// Code generated by sqlgen. DO NOT EDIT.

package models

import (
	"context"
	"fmt"

	"github.com/davidbyttow/sqlgen"
)

// postLoaders maps relationship names to their loader functions.
var postLoaders = map[string]sqlgen.LoadFunc{}

func init() {
	postLoaders["User"] = loadPostUser
	postLoaders["Tags"] = loadPostTags
}

// LoadRelations eagerly loads the specified relationships for a slice of Post.
func (s PostSlice) LoadRelations(ctx context.Context, exec sqlgen.Executor, loads ...*sqlgen.EagerLoadRequest) error {
	for _, load := range loads {
		fn, ok := postLoaders[load.Name]
		if !ok {
			return fmt.Errorf("unknown relationship %q on Post", load.Name)
		}
		if err := fn(ctx, exec, dialect, s, loads); err != nil {
			return fmt.Errorf("loading %s: %w", load.Name, err)
		}
	}
	return nil
}

// postLoadMods extracts query mods for the named relationship from the load requests.
func postLoadMods(loads []*sqlgen.EagerLoadRequest, name string) []sqlgen.QueryMod {
	for _, l := range loads {
		if l.Name == name {
			return l.Mods
		}
	}
	return nil
}

func loadPostUser(ctx context.Context, exec sqlgen.Executor, d sqlgen.Dialect, parentModels any, loads []*sqlgen.EagerLoadRequest) error {
	models := parentModels.(PostSlice)
	if len(models) == 0 {
		return nil
	}

	// Collect unique FK values.
	seen := make(map[string]bool)
	var ids []any
	for _, m := range models {
		key := fmt.Sprint(m.AuthorID)
		if !seen[key] {
			seen[key] = true
			ids = append(ids, m.AuthorID)
		}
	}

	mods := postLoadMods(loads, "User")
	rows, err := sqlgen.LoadMany(ctx, exec, d, UserTableName, "id", ids, mods...)
	if err != nil {
		return err
	}
	if rows == nil {
		return nil
	}
	defer rows.Close()

	resultMap := make(map[string]*User)
	for rows.Next() {
		o := &User{}
		if err := o.ScanRow(rows); err != nil {
			return err
		}
		resultMap[fmt.Sprint(o.ID)] = o
	}
	if err := rows.Err(); err != nil {
		return err
	}

	for _, m := range models {
		o := resultMap[fmt.Sprint(m.AuthorID)]
		if o != nil {
			if m.R == nil {
				m.R = &PostRels{}
			}
			m.R.User = o
		}
	}
	return nil
}

func loadPostTags(ctx context.Context, exec sqlgen.Executor, d sqlgen.Dialect, parentModels any, loads []*sqlgen.EagerLoadRequest) error {
	models := parentModels.(PostSlice)
	if len(models) == 0 {
		return nil
	}

	// Collect parent PK values.
	ids := make([]any, len(models))
	idMap := make(map[string][]*Post)
	for i, m := range models {
		ids[i] = m.ID
		key := fmt.Sprint(m.ID)
		idMap[key] = append(idMap[key], m)
	}

	mods := postLoadMods(loads, "Tags")
	rows, joinKeyAlias, err := sqlgen.LoadManyToMany(ctx, exec, d,
		TagTableName,
		"post_tags",
		"post_id",
		"tag_id",
		"id",
		ids,
		mods...,
	)
	if err != nil {
		return err
	}
	if rows == nil {
		return nil
	}
	defer rows.Close()
	_ = joinKeyAlias

	for rows.Next() {
		o := &Tag{}
		var joinKey any
		// ScanRow scans all target columns; we also need the join key column appended by the query.
		if err := rows.Scan(
			&o.ID,
			&o.Name,
			&joinKey,
		); err != nil {
			return err
		}
		key := fmt.Sprint(joinKey)
		for _, parent := range idMap[key] {
			if parent.R == nil {
				parent.R = &PostRels{}
			}
			parent.R.Tags = append(parent.R.Tags, o)
		}
	}
	if err := rows.Err(); err != nil {
		return err
	}

	// Handle nested loads.
	for _, l := range loads {
		if l.Name == "Tags" && len(l.Nested) > 0 {
			var all TagSlice
			for _, m := range models {
				if m.R != nil {
					all = append(all, m.R.Tags...)
				}
			}
			if err := all.LoadRelations(ctx, exec, l.Nested...); err != nil {
				return err
			}
		}
	}
	return nil
}
