// Code generated by sqlgen. DO NOT EDIT.

package models

import (
	"context"
	"fmt"

	"github.com/davidbyttow/sqlgen"
)

// tagLoaders maps relationship names to their loader functions.
var tagLoaders = map[string]sqlgen.LoadFunc{}

func init() {
	tagLoaders["Posts"] = loadTagPosts
}

// LoadRelations eagerly loads the specified relationships for a slice of Tag.
func (s TagSlice) LoadRelations(ctx context.Context, exec sqlgen.Executor, loads ...*sqlgen.EagerLoadRequest) error {
	for _, load := range loads {
		fn, ok := tagLoaders[load.Name]
		if !ok {
			return fmt.Errorf("unknown relationship %q on Tag", load.Name)
		}
		if err := fn(ctx, exec, dialect, s, loads); err != nil {
			return fmt.Errorf("loading %s: %w", load.Name, err)
		}
	}
	return nil
}

// tagLoadMods extracts query mods for the named relationship from the load requests.
func tagLoadMods(loads []*sqlgen.EagerLoadRequest, name string) []sqlgen.QueryMod {
	for _, l := range loads {
		if l.Name == name {
			return l.Mods
		}
	}
	return nil
}

func loadTagPosts(ctx context.Context, exec sqlgen.Executor, d sqlgen.Dialect, parentModels any, loads []*sqlgen.EagerLoadRequest) error {
	models := parentModels.(TagSlice)
	if len(models) == 0 {
		return nil
	}

	// Collect parent PK values.
	ids := make([]any, len(models))
	idMap := make(map[string][]*Tag)
	for i, m := range models {
		ids[i] = m.ID
		key := fmt.Sprint(m.ID)
		idMap[key] = append(idMap[key], m)
	}

	mods := tagLoadMods(loads, "Posts")
	rows, joinKeyAlias, err := sqlgen.LoadManyToMany(ctx, exec, d,
		PostTableName,
		"post_tags",
		"tag_id",
		"post_id",
		"id",
		ids,
		mods...,
	)
	if err != nil {
		return err
	}
	if rows == nil {
		return nil
	}
	defer rows.Close()
	_ = joinKeyAlias

	for rows.Next() {
		o := &Post{}
		var joinKey any
		// ScanRow scans all target columns; we also need the join key column appended by the query.
		if err := rows.Scan(
			&o.ID,
			&o.AuthorID,
			&o.Title,
			&o.Body,
			&o.Status,
			&o.CreatedAt,
			&o.PublishedAt,
			&joinKey,
		); err != nil {
			return err
		}
		key := fmt.Sprint(joinKey)
		for _, parent := range idMap[key] {
			if parent.R == nil {
				parent.R = &TagRels{}
			}
			parent.R.Posts = append(parent.R.Posts, o)
		}
	}
	if err := rows.Err(); err != nil {
		return err
	}

	// Handle nested loads.
	for _, l := range loads {
		if l.Name == "Posts" && len(l.Nested) > 0 {
			var all PostSlice
			for _, m := range models {
				if m.R != nil {
					all = append(all, m.R.Posts...)
				}
			}
			if err := all.LoadRelations(ctx, exec, l.Nested...); err != nil {
				return err
			}
		}
	}
	return nil
}
