// Code generated by sqlgen. DO NOT EDIT.

package models

import (
	"time"

	"github.com/davidbyttow/sqlgen/runtime"
)

// postUserPreload holds nullable scan targets for LEFT JOINed User columns.
type postUserPreload struct {
	id        runtime.Null[string]
	email     runtime.Null[string]
	name      runtime.Null[string]
	bio       runtime.Null[string]
	createdAt runtime.Null[time.Time]
}

func (p *postUserPreload) scanDests() []any {
	return []any{
		&p.id,
		&p.email,
		&p.name,
		&p.bio,
		&p.createdAt,
	}
}

func (p *postUserPreload) assign(o *Post) {
	if !p.id.Valid {
		return
	}
	if o.R == nil {
		o.R = &PostRels{}
	}
	o.R.User = &User{
		ID:        p.id.Val,
		Email:     p.email.Val,
		Name:      p.name.Val,
		Bio:       p.bio,
		CreatedAt: p.createdAt.Val,
	}
}

// PostPreloadUser is the PreloadDef for the User relationship.
var PostPreloadUser = runtime.PreloadDef{
	Name:     "User",
	Table:    UserTableName,
	JoinCond: "\"users\".\"id\" = \"posts\".\"author_id\"",
	Columns: []string{
		"\"users\".\"id\"",
		"\"users\".\"email\"",
		"\"users\".\"name\"",
		"\"users\".\"bio\"",
		"\"users\".\"created_at\"",
	},
}

// postPreloadState is the interface for preload scan states.
type postPreloadState interface {
	scanDests() []any
	assign(o *Post)
}

// newPostPreloadState returns a preload state for the named relationship.
func newPostPreloadState(name string) postPreloadState {
	switch name {
	case "User":
		return &postUserPreload{}
	}
	return nil
}
