// Code generated by sqlgen. DO NOT EDIT.

package models

import "github.com/davidbyttow/sqlgen/runtime"

// userHooks stores the hooks for User.
var userHooks = runtime.NewHooks()

// AddUserHook registers a hook for the given hook point.
func AddUserHook(point runtime.HookPoint, fn runtime.Hook) {
	userHooks.Add(point, fn)
}
