// Code generated by sqlgen. DO NOT EDIT.

package models

import (
	"time"

	"github.com/davidbyttow/sqlgen"
)

// PostTableName is the database table name.
const PostTableName = "posts"

// PostColumns contains all column names for the posts table.
var PostColumns = struct {
	ID          string
	AuthorID    string
	Title       string
	Body        string
	Status      string
	CreatedAt   string
	PublishedAt string
}{
	ID:          "id",
	AuthorID:    "author_id",
	Title:       "title",
	Body:        "body",
	Status:      "status",
	CreatedAt:   "created_at",
	PublishedAt: "published_at",
}

// Post represents a row from the 'posts' table.
type Post struct {
	ID          string                  `db:"id" json:"id"`
	AuthorID    string                  `db:"author_id" json:"author_id"`
	Title       string                  `db:"title" json:"title"`
	Body        string                  `db:"body" json:"body"`
	Status      PostStatus              `db:"status" json:"status"`
	CreatedAt   time.Time               `db:"created_at" json:"created_at"`
	PublishedAt sqlgen.Null[time.Time] `db:"published_at" json:"published_at"`

	R *PostRels `db:"-" json:"-"`
}

// PostRels holds eagerly loaded relationships.
type PostRels struct {
	User      *User
	Tags      []*Tag
	TagsCount *int64
}

// PostSlice is a slice of Post pointers.
type PostSlice []*Post

// ScanRow scans a database row into a Post.
func (o *Post) ScanRow(rows interface{ Scan(...any) error }) error {
	return rows.Scan(
		&o.ID,
		&o.AuthorID,
		&o.Title,
		&o.Body,
		&o.Status,
		&o.CreatedAt,
		&o.PublishedAt,
	)
}

// scanDests returns scan destinations for all columns (used by preload-aware queries).
func (o *Post) scanDests() []any {
	return []any{
		&o.ID,
		&o.AuthorID,
		&o.Title,
		&o.Body,
		&o.Status,
		&o.CreatedAt,
		&o.PublishedAt,
	}
}
