// Code generated by sqlgen. DO NOT EDIT.

package models

import (
	"context"
	"time"

	"github.com/davidbyttow/sqlgen"
)

// Posts returns a query builder for the posts table.
func Posts(mods ...sqlgen.QueryMod) *sqlgen.Query {
	return sqlgen.NewQuery(dialect, PostTableName, mods...)
}

// FindPostByPK finds a Post by primary key.
func FindPostByPK(ctx context.Context, exec sqlgen.Executor, id string) (*Post, error) {
	q := sqlgen.NewQuery(dialect, PostTableName,
		sqlgen.Where("\"id\" = ?", id),
		sqlgen.Limit(1),
	)

	query, args := q.BuildSelect()
	row := exec.QueryRowContext(ctx, query, args...)

	o := &Post{}
	if err := o.ScanRow(row); err != nil {
		return nil, err
	}
	return o, nil
}

// AllPosts retrieves all rows from the posts table with the given query mods.
// Supports Preload() for LEFT JOIN eager loading of to-one relationships.
func AllPosts(ctx context.Context, exec sqlgen.Executor, mods ...sqlgen.QueryMod) (PostSlice, error) {
	q := sqlgen.NewQuery(dialect, PostTableName, mods...)
	query, args := q.BuildSelect()
	rows, err := exec.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	preloads := q.Preloads()

	var result PostSlice
	for rows.Next() {
		o := &Post{}
		if len(preloads) == 0 {
			if err := o.ScanRow(rows); err != nil {
				return nil, err
			}
		} else {
			dests := o.scanDests()
			var states []postPreloadState
			for _, p := range preloads {
				ps := newPostPreloadState(p.Name)
				if ps != nil {
					dests = append(dests, ps.scanDests()...)
					states = append(states, ps)
				}
			}
			if err := rows.Scan(dests...); err != nil {
				return nil, err
			}
			for _, ps := range states {
				ps.assign(o)
			}
		}
		result = append(result, o)
	}
	return result, rows.Err()
}

// Insert inserts the Post into the database.
// Optional Columns parameter controls which columns are included (Whitelist/Blacklist).
func (o *Post) Insert(ctx context.Context, exec sqlgen.Executor, cols ...sqlgen.Columns) error {
	ctx, err := postHooks.RunIfEnabled(ctx, exec, sqlgen.BeforeInsert, o)
	if err != nil {
		return err
	}
	o.CreatedAt = time.Now()
	allCols := []string{"id", "author_id", "title", "body", "status", "created_at", "published_at"}
	allVals := []any{o.ID, o.AuthorID, o.Title, o.Body, o.Status, o.CreatedAt, o.PublishedAt}
	allCols, allVals = sqlgen.FilterColumns(allCols, allVals, cols...)

	returning := []string{"id", "author_id", "title", "body", "status", "created_at", "published_at"}

	query, args := sqlgen.BuildInsert(dialect, PostTableName, allCols, allVals, returning)
	err = exec.QueryRowContext(ctx, query, args...).Scan(
		&o.ID,
		&o.AuthorID,
		&o.Title,
		&o.Body,
		&o.Status,
		&o.CreatedAt,
		&o.PublishedAt,
	)
	if err != nil {
		return err
	}
	_, err = postHooks.RunIfEnabled(ctx, exec, sqlgen.AfterInsert, o)
	return err
}

// Update updates the Post in the database. Only non-PK columns are updated.
// Optional Columns parameter controls which columns are included (Whitelist/Blacklist).
func (o *Post) Update(ctx context.Context, exec sqlgen.Executor, cols ...sqlgen.Columns) error {
	ctx, err := postHooks.RunIfEnabled(ctx, exec, sqlgen.BeforeUpdate, o)
	if err != nil {
		return err
	}
	setCols := []string{"author_id", "title", "body", "status", "created_at", "published_at"}
	setVals := []any{o.AuthorID, o.Title, o.Body, o.Status, o.CreatedAt, o.PublishedAt}
	setCols, setVals = sqlgen.FilterColumns(setCols, setVals, cols...)

	whereClauses := []string{"\"id\" = ?"}
	whereArgs := []any{o.ID}

	query, args := sqlgen.BuildUpdate(dialect, PostTableName, setCols, setVals, whereClauses, whereArgs)
	_, err = exec.ExecContext(ctx, query, args...)
	if err != nil {
		return err
	}
	_, err = postHooks.RunIfEnabled(ctx, exec, sqlgen.AfterUpdate, o)
	return err
}

// Delete deletes the Post from the database.
func (o *Post) Delete(ctx context.Context, exec sqlgen.Executor) error {
	ctx, err := postHooks.RunIfEnabled(ctx, exec, sqlgen.BeforeDelete, o)
	if err != nil {
		return err
	}

	whereClauses := []string{"\"id\" = ?"}
	whereArgs := []any{o.ID}

	query, args := sqlgen.BuildDelete(dialect, PostTableName, whereClauses, whereArgs)
	_, err = exec.ExecContext(ctx, query, args...)
	if err != nil {
		return err
	}
	_, err = postHooks.RunIfEnabled(ctx, exec, sqlgen.AfterDelete, o)
	return err
}

// Upsert inserts or updates the Post based on the primary key.
// Optional Columns parameter controls which non-PK columns are included (Whitelist/Blacklist).
func (o *Post) Upsert(ctx context.Context, exec sqlgen.Executor, cols ...sqlgen.Columns) error {
	ctx, err := postHooks.RunIfEnabled(ctx, exec, sqlgen.BeforeUpsert, o)
	if err != nil {
		return err
	}
	allCols := []string{"id", "author_id", "title", "body", "status", "created_at", "published_at"}
	allVals := []any{o.ID, o.AuthorID, o.Title, o.Body, o.Status, o.CreatedAt, o.PublishedAt}
	allCols, allVals = sqlgen.FilterColumns(allCols, allVals, cols...)
	conflictCols := []string{"id"}
	updateCols := []string{"author_id", "title", "body", "status", "created_at", "published_at"}
	updateCols, _ = sqlgen.FilterColumns(updateCols, make([]any, len(updateCols)), cols...)
	returning := []string{"id", "author_id", "title", "body", "status", "created_at", "published_at"}

	query, args := sqlgen.BuildUpsert(dialect, PostTableName, allCols, allVals, conflictCols, updateCols, returning)
	err = exec.QueryRowContext(ctx, query, args...).Scan(
		&o.ID,
		&o.AuthorID,
		&o.Title,
		&o.Body,
		&o.Status,
		&o.CreatedAt,
		&o.PublishedAt,
	)
	if err != nil {
		return err
	}
	_, err = postHooks.RunIfEnabled(ctx, exec, sqlgen.AfterUpsert, o)
	return err
}

// Exists checks if a row with the given primary key exists.
func PostExists(ctx context.Context, exec sqlgen.Executor, id string) (bool, error) {
	return sqlgen.Exists(ctx, exec, dialect, PostTableName,
		sqlgen.Where("\"id\" = ?", id),
	)
}

// CountPosts returns the count of rows matching the query mods.
func CountPosts(ctx context.Context, exec sqlgen.Executor, mods ...sqlgen.QueryMod) (int64, error) {
	return sqlgen.Count(ctx, exec, dialect, PostTableName, mods...)
}

// UpdateAllPosts updates all rows matching the given mods.
// set is a map of column name -> new value.
func UpdateAllPosts(ctx context.Context, exec sqlgen.Executor, set map[string]any, mods ...sqlgen.QueryMod) (int64, error) {
	q := sqlgen.NewQuery(dialect, PostTableName, mods...)
	query, args := q.BuildUpdateAll(set)
	result, err := exec.ExecContext(ctx, query, args...)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

// DeleteAllPosts deletes all rows matching the given mods.
func DeleteAllPosts(ctx context.Context, exec sqlgen.Executor, mods ...sqlgen.QueryMod) (int64, error) {
	q := sqlgen.NewQuery(dialect, PostTableName, mods...)
	query, args := q.BuildDeleteAll()
	result, err := exec.ExecContext(ctx, query, args...)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

// EachPost executes a query and calls fn for each row. Iteration stops
// early if fn returns an error. Rows are not accumulated in memory.
func EachPost(ctx context.Context, exec sqlgen.Executor, fn func(*Post) error, mods ...sqlgen.QueryMod) error {
	return sqlgen.Each(ctx, exec, sqlgen.NewQuery(dialect, PostTableName, mods...), func() *Post { return &Post{} }, fn)
}

// PostCursor returns a cursor for iterating over posts rows one at a time.
func PostCursor(ctx context.Context, exec sqlgen.Executor, mods ...sqlgen.QueryMod) (*sqlgen.Cursor[*Post], error) {
	return sqlgen.NewCursor(ctx, exec, sqlgen.NewQuery(dialect, PostTableName, mods...), func() *Post { return &Post{} })
}

// Reload refreshes the Post from the database using its primary key.
func (o *Post) Reload(ctx context.Context, exec sqlgen.Executor) error {
	q := sqlgen.NewQuery(dialect, PostTableName,
		sqlgen.Where("\"id\" = ?", o.ID),
		sqlgen.Limit(1),
	)
	query, args := q.BuildSelect()
	return o.ScanRow(exec.QueryRowContext(ctx, query, args...))
}

// UpdateAll updates all models in the slice with the given column values.
func (s PostSlice) UpdateAll(ctx context.Context, exec sqlgen.Executor, set map[string]any) (int64, error) {
	if len(s) == 0 {
		return 0, nil
	}
	ids := make([]any, len(s))
	for i, o := range s {
		ids[i] = o.ID
	}
	return UpdateAllPosts(ctx, exec, set, sqlgen.WhereIn("\"id\"", ids...))
}

// DeleteAll deletes all models in the slice.
func (s PostSlice) DeleteAll(ctx context.Context, exec sqlgen.Executor) (int64, error) {
	if len(s) == 0 {
		return 0, nil
	}
	ids := make([]any, len(s))
	for i, o := range s {
		ids[i] = o.ID
	}
	return DeleteAllPosts(ctx, exec, sqlgen.WhereIn("\"id\"", ids...))
}

// InsertAll batch-inserts all models in the slice. Each model's columns are
// scanned back via RETURNING, picking up defaults and generated values.
// Hooks are not fired (consistent with UpdateAll/DeleteAll).
func (s PostSlice) InsertAll(ctx context.Context, exec sqlgen.Executor) error {
	if len(s) == 0 {
		return nil
	}
	now := time.Now()
	for _, o := range s {
		o.CreatedAt = now
	}
	cols := []string{"id", "author_id", "title", "body", "status", "created_at", "published_at"}
	returning := []string{"id", "author_id", "title", "body", "status", "created_at", "published_at"}

	rows := make([][]any, len(s))
	for i, o := range s {
		rows[i] = []any{o.ID, o.AuthorID, o.Title, o.Body, o.Status, o.CreatedAt, o.PublishedAt}
	}

	query, args := sqlgen.BuildBatchInsert(dialect, PostTableName, cols, rows, returning)
	result, err := exec.QueryContext(ctx, query, args...)
	if err != nil {
		return err
	}
	defer result.Close()

	idx := 0
	for result.Next() {
		if err := s[idx].ScanRow(result); err != nil {
			return err
		}
		idx++
	}
	return result.Err()
}
