// Code generated by sqlgen. DO NOT EDIT.

package models

import "github.com/davidbyttow/sqlgen/runtime"

// tagHooks stores the hooks for Tag.
var tagHooks = runtime.NewHooks()

// AddTagHook registers a hook for the given hook point.
func AddTagHook(point runtime.HookPoint, fn runtime.Hook) {
	tagHooks.Add(point, fn)
}
