// Code generated by sqlgen. DO NOT EDIT.

package models

import (
	"context"

	"github.com/davidbyttow/sqlgen/runtime"
)

// PostTags returns a query builder for the post_tags table.
func PostTags(mods ...runtime.QueryMod) *runtime.Query {
	return runtime.NewQuery(dialect, PostTagTableName, mods...)
}

// FindPostTagByPK finds a PostTag by primary key.
func FindPostTagByPK(ctx context.Context, exec runtime.Executor, postID string, tagID int32) (*PostTag, error) {
	q := runtime.NewQuery(dialect, PostTagTableName,
		runtime.Where("\"post_id\" = ?", postID),
		runtime.Where("\"tag_id\" = ?", tagID),
		runtime.Limit(1),
	)

	query, args := q.BuildSelect()
	row := exec.QueryRowContext(ctx, query, args...)

	o := &PostTag{}
	if err := o.ScanRow(row); err != nil {
		return nil, err
	}
	return o, nil
}

// AllPostTags retrieves all rows from the post_tags table with the given query mods.
// Supports Preload() for LEFT JOIN eager loading of to-one relationships.
func AllPostTags(ctx context.Context, exec runtime.Executor, mods ...runtime.QueryMod) (PostTagSlice, error) {
	q := runtime.NewQuery(dialect, PostTagTableName, mods...)
	query, args := q.BuildSelect()
	rows, err := exec.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var result PostTagSlice
	for rows.Next() {
		o := &PostTag{}
		if err := o.ScanRow(rows); err != nil {
			return nil, err
		}
		result = append(result, o)
	}
	return result, rows.Err()
}

// Insert inserts the PostTag into the database.
// Optional Columns parameter controls which columns are included (Whitelist/Blacklist).
func (o *PostTag) Insert(ctx context.Context, exec runtime.Executor, cols ...runtime.Columns) error {
	ctx, err := posttagHooks.RunIfEnabled(ctx, exec, runtime.BeforeInsert, o)
	if err != nil {
		return err
	}
	allCols := []string{"post_id", "tag_id"}
	allVals := []any{o.PostID, o.TagID}
	allCols, allVals = runtime.FilterColumns(allCols, allVals, cols...)

	returning := []string{"post_id", "tag_id"}

	query, args := runtime.BuildInsert(dialect, PostTagTableName, allCols, allVals, returning)
	err = exec.QueryRowContext(ctx, query, args...).Scan(
		&o.PostID,
		&o.TagID,
	)
	if err != nil {
		return err
	}
	_, err = posttagHooks.RunIfEnabled(ctx, exec, runtime.AfterInsert, o)
	return err
}

// Update updates the PostTag in the database. Only non-PK columns are updated.
// Optional Columns parameter controls which columns are included (Whitelist/Blacklist).
func (o *PostTag) Update(ctx context.Context, exec runtime.Executor, cols ...runtime.Columns) error {
	ctx, err := posttagHooks.RunIfEnabled(ctx, exec, runtime.BeforeUpdate, o)
	if err != nil {
		return err
	}
	setCols := []string{}
	setVals := []any{}
	setCols, setVals = runtime.FilterColumns(setCols, setVals, cols...)

	whereClauses := []string{"\"post_id\" = ?", "\"tag_id\" = ?"}
	whereArgs := []any{o.PostID, o.TagID}

	query, args := runtime.BuildUpdate(dialect, PostTagTableName, setCols, setVals, whereClauses, whereArgs)
	_, err = exec.ExecContext(ctx, query, args...)
	if err != nil {
		return err
	}
	_, err = posttagHooks.RunIfEnabled(ctx, exec, runtime.AfterUpdate, o)
	return err
}

// Delete deletes the PostTag from the database.
func (o *PostTag) Delete(ctx context.Context, exec runtime.Executor) error {
	ctx, err := posttagHooks.RunIfEnabled(ctx, exec, runtime.BeforeDelete, o)
	if err != nil {
		return err
	}

	whereClauses := []string{"\"post_id\" = ?", "\"tag_id\" = ?"}
	whereArgs := []any{o.PostID, o.TagID}

	query, args := runtime.BuildDelete(dialect, PostTagTableName, whereClauses, whereArgs)
	_, err = exec.ExecContext(ctx, query, args...)
	if err != nil {
		return err
	}
	_, err = posttagHooks.RunIfEnabled(ctx, exec, runtime.AfterDelete, o)
	return err
}

// Upsert inserts or updates the PostTag based on the primary key.
// Optional Columns parameter controls which non-PK columns are included (Whitelist/Blacklist).
func (o *PostTag) Upsert(ctx context.Context, exec runtime.Executor, cols ...runtime.Columns) error {
	ctx, err := posttagHooks.RunIfEnabled(ctx, exec, runtime.BeforeUpsert, o)
	if err != nil {
		return err
	}
	allCols := []string{"post_id", "tag_id"}
	allVals := []any{o.PostID, o.TagID}
	allCols, allVals = runtime.FilterColumns(allCols, allVals, cols...)
	conflictCols := []string{"post_id", "tag_id"}
	updateCols := []string{}
	updateCols, _ = runtime.FilterColumns(updateCols, make([]any, len(updateCols)), cols...)
	returning := []string{"post_id", "tag_id"}

	query, args := runtime.BuildUpsert(dialect, PostTagTableName, allCols, allVals, conflictCols, updateCols, returning)
	err = exec.QueryRowContext(ctx, query, args...).Scan(
		&o.PostID,
		&o.TagID,
	)
	if err != nil {
		return err
	}
	_, err = posttagHooks.RunIfEnabled(ctx, exec, runtime.AfterUpsert, o)
	return err
}

// Exists checks if a row with the given primary key exists.
func PostTagExists(ctx context.Context, exec runtime.Executor, postID string, tagID int32) (bool, error) {
	return runtime.Exists(ctx, exec, dialect, PostTagTableName,
		runtime.Where("\"post_id\" = ?", postID),
		runtime.Where("\"tag_id\" = ?", tagID),
	)
}

// CountPostTags returns the count of rows matching the query mods.
func CountPostTags(ctx context.Context, exec runtime.Executor, mods ...runtime.QueryMod) (int64, error) {
	return runtime.Count(ctx, exec, dialect, PostTagTableName, mods...)
}

// UpdateAllPostTags updates all rows matching the given mods.
// set is a map of column name -> new value.
func UpdateAllPostTags(ctx context.Context, exec runtime.Executor, set map[string]any, mods ...runtime.QueryMod) (int64, error) {
	q := runtime.NewQuery(dialect, PostTagTableName, mods...)
	query, args := q.BuildUpdateAll(set)
	result, err := exec.ExecContext(ctx, query, args...)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

// DeleteAllPostTags deletes all rows matching the given mods.
func DeleteAllPostTags(ctx context.Context, exec runtime.Executor, mods ...runtime.QueryMod) (int64, error) {
	q := runtime.NewQuery(dialect, PostTagTableName, mods...)
	query, args := q.BuildDeleteAll()
	result, err := exec.ExecContext(ctx, query, args...)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

// EachPostTag executes a query and calls fn for each row. Iteration stops
// early if fn returns an error. Rows are not accumulated in memory.
func EachPostTag(ctx context.Context, exec runtime.Executor, fn func(*PostTag) error, mods ...runtime.QueryMod) error {
	return runtime.Each(ctx, exec, runtime.NewQuery(dialect, PostTagTableName, mods...), func() *PostTag { return &PostTag{} }, fn)
}

// PostTagCursor returns a cursor for iterating over post_tags rows one at a time.
func PostTagCursor(ctx context.Context, exec runtime.Executor, mods ...runtime.QueryMod) (*runtime.Cursor[*PostTag], error) {
	return runtime.NewCursor(ctx, exec, runtime.NewQuery(dialect, PostTagTableName, mods...), func() *PostTag { return &PostTag{} })
}

// Reload refreshes the PostTag from the database using its primary key.
func (o *PostTag) Reload(ctx context.Context, exec runtime.Executor) error {
	q := runtime.NewQuery(dialect, PostTagTableName,
		runtime.Where("\"post_id\" = ?", o.PostID),
		runtime.Where("\"tag_id\" = ?", o.TagID),
		runtime.Limit(1),
	)
	query, args := q.BuildSelect()
	return o.ScanRow(exec.QueryRowContext(ctx, query, args...))
}
