// Code generated by sqlgen. DO NOT EDIT.

package models

import (
	"context"

	"github.com/davidbyttow/sqlgen/runtime"
)

// AddPosts adds models to the Posts relationship by setting their FK.
func (o *User) AddPosts(ctx context.Context, exec runtime.Executor, related ...*Post) error {
	for _, r := range related {
		r.AuthorID = o.ID
		query := "UPDATE " + dialect.QuoteIdent(PostTableName) +
			" SET " + dialect.QuoteIdent("author_id") + " = " + dialect.Placeholder(1) +
			" WHERE " + dialect.QuoteIdent("id") + " = " + dialect.Placeholder(2)
		_, err := exec.ExecContext(ctx, query, r.AuthorID, r.ID)
		if err != nil {
			return err
		}
	}
	if o.R == nil {
		o.R = &UserRels{}
	}
	o.R.Posts = append(o.R.Posts, related...)
	return nil
}
