// Code generated by sqlgen. DO NOT EDIT.

package models

import (
	"context"
	"fmt"

	"github.com/davidbyttow/sqlgen/runtime"
)

// tagCountLoaders maps relationship names to their count loader functions.
var tagCountLoaders = map[string]runtime.CountLoadFunc{}

func init() {
	tagCountLoaders["Posts"] = loadCountTagPosts
}

// LoadCountRelations loads counts for the specified relationships.
// Pass relationship names (e.g., "Posts", "Tags") to load their counts.
func (s TagSlice) LoadCountRelations(ctx context.Context, exec runtime.Executor, names ...string) error {
	for _, name := range names {
		fn, ok := tagCountLoaders[name]
		if !ok {
			return fmt.Errorf("unknown count relationship %q on Tag", name)
		}
		if err := fn(ctx, exec, dialect, s); err != nil {
			return fmt.Errorf("loading count for %s: %w", name, err)
		}
	}
	return nil
}

func loadCountTagPosts(ctx context.Context, exec runtime.Executor, d runtime.Dialect, parentModels any) error {
	models := parentModels.(TagSlice)
	if len(models) == 0 {
		return nil
	}

	ids := make([]any, len(models))
	for i, m := range models {
		ids[i] = m.ID
	}

	counts, err := runtime.LoadManyToManyCount(ctx, exec, d, "post_tags", "tag_id", "post_id", ids)
	if err != nil {
		return err
	}

	for _, m := range models {
		if m.R == nil {
			m.R = &TagRels{}
		}
		key := fmt.Sprint(m.ID)
		c := counts[key]
		m.R.PostsCount = &c
	}
	return nil
}
