// Code generated by sqlgen. DO NOT EDIT.

package models

import "github.com/davidbyttow/sqlgen/runtime"

// TagWhere provides type-safe where clause builders for each column.
var TagWhere = struct {
	ID   TagIDFilter
	Name TagNameFilter
}{
	ID:   TagIDFilter{col: "id"},
	Name: TagNameFilter{col: "name"},
}

// TagIDFilter provides where clauses for the id column.
type TagIDFilter struct {
	col string
}

func (f TagIDFilter) EQ(val int32) runtime.QueryMod {
	return runtime.Where("\""+f.col+"\" = ?", val)
}

func (f TagIDFilter) NEQ(val int32) runtime.QueryMod {
	return runtime.Where("\""+f.col+"\" != ?", val)
}

func (f TagIDFilter) LT(val int32) runtime.QueryMod {
	return runtime.Where("\""+f.col+"\" < ?", val)
}

func (f TagIDFilter) LTE(val int32) runtime.QueryMod {
	return runtime.Where("\""+f.col+"\" <= ?", val)
}

func (f TagIDFilter) GT(val int32) runtime.QueryMod {
	return runtime.Where("\""+f.col+"\" > ?", val)
}

func (f TagIDFilter) GTE(val int32) runtime.QueryMod {
	return runtime.Where("\""+f.col+"\" >= ?", val)
}

func (f TagIDFilter) IN(vals ...int32) runtime.QueryMod {
	args := make([]any, len(vals))
	for i, v := range vals {
		args[i] = v
	}
	placeholders := make([]byte, 0, len(vals)*2)
	for i := range vals {
		if i > 0 {
			placeholders = append(placeholders, ',', ' ')
		}
		placeholders = append(placeholders, '?')
	}
	return runtime.Where("\""+f.col+"\" IN ("+string(placeholders)+")", args...)
}

// TagNameFilter provides where clauses for the name column.
type TagNameFilter struct {
	col string
}

func (f TagNameFilter) EQ(val string) runtime.QueryMod {
	return runtime.Where("\""+f.col+"\" = ?", val)
}

func (f TagNameFilter) NEQ(val string) runtime.QueryMod {
	return runtime.Where("\""+f.col+"\" != ?", val)
}

func (f TagNameFilter) LT(val string) runtime.QueryMod {
	return runtime.Where("\""+f.col+"\" < ?", val)
}

func (f TagNameFilter) LTE(val string) runtime.QueryMod {
	return runtime.Where("\""+f.col+"\" <= ?", val)
}

func (f TagNameFilter) GT(val string) runtime.QueryMod {
	return runtime.Where("\""+f.col+"\" > ?", val)
}

func (f TagNameFilter) GTE(val string) runtime.QueryMod {
	return runtime.Where("\""+f.col+"\" >= ?", val)
}

func (f TagNameFilter) IN(vals ...string) runtime.QueryMod {
	args := make([]any, len(vals))
	for i, v := range vals {
		args[i] = v
	}
	placeholders := make([]byte, 0, len(vals)*2)
	for i := range vals {
		if i > 0 {
			placeholders = append(placeholders, ',', ' ')
		}
		placeholders = append(placeholders, '?')
	}
	return runtime.Where("\""+f.col+"\" IN ("+string(placeholders)+")", args...)
}
