// Code generated by sqlgen. DO NOT EDIT.

package models

import (
	"context"

	"github.com/davidbyttow/sqlgen/runtime"
)

// Tags returns a query builder for the tags table.
func Tags(mods ...runtime.QueryMod) *runtime.Query {
	return runtime.NewQuery(dialect, TagTableName, mods...)
}

// FindTagByPK finds a Tag by primary key.
func FindTagByPK(ctx context.Context, exec runtime.Executor, id int32) (*Tag, error) {
	q := runtime.NewQuery(dialect, TagTableName,
		runtime.Where("\"id\" = ?", id),
		runtime.Limit(1),
	)

	query, args := q.BuildSelect()
	row := exec.QueryRowContext(ctx, query, args...)

	o := &Tag{}
	if err := o.ScanRow(row); err != nil {
		return nil, err
	}
	return o, nil
}

// AllTags retrieves all rows from the tags table with the given query mods.
func AllTags(ctx context.Context, exec runtime.Executor, mods ...runtime.QueryMod) (TagSlice, error) {
	q := runtime.NewQuery(dialect, TagTableName, mods...)
	query, args := q.BuildSelect()
	rows, err := exec.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var result TagSlice
	for rows.Next() {
		o := &Tag{}
		if err := o.ScanRow(rows); err != nil {
			return nil, err
		}
		result = append(result, o)
	}
	return result, rows.Err()
}

// Insert inserts the Tag into the database.
func (o *Tag) Insert(ctx context.Context, exec runtime.Executor) error {
	ctx, err := tagHooks.RunIfEnabled(ctx, runtime.BeforeInsert)
	if err != nil {
		return err
	}
	query, args := runtime.BuildInsert(dialect, TagTableName,
		[]string{"name"},
		[]any{o.Name},
		[]string{"id"},
	)

	err = exec.QueryRowContext(ctx, query, args...).Scan(
		&o.ID,
	)
	if err != nil {
		return err
	}

	_, err = tagHooks.RunIfEnabled(ctx, runtime.AfterInsert)
	return err
}

// Update updates the Tag in the database. Only non-PK columns are updated.
func (o *Tag) Update(ctx context.Context, exec runtime.Executor) error {
	ctx, err := tagHooks.RunIfEnabled(ctx, runtime.BeforeUpdate)
	if err != nil {
		return err
	}
	setCols := []string{"name"}
	setVals := []any{o.Name}

	whereClauses := []string{"\"id\" = ?"}
	whereArgs := []any{o.ID}

	query, args := runtime.BuildUpdate(dialect, TagTableName, setCols, setVals, whereClauses, whereArgs)
	_, err = exec.ExecContext(ctx, query, args...)
	if err != nil {
		return err
	}

	_, err = tagHooks.RunIfEnabled(ctx, runtime.AfterUpdate)
	return err
}

// Delete deletes the Tag from the database.
func (o *Tag) Delete(ctx context.Context, exec runtime.Executor) error {
	ctx, err := tagHooks.RunIfEnabled(ctx, runtime.BeforeDelete)
	if err != nil {
		return err
	}

	whereClauses := []string{"\"id\" = ?"}
	whereArgs := []any{o.ID}

	query, args := runtime.BuildDelete(dialect, TagTableName, whereClauses, whereArgs)
	_, err = exec.ExecContext(ctx, query, args...)
	if err != nil {
		return err
	}

	_, err = tagHooks.RunIfEnabled(ctx, runtime.AfterDelete)
	return err
}

// Upsert inserts or updates the Tag based on the primary key.
func (o *Tag) Upsert(ctx context.Context, exec runtime.Executor) error {
	ctx, err := tagHooks.RunIfEnabled(ctx, runtime.BeforeUpsert)
	if err != nil {
		return err
	}
	allCols := []string{"id", "name"}
	allVals := []any{o.ID, o.Name}
	conflictCols := []string{"id"}
	updateCols := []string{"name"}
	returning := []string{"id", "name"}

	query, args := runtime.BuildUpsert(dialect, TagTableName, allCols, allVals, conflictCols, updateCols, returning)

	err = exec.QueryRowContext(ctx, query, args...).Scan(
		&o.ID,
		&o.Name,
	)
	if err != nil {
		return err
	}

	_, err = tagHooks.RunIfEnabled(ctx, runtime.AfterUpsert)
	return err
}

// Exists checks if a row with the given primary key exists.
func TagExists(ctx context.Context, exec runtime.Executor, id int32) (bool, error) {
	return runtime.Exists(ctx, exec, dialect, TagTableName,
		runtime.Where("\"id\" = ?", id),
	)
}

// CountTags returns the count of rows matching the query mods.
func CountTags(ctx context.Context, exec runtime.Executor, mods ...runtime.QueryMod) (int64, error) {
	return runtime.Count(ctx, exec, dialect, TagTableName, mods...)
}
