// Code generated by sqlgen. DO NOT EDIT.

package models

import (
	"time"

	"github.com/davidbyttow/sqlgen/runtime"
)

// UserTableName is the database table name.
const UserTableName = "users"

// UserColumns contains all column names for the users table.
var UserColumns = struct {
	ID        string
	Email     string
	Name      string
	Bio       string
	CreatedAt string
}{
	ID:        "id",
	Email:     "email",
	Name:      "name",
	Bio:       "bio",
	CreatedAt: "created_at",
}

// User represents a row from the 'users' table.
type User struct {
	ID        string               `json:"id" db:"id"`
	Email     string               `json:"email" db:"email"`
	Name      string               `json:"name" db:"name"`
	Bio       runtime.Null[string] `json:"bio" db:"bio"`
	CreatedAt time.Time            `json:"created_at" db:"created_at"`

	R *UserRels `json:"-" db:"-"`
}

// UserRels holds eagerly loaded relationships.
type UserRels struct {
	Posts []*Post
}

// UserSlice is a slice of User pointers.
type UserSlice []*User

// ScanRow scans a database row into a User.
func (o *User) ScanRow(rows interface{ Scan(...any) error }) error {
	return rows.Scan(
		&o.ID,
		&o.Email,
		&o.Name,
		&o.Bio,
		&o.CreatedAt,
	)
}

// scanDests returns scan destinations for all columns (used by preload-aware queries).
func (o *User) scanDests() []any {
	return []any{
		&o.ID,
		&o.Email,
		&o.Name,
		&o.Bio,
		&o.CreatedAt,
	}
}
