// Code generated by sqlgen. DO NOT EDIT.

package models

import "github.com/davidbyttow/sqlgen"

// PostTagWhere provides type-safe where clause builders for each column.
var PostTagWhere = struct {
	PostID PostTagPostIDFilter
	TagID  PostTagTagIDFilter
}{
	PostID: PostTagPostIDFilter{col: "post_id"},
	TagID:  PostTagTagIDFilter{col: "tag_id"},
}

// PostTagPostIDFilter provides where clauses for the post_id column.
type PostTagPostIDFilter struct {
	col string
}

func (f PostTagPostIDFilter) EQ(val string) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" = ?", val)
}

func (f PostTagPostIDFilter) NEQ(val string) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" != ?", val)
}

func (f PostTagPostIDFilter) LT(val string) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" < ?", val)
}

func (f PostTagPostIDFilter) LTE(val string) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" <= ?", val)
}

func (f PostTagPostIDFilter) GT(val string) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" > ?", val)
}

func (f PostTagPostIDFilter) GTE(val string) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" >= ?", val)
}

func (f PostTagPostIDFilter) IN(vals ...string) sqlgen.QueryMod {
	args := make([]any, len(vals))
	for i, v := range vals {
		args[i] = v
	}
	placeholders := make([]byte, 0, len(vals)*2)
	for i := range vals {
		if i > 0 {
			placeholders = append(placeholders, ',', ' ')
		}
		placeholders = append(placeholders, '?')
	}
	return sqlgen.Where("\""+f.col+"\" IN ("+string(placeholders)+")", args...)
}

// PostTagTagIDFilter provides where clauses for the tag_id column.
type PostTagTagIDFilter struct {
	col string
}

func (f PostTagTagIDFilter) EQ(val int32) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" = ?", val)
}

func (f PostTagTagIDFilter) NEQ(val int32) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" != ?", val)
}

func (f PostTagTagIDFilter) LT(val int32) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" < ?", val)
}

func (f PostTagTagIDFilter) LTE(val int32) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" <= ?", val)
}

func (f PostTagTagIDFilter) GT(val int32) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" > ?", val)
}

func (f PostTagTagIDFilter) GTE(val int32) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" >= ?", val)
}

func (f PostTagTagIDFilter) IN(vals ...int32) sqlgen.QueryMod {
	args := make([]any, len(vals))
	for i, v := range vals {
		args[i] = v
	}
	placeholders := make([]byte, 0, len(vals)*2)
	for i := range vals {
		if i > 0 {
			placeholders = append(placeholders, ',', ' ')
		}
		placeholders = append(placeholders, '?')
	}
	return sqlgen.Where("\""+f.col+"\" IN ("+string(placeholders)+")", args...)
}
