// Code generated by sqlgen. DO NOT EDIT.

package models

import (
	"time"

	"github.com/davidbyttow/sqlgen/runtime"
)

// PostWhere provides type-safe where clause builders for each column.
var PostWhere = struct {
	ID          PostIDFilter
	AuthorID    PostAuthorIDFilter
	Title       PostTitleFilter
	Body        PostBodyFilter
	Status      PostStatusFilter
	CreatedAt   PostCreatedAtFilter
	PublishedAt PostPublishedAtFilter
}{
	ID:          PostIDFilter{col: "id"},
	AuthorID:    PostAuthorIDFilter{col: "author_id"},
	Title:       PostTitleFilter{col: "title"},
	Body:        PostBodyFilter{col: "body"},
	Status:      PostStatusFilter{col: "status"},
	CreatedAt:   PostCreatedAtFilter{col: "created_at"},
	PublishedAt: PostPublishedAtFilter{col: "published_at"},
}

// PostIDFilter provides where clauses for the id column.
type PostIDFilter struct {
	col string
}

func (f PostIDFilter) EQ(val string) runtime.QueryMod {
	return runtime.Where("\""+f.col+"\" = ?", val)
}

func (f PostIDFilter) NEQ(val string) runtime.QueryMod {
	return runtime.Where("\""+f.col+"\" != ?", val)
}

func (f PostIDFilter) LT(val string) runtime.QueryMod {
	return runtime.Where("\""+f.col+"\" < ?", val)
}

func (f PostIDFilter) LTE(val string) runtime.QueryMod {
	return runtime.Where("\""+f.col+"\" <= ?", val)
}

func (f PostIDFilter) GT(val string) runtime.QueryMod {
	return runtime.Where("\""+f.col+"\" > ?", val)
}

func (f PostIDFilter) GTE(val string) runtime.QueryMod {
	return runtime.Where("\""+f.col+"\" >= ?", val)
}

func (f PostIDFilter) IN(vals ...string) runtime.QueryMod {
	args := make([]any, len(vals))
	for i, v := range vals {
		args[i] = v
	}
	placeholders := make([]byte, 0, len(vals)*2)
	for i := range vals {
		if i > 0 {
			placeholders = append(placeholders, ',', ' ')
		}
		placeholders = append(placeholders, '?')
	}
	return runtime.Where("\""+f.col+"\" IN ("+string(placeholders)+")", args...)
}

// PostAuthorIDFilter provides where clauses for the author_id column.
type PostAuthorIDFilter struct {
	col string
}

func (f PostAuthorIDFilter) EQ(val string) runtime.QueryMod {
	return runtime.Where("\""+f.col+"\" = ?", val)
}

func (f PostAuthorIDFilter) NEQ(val string) runtime.QueryMod {
	return runtime.Where("\""+f.col+"\" != ?", val)
}

func (f PostAuthorIDFilter) LT(val string) runtime.QueryMod {
	return runtime.Where("\""+f.col+"\" < ?", val)
}

func (f PostAuthorIDFilter) LTE(val string) runtime.QueryMod {
	return runtime.Where("\""+f.col+"\" <= ?", val)
}

func (f PostAuthorIDFilter) GT(val string) runtime.QueryMod {
	return runtime.Where("\""+f.col+"\" > ?", val)
}

func (f PostAuthorIDFilter) GTE(val string) runtime.QueryMod {
	return runtime.Where("\""+f.col+"\" >= ?", val)
}

func (f PostAuthorIDFilter) IN(vals ...string) runtime.QueryMod {
	args := make([]any, len(vals))
	for i, v := range vals {
		args[i] = v
	}
	placeholders := make([]byte, 0, len(vals)*2)
	for i := range vals {
		if i > 0 {
			placeholders = append(placeholders, ',', ' ')
		}
		placeholders = append(placeholders, '?')
	}
	return runtime.Where("\""+f.col+"\" IN ("+string(placeholders)+")", args...)
}

// PostTitleFilter provides where clauses for the title column.
type PostTitleFilter struct {
	col string
}

func (f PostTitleFilter) EQ(val string) runtime.QueryMod {
	return runtime.Where("\""+f.col+"\" = ?", val)
}

func (f PostTitleFilter) NEQ(val string) runtime.QueryMod {
	return runtime.Where("\""+f.col+"\" != ?", val)
}

func (f PostTitleFilter) LT(val string) runtime.QueryMod {
	return runtime.Where("\""+f.col+"\" < ?", val)
}

func (f PostTitleFilter) LTE(val string) runtime.QueryMod {
	return runtime.Where("\""+f.col+"\" <= ?", val)
}

func (f PostTitleFilter) GT(val string) runtime.QueryMod {
	return runtime.Where("\""+f.col+"\" > ?", val)
}

func (f PostTitleFilter) GTE(val string) runtime.QueryMod {
	return runtime.Where("\""+f.col+"\" >= ?", val)
}

func (f PostTitleFilter) IN(vals ...string) runtime.QueryMod {
	args := make([]any, len(vals))
	for i, v := range vals {
		args[i] = v
	}
	placeholders := make([]byte, 0, len(vals)*2)
	for i := range vals {
		if i > 0 {
			placeholders = append(placeholders, ',', ' ')
		}
		placeholders = append(placeholders, '?')
	}
	return runtime.Where("\""+f.col+"\" IN ("+string(placeholders)+")", args...)
}

// PostBodyFilter provides where clauses for the body column.
type PostBodyFilter struct {
	col string
}

func (f PostBodyFilter) EQ(val string) runtime.QueryMod {
	return runtime.Where("\""+f.col+"\" = ?", val)
}

func (f PostBodyFilter) NEQ(val string) runtime.QueryMod {
	return runtime.Where("\""+f.col+"\" != ?", val)
}

func (f PostBodyFilter) LT(val string) runtime.QueryMod {
	return runtime.Where("\""+f.col+"\" < ?", val)
}

func (f PostBodyFilter) LTE(val string) runtime.QueryMod {
	return runtime.Where("\""+f.col+"\" <= ?", val)
}

func (f PostBodyFilter) GT(val string) runtime.QueryMod {
	return runtime.Where("\""+f.col+"\" > ?", val)
}

func (f PostBodyFilter) GTE(val string) runtime.QueryMod {
	return runtime.Where("\""+f.col+"\" >= ?", val)
}

func (f PostBodyFilter) IN(vals ...string) runtime.QueryMod {
	args := make([]any, len(vals))
	for i, v := range vals {
		args[i] = v
	}
	placeholders := make([]byte, 0, len(vals)*2)
	for i := range vals {
		if i > 0 {
			placeholders = append(placeholders, ',', ' ')
		}
		placeholders = append(placeholders, '?')
	}
	return runtime.Where("\""+f.col+"\" IN ("+string(placeholders)+")", args...)
}

// PostStatusFilter provides where clauses for the status column.
type PostStatusFilter struct {
	col string
}

func (f PostStatusFilter) EQ(val PostStatus) runtime.QueryMod {
	return runtime.Where("\""+f.col+"\" = ?", val)
}

func (f PostStatusFilter) NEQ(val PostStatus) runtime.QueryMod {
	return runtime.Where("\""+f.col+"\" != ?", val)
}

func (f PostStatusFilter) LT(val PostStatus) runtime.QueryMod {
	return runtime.Where("\""+f.col+"\" < ?", val)
}

func (f PostStatusFilter) LTE(val PostStatus) runtime.QueryMod {
	return runtime.Where("\""+f.col+"\" <= ?", val)
}

func (f PostStatusFilter) GT(val PostStatus) runtime.QueryMod {
	return runtime.Where("\""+f.col+"\" > ?", val)
}

func (f PostStatusFilter) GTE(val PostStatus) runtime.QueryMod {
	return runtime.Where("\""+f.col+"\" >= ?", val)
}

func (f PostStatusFilter) IN(vals ...PostStatus) runtime.QueryMod {
	args := make([]any, len(vals))
	for i, v := range vals {
		args[i] = v
	}
	placeholders := make([]byte, 0, len(vals)*2)
	for i := range vals {
		if i > 0 {
			placeholders = append(placeholders, ',', ' ')
		}
		placeholders = append(placeholders, '?')
	}
	return runtime.Where("\""+f.col+"\" IN ("+string(placeholders)+")", args...)
}

// PostCreatedAtFilter provides where clauses for the created_at column.
type PostCreatedAtFilter struct {
	col string
}

func (f PostCreatedAtFilter) EQ(val time.Time) runtime.QueryMod {
	return runtime.Where("\""+f.col+"\" = ?", val)
}

func (f PostCreatedAtFilter) NEQ(val time.Time) runtime.QueryMod {
	return runtime.Where("\""+f.col+"\" != ?", val)
}

func (f PostCreatedAtFilter) LT(val time.Time) runtime.QueryMod {
	return runtime.Where("\""+f.col+"\" < ?", val)
}

func (f PostCreatedAtFilter) LTE(val time.Time) runtime.QueryMod {
	return runtime.Where("\""+f.col+"\" <= ?", val)
}

func (f PostCreatedAtFilter) GT(val time.Time) runtime.QueryMod {
	return runtime.Where("\""+f.col+"\" > ?", val)
}

func (f PostCreatedAtFilter) GTE(val time.Time) runtime.QueryMod {
	return runtime.Where("\""+f.col+"\" >= ?", val)
}

func (f PostCreatedAtFilter) IN(vals ...time.Time) runtime.QueryMod {
	args := make([]any, len(vals))
	for i, v := range vals {
		args[i] = v
	}
	placeholders := make([]byte, 0, len(vals)*2)
	for i := range vals {
		if i > 0 {
			placeholders = append(placeholders, ',', ' ')
		}
		placeholders = append(placeholders, '?')
	}
	return runtime.Where("\""+f.col+"\" IN ("+string(placeholders)+")", args...)
}

// PostPublishedAtFilter provides where clauses for the published_at column.
type PostPublishedAtFilter struct {
	col string
}

func (f PostPublishedAtFilter) EQ(val runtime.Null[time.Time]) runtime.QueryMod {
	return runtime.Where("\""+f.col+"\" = ?", val)
}

func (f PostPublishedAtFilter) NEQ(val runtime.Null[time.Time]) runtime.QueryMod {
	return runtime.Where("\""+f.col+"\" != ?", val)
}

func (f PostPublishedAtFilter) LT(val runtime.Null[time.Time]) runtime.QueryMod {
	return runtime.Where("\""+f.col+"\" < ?", val)
}

func (f PostPublishedAtFilter) LTE(val runtime.Null[time.Time]) runtime.QueryMod {
	return runtime.Where("\""+f.col+"\" <= ?", val)
}

func (f PostPublishedAtFilter) GT(val runtime.Null[time.Time]) runtime.QueryMod {
	return runtime.Where("\""+f.col+"\" > ?", val)
}

func (f PostPublishedAtFilter) GTE(val runtime.Null[time.Time]) runtime.QueryMod {
	return runtime.Where("\""+f.col+"\" >= ?", val)
}

func (f PostPublishedAtFilter) IN(vals ...runtime.Null[time.Time]) runtime.QueryMod {
	args := make([]any, len(vals))
	for i, v := range vals {
		args[i] = v
	}
	placeholders := make([]byte, 0, len(vals)*2)
	for i := range vals {
		if i > 0 {
			placeholders = append(placeholders, ',', ' ')
		}
		placeholders = append(placeholders, '?')
	}
	return runtime.Where("\""+f.col+"\" IN ("+string(placeholders)+")", args...)
}

func (f PostPublishedAtFilter) IsNull() runtime.QueryMod {
	return runtime.Where("\"" + f.col + "\" IS NULL")
}

func (f PostPublishedAtFilter) IsNotNull() runtime.QueryMod {
	return runtime.Where("\"" + f.col + "\" IS NOT NULL")
}
