// Code generated by sqlgen. DO NOT EDIT.

package models

import (
	"context"

	"github.com/davidbyttow/sqlgen"
)

// PostTags returns a query builder for the post_tags table.
func PostTags(mods ...sqlgen.QueryMod) *sqlgen.Query {
	return sqlgen.NewQuery(dialect, PostTagTableName, mods...)
}

// FindPostTagByPK finds a PostTag by primary key.
func FindPostTagByPK(ctx context.Context, exec sqlgen.Executor, postID string, tagID int32) (*PostTag, error) {
	q := sqlgen.NewQuery(dialect, PostTagTableName,
		sqlgen.Where("\"post_id\" = ?", postID),
		sqlgen.Where("\"tag_id\" = ?", tagID),
		sqlgen.Limit(1),
	)

	query, args := q.BuildSelect()
	row := exec.QueryRowContext(ctx, query, args...)

	o := &PostTag{}
	if err := o.ScanRow(row); err != nil {
		return nil, err
	}
	return o, nil
}

// AllPostTags retrieves all rows from the post_tags table with the given query mods.
// Supports Preload() for LEFT JOIN eager loading of to-one relationships.
func AllPostTags(ctx context.Context, exec sqlgen.Executor, mods ...sqlgen.QueryMod) (PostTagSlice, error) {
	q := sqlgen.NewQuery(dialect, PostTagTableName, mods...)
	query, args := q.BuildSelect()
	rows, err := exec.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var result PostTagSlice
	for rows.Next() {
		o := &PostTag{}
		if err := o.ScanRow(rows); err != nil {
			return nil, err
		}
		result = append(result, o)
	}
	return result, rows.Err()
}

// Insert inserts the PostTag into the database.
// Optional Columns parameter controls which columns are included (Whitelist/Blacklist).
func (o *PostTag) Insert(ctx context.Context, exec sqlgen.Executor, cols ...sqlgen.Columns) error {
	ctx, err := posttagHooks.RunIfEnabled(ctx, exec, sqlgen.BeforeInsert, o)
	if err != nil {
		return err
	}
	allCols := []string{"post_id", "tag_id"}
	allVals := []any{o.PostID, o.TagID}
	allCols, allVals = sqlgen.FilterColumns(allCols, allVals, cols...)

	returning := []string{"post_id", "tag_id"}

	query, args := sqlgen.BuildInsert(dialect, PostTagTableName, allCols, allVals, returning)
	err = exec.QueryRowContext(ctx, query, args...).Scan(
		&o.PostID,
		&o.TagID,
	)
	if err != nil {
		return err
	}
	_, err = posttagHooks.RunIfEnabled(ctx, exec, sqlgen.AfterInsert, o)
	return err
}

// Update updates the PostTag in the database. Only non-PK columns are updated.
// Optional Columns parameter controls which columns are included (Whitelist/Blacklist).
func (o *PostTag) Update(ctx context.Context, exec sqlgen.Executor, cols ...sqlgen.Columns) error {
	ctx, err := posttagHooks.RunIfEnabled(ctx, exec, sqlgen.BeforeUpdate, o)
	if err != nil {
		return err
	}
	setCols := []string{}
	setVals := []any{}
	setCols, setVals = sqlgen.FilterColumns(setCols, setVals, cols...)

	whereClauses := []string{"\"post_id\" = ?", "\"tag_id\" = ?"}
	whereArgs := []any{o.PostID, o.TagID}

	query, args := sqlgen.BuildUpdate(dialect, PostTagTableName, setCols, setVals, whereClauses, whereArgs)
	_, err = exec.ExecContext(ctx, query, args...)
	if err != nil {
		return err
	}
	_, err = posttagHooks.RunIfEnabled(ctx, exec, sqlgen.AfterUpdate, o)
	return err
}

// Delete deletes the PostTag from the database.
func (o *PostTag) Delete(ctx context.Context, exec sqlgen.Executor) error {
	ctx, err := posttagHooks.RunIfEnabled(ctx, exec, sqlgen.BeforeDelete, o)
	if err != nil {
		return err
	}

	whereClauses := []string{"\"post_id\" = ?", "\"tag_id\" = ?"}
	whereArgs := []any{o.PostID, o.TagID}

	query, args := sqlgen.BuildDelete(dialect, PostTagTableName, whereClauses, whereArgs)
	_, err = exec.ExecContext(ctx, query, args...)
	if err != nil {
		return err
	}
	_, err = posttagHooks.RunIfEnabled(ctx, exec, sqlgen.AfterDelete, o)
	return err
}

// Upsert inserts or updates the PostTag based on the primary key.
// Optional Columns parameter controls which non-PK columns are included (Whitelist/Blacklist).
func (o *PostTag) Upsert(ctx context.Context, exec sqlgen.Executor, cols ...sqlgen.Columns) error {
	ctx, err := posttagHooks.RunIfEnabled(ctx, exec, sqlgen.BeforeUpsert, o)
	if err != nil {
		return err
	}
	allCols := []string{"post_id", "tag_id"}
	allVals := []any{o.PostID, o.TagID}
	allCols, allVals = sqlgen.FilterColumns(allCols, allVals, cols...)
	conflictCols := []string{"post_id", "tag_id"}
	updateCols := []string{}
	updateCols, _ = sqlgen.FilterColumns(updateCols, make([]any, len(updateCols)), cols...)
	returning := []string{"post_id", "tag_id"}

	query, args := sqlgen.BuildUpsert(dialect, PostTagTableName, allCols, allVals, conflictCols, updateCols, returning)
	err = exec.QueryRowContext(ctx, query, args...).Scan(
		&o.PostID,
		&o.TagID,
	)
	if err != nil {
		return err
	}
	_, err = posttagHooks.RunIfEnabled(ctx, exec, sqlgen.AfterUpsert, o)
	return err
}

// Exists checks if a row with the given primary key exists.
func PostTagExists(ctx context.Context, exec sqlgen.Executor, postID string, tagID int32) (bool, error) {
	return sqlgen.Exists(ctx, exec, dialect, PostTagTableName,
		sqlgen.Where("\"post_id\" = ?", postID),
		sqlgen.Where("\"tag_id\" = ?", tagID),
	)
}

// CountPostTags returns the count of rows matching the query mods.
func CountPostTags(ctx context.Context, exec sqlgen.Executor, mods ...sqlgen.QueryMod) (int64, error) {
	return sqlgen.Count(ctx, exec, dialect, PostTagTableName, mods...)
}

// UpdateAllPostTags updates all rows matching the given mods.
// set is a map of column name -> new value.
func UpdateAllPostTags(ctx context.Context, exec sqlgen.Executor, set map[string]any, mods ...sqlgen.QueryMod) (int64, error) {
	q := sqlgen.NewQuery(dialect, PostTagTableName, mods...)
	query, args := q.BuildUpdateAll(set)
	result, err := exec.ExecContext(ctx, query, args...)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

// DeleteAllPostTags deletes all rows matching the given mods.
func DeleteAllPostTags(ctx context.Context, exec sqlgen.Executor, mods ...sqlgen.QueryMod) (int64, error) {
	q := sqlgen.NewQuery(dialect, PostTagTableName, mods...)
	query, args := q.BuildDeleteAll()
	result, err := exec.ExecContext(ctx, query, args...)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

// Reload refreshes the PostTag from the database using its primary key.
func (o *PostTag) Reload(ctx context.Context, exec sqlgen.Executor) error {
	q := sqlgen.NewQuery(dialect, PostTagTableName,
		sqlgen.Where("\"post_id\" = ?", o.PostID),
		sqlgen.Where("\"tag_id\" = ?", o.TagID),
		sqlgen.Limit(1),
	)
	query, args := q.BuildSelect()
	return o.ScanRow(exec.QueryRowContext(ctx, query, args...))
}
