// Code generated by sqlgen. DO NOT EDIT.

package models

import "github.com/davidbyttow/sqlgen/runtime"

// postHooks stores the hooks for Post.
var postHooks = runtime.NewHooks()

// AddPostHook registers a hook for the given hook point.
func AddPostHook(point runtime.HookPoint, fn runtime.Hook) {
	postHooks.Add(point, fn)
}
