// Code generated by sqlgen. DO NOT EDIT.

package models

import (
	"context"
	"fmt"

	"github.com/davidbyttow/sqlgen/runtime"
)

// userLoaders maps relationship names to their loader functions.
var userLoaders = map[string]runtime.LoadFunc{}

func init() {
	userLoaders["Posts"] = loadUserPosts
}

// LoadRelations eagerly loads the specified relationships for a slice of User.
func (s UserSlice) LoadRelations(ctx context.Context, exec runtime.Executor, loads ...*runtime.EagerLoadRequest) error {
	for _, load := range loads {
		fn, ok := userLoaders[load.Name]
		if !ok {
			return fmt.Errorf("unknown relationship %q on User", load.Name)
		}
		if err := fn(ctx, exec, dialect, s, loads); err != nil {
			return fmt.Errorf("loading %s: %w", load.Name, err)
		}
	}
	return nil
}

func loadUserPosts(ctx context.Context, exec runtime.Executor, d runtime.Dialect, parentModels any, loads []*runtime.EagerLoadRequest) error {
	models := parentModels.(UserSlice)
	if len(models) == 0 {
		return nil
	}

	// Collect parent PK values.
	ids := make([]any, len(models))
	idMap := make(map[string][]*User)
	for i, m := range models {
		ids[i] = m.ID
		key := fmt.Sprint(m.ID)
		idMap[key] = append(idMap[key], m)
	}

	rows, err := runtime.LoadMany(ctx, exec, d, PostTableName, "author_id", ids)
	if err != nil {
		return err
	}
	if rows == nil {
		return nil
	}
	defer rows.Close()

	for rows.Next() {
		o := &Post{}
		if err := o.ScanRow(rows); err != nil {
			return err
		}
		key := fmt.Sprint(o.AuthorID)
		for _, parent := range idMap[key] {
			if parent.R == nil {
				parent.R = &UserRels{}
			}
			parent.R.Posts = append(parent.R.Posts, o)
		}
	}
	if err := rows.Err(); err != nil {
		return err
	}

	// Handle nested loads.
	for _, l := range loads {
		if l.Name == "Posts" && len(l.Nested) > 0 {
			var all PostSlice
			for _, m := range models {
				if m.R != nil {
					all = append(all, m.R.Posts...)
				}
			}
			if err := all.LoadRelations(ctx, exec, l.Nested...); err != nil {
				return err
			}
		}
	}
	return nil
}
