// Code generated by sqlgen. DO NOT EDIT.

package models

import (
	"context"

	"github.com/davidbyttow/sqlgen"
)

// tagHooks stores the hooks for Tag.
var tagHooks = sqlgen.NewHooks()

// TagHook is a typed hook function for Tag lifecycle events.
type TagHook func(ctx context.Context, exec sqlgen.Executor, model *Tag) (context.Context, error)

// AddTagHook registers a typed hook for the given hook point.
// The hook receives the model pointer and can inspect or modify it.
func AddTagHook(point sqlgen.HookPoint, fn TagHook) {
	tagHooks.Add(point, func(ctx context.Context, exec sqlgen.Executor, model any) (context.Context, error) {
		return fn(ctx, exec, model.(*Tag))
	})
}
