// Code generated by sqlgen. DO NOT EDIT.

package models

import (
	"context"

	"github.com/davidbyttow/sqlgen/runtime"
)

// Users returns a query builder for the users table.
func Users(mods ...runtime.QueryMod) *runtime.Query {
	return runtime.NewQuery(dialect, UserTableName, mods...)
}

// FindUserByPK finds a User by primary key.
func FindUserByPK(ctx context.Context, exec runtime.Executor, id string) (*User, error) {
	q := runtime.NewQuery(dialect, UserTableName,
		runtime.Where("\"id\" = ?", id),
		runtime.Limit(1),
	)

	query, args := q.BuildSelect()
	row := exec.QueryRowContext(ctx, query, args...)

	o := &User{}
	if err := o.ScanRow(row); err != nil {
		return nil, err
	}
	return o, nil
}

// AllUsers retrieves all rows from the users table with the given query mods.
func AllUsers(ctx context.Context, exec runtime.Executor, mods ...runtime.QueryMod) (UserSlice, error) {
	q := runtime.NewQuery(dialect, UserTableName, mods...)
	query, args := q.BuildSelect()
	rows, err := exec.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var result UserSlice
	for rows.Next() {
		o := &User{}
		if err := o.ScanRow(rows); err != nil {
			return nil, err
		}
		result = append(result, o)
	}
	return result, rows.Err()
}

// Insert inserts the User into the database.
func (o *User) Insert(ctx context.Context, exec runtime.Executor) error {
	ctx, err := userHooks.RunIfEnabled(ctx, runtime.BeforeInsert)
	if err != nil {
		return err
	}
	allCols := []string{"id", "email", "name", "bio", "created_at"}
	allVals := []any{o.ID, o.Email, o.Name, o.Bio, o.CreatedAt}

	returning := []string{"id", "email", "name", "bio", "created_at"}

	query, args := runtime.BuildInsert(dialect, UserTableName, allCols, allVals, returning)

	err = exec.QueryRowContext(ctx, query, args...).Scan(
		&o.ID,
		&o.Email,
		&o.Name,
		&o.Bio,
		&o.CreatedAt,
	)
	if err != nil {
		return err
	}

	_, err = userHooks.RunIfEnabled(ctx, runtime.AfterInsert)
	return err
}

// Update updates the User in the database. Only non-PK columns are updated.
func (o *User) Update(ctx context.Context, exec runtime.Executor) error {
	ctx, err := userHooks.RunIfEnabled(ctx, runtime.BeforeUpdate)
	if err != nil {
		return err
	}
	setCols := []string{"email", "name", "bio", "created_at"}
	setVals := []any{o.Email, o.Name, o.Bio, o.CreatedAt}

	whereClauses := []string{"\"id\" = ?"}
	whereArgs := []any{o.ID}

	query, args := runtime.BuildUpdate(dialect, UserTableName, setCols, setVals, whereClauses, whereArgs)
	_, err = exec.ExecContext(ctx, query, args...)
	if err != nil {
		return err
	}

	_, err = userHooks.RunIfEnabled(ctx, runtime.AfterUpdate)
	return err
}

// Delete deletes the User from the database.
func (o *User) Delete(ctx context.Context, exec runtime.Executor) error {
	ctx, err := userHooks.RunIfEnabled(ctx, runtime.BeforeDelete)
	if err != nil {
		return err
	}

	whereClauses := []string{"\"id\" = ?"}
	whereArgs := []any{o.ID}

	query, args := runtime.BuildDelete(dialect, UserTableName, whereClauses, whereArgs)
	_, err = exec.ExecContext(ctx, query, args...)
	if err != nil {
		return err
	}

	_, err = userHooks.RunIfEnabled(ctx, runtime.AfterDelete)
	return err
}

// Upsert inserts or updates the User based on the primary key.
func (o *User) Upsert(ctx context.Context, exec runtime.Executor) error {
	ctx, err := userHooks.RunIfEnabled(ctx, runtime.BeforeUpsert)
	if err != nil {
		return err
	}
	allCols := []string{"id", "email", "name", "bio", "created_at"}
	allVals := []any{o.ID, o.Email, o.Name, o.Bio, o.CreatedAt}
	conflictCols := []string{"id"}
	updateCols := []string{"email", "name", "bio", "created_at"}
	returning := []string{"id", "email", "name", "bio", "created_at"}

	query, args := runtime.BuildUpsert(dialect, UserTableName, allCols, allVals, conflictCols, updateCols, returning)

	err = exec.QueryRowContext(ctx, query, args...).Scan(
		&o.ID,
		&o.Email,
		&o.Name,
		&o.Bio,
		&o.CreatedAt,
	)
	if err != nil {
		return err
	}

	_, err = userHooks.RunIfEnabled(ctx, runtime.AfterUpsert)
	return err
}

// Exists checks if a row with the given primary key exists.
func UserExists(ctx context.Context, exec runtime.Executor, id string) (bool, error) {
	return runtime.Exists(ctx, exec, dialect, UserTableName,
		runtime.Where("\"id\" = ?", id),
	)
}

// CountUsers returns the count of rows matching the query mods.
func CountUsers(ctx context.Context, exec runtime.Executor, mods ...runtime.QueryMod) (int64, error) {
	return runtime.Count(ctx, exec, dialect, UserTableName, mods...)
}
