// Code generated by sqlgen. DO NOT EDIT.

package models

import (
	"context"

	"github.com/davidbyttow/sqlgen"
)

// commentHooks stores the hooks for Comment.
var commentHooks = sqlgen.NewHooks()

// CommentHook is a typed hook function for Comment lifecycle events.
type CommentHook func(ctx context.Context, exec sqlgen.Executor, model *Comment) (context.Context, error)

// AddCommentHook registers a typed hook for the given hook point.
// The hook receives the model pointer and can inspect or modify it.
func AddCommentHook(point sqlgen.HookPoint, fn CommentHook) {
	commentHooks.Add(point, func(ctx context.Context, exec sqlgen.Executor, model any) (context.Context, error) {
		return fn(ctx, exec, model.(*Comment))
	})
}
