// Code generated by sqlgen. DO NOT EDIT.

package models

import (
	"context"
	"fmt"

	"github.com/davidbyttow/sqlgen"
)

// SetUser sets the User relationship by updating the FK column.
func (o *Post) SetUser(ctx context.Context, exec sqlgen.Executor, related *User) error {
	o.AuthorID = related.ID
	query := "UPDATE " + dialect.QuoteIdent(PostTableName) +
		" SET " + dialect.QuoteIdent("author_id") + " = " + dialect.Placeholder(1) +
		" WHERE " + dialect.QuoteIdent("id") + " = " + dialect.Placeholder(2)
	_, err := exec.ExecContext(ctx, query, o.AuthorID, o.ID)
	if err != nil {
		return err
	}
	if o.R == nil {
		o.R = &PostRels{}
	}
	o.R.User = related
	return nil
}

// SetCategory sets the Category relationship by updating the FK column.
func (o *Post) SetCategory(ctx context.Context, exec sqlgen.Executor, related *Category) error {
	o.CategoryID = sqlgen.NewNull(related.ID)
	query := "UPDATE " + dialect.QuoteIdent(PostTableName) +
		" SET " + dialect.QuoteIdent("category_id") + " = " + dialect.Placeholder(1) +
		" WHERE " + dialect.QuoteIdent("id") + " = " + dialect.Placeholder(2)
	_, err := exec.ExecContext(ctx, query, o.CategoryID, o.ID)
	if err != nil {
		return err
	}
	if o.R == nil {
		o.R = &PostRels{}
	}
	o.R.Category = related
	return nil
}

// RemoveCategory clears the Category relationship by setting the FK to NULL.
func (o *Post) RemoveCategory(ctx context.Context, exec sqlgen.Executor) error {
	query := "UPDATE " + dialect.QuoteIdent(PostTableName) +
		" SET " + dialect.QuoteIdent("category_id") + " = NULL" +
		" WHERE " + dialect.QuoteIdent("id") + " = " + dialect.Placeholder(1)
	_, err := exec.ExecContext(ctx, query, o.ID)
	if err != nil {
		return err
	}
	if o.R != nil {
		o.R.Category = nil
	}
	return nil
}

// AddTags adds to the Tags relationship by inserting join table rows.
func (o *Post) AddTags(ctx context.Context, exec sqlgen.Executor, related ...*Tag) error {
	for _, r := range related {
		query := "INSERT INTO " + dialect.QuoteIdent("post_tags") +
			" (" + dialect.QuoteIdent("post_id") + ", " + dialect.QuoteIdent("tag_id") + ")" +
			" VALUES (" + dialect.Placeholder(1) + ", " + dialect.Placeholder(2) + ")"
		_, err := exec.ExecContext(ctx, query, o.ID, r.ID)
		if err != nil {
			return err
		}
	}
	if o.R == nil {
		o.R = &PostRels{}
	}
	o.R.Tags = append(o.R.Tags, related...)
	return nil
}

// RemoveTags removes from the Tags relationship by deleting join table rows.
func (o *Post) RemoveTags(ctx context.Context, exec sqlgen.Executor, related ...*Tag) error {
	toRemove := make(map[string]bool)
	for _, r := range related {
		query := "DELETE FROM " + dialect.QuoteIdent("post_tags") +
			" WHERE " + dialect.QuoteIdent("post_id") + " = " + dialect.Placeholder(1) +
			" AND " + dialect.QuoteIdent("tag_id") + " = " + dialect.Placeholder(2)
		_, err := exec.ExecContext(ctx, query, o.ID, r.ID)
		if err != nil {
			return err
		}
		toRemove[fmt.Sprint(r.ID)] = true
	}
	if o.R != nil {
		filtered := make([]*Tag, 0, len(o.R.Tags))
		for _, r := range o.R.Tags {
			if !toRemove[fmt.Sprint(r.ID)] {
				filtered = append(filtered, r)
			}
		}
		o.R.Tags = filtered
	}
	return nil
}

// SetTags replaces the Tags relationship entirely.
// Deletes all existing join rows, then inserts new ones.
func (o *Post) SetTags(ctx context.Context, exec sqlgen.Executor, related ...*Tag) error {
	// Delete all existing associations.
	query := "DELETE FROM " + dialect.QuoteIdent("post_tags") +
		" WHERE " + dialect.QuoteIdent("post_id") + " = " + dialect.Placeholder(1)
	_, err := exec.ExecContext(ctx, query, o.ID)
	if err != nil {
		return err
	}
	if o.R == nil {
		o.R = &PostRels{}
	}
	o.R.Tags = nil

	if len(related) == 0 {
		return nil
	}

	// Insert new associations.
	return o.AddTags(ctx, exec, related...)
}
