// Code generated by sqlgen. DO NOT EDIT.

package models

import (
	"context"
	"fmt"

	"github.com/davidbyttow/sqlgen"
)

// AddPosts adds to the Posts relationship by inserting join table rows.
func (o *Tag) AddPosts(ctx context.Context, exec sqlgen.Executor, related ...*Post) error {
	for _, r := range related {
		query := "INSERT INTO " + dialect.QuoteIdent("post_tags") +
			" (" + dialect.QuoteIdent("tag_id") + ", " + dialect.QuoteIdent("post_id") + ")" +
			" VALUES (" + dialect.Placeholder(1) + ", " + dialect.Placeholder(2) + ")"
		_, err := exec.ExecContext(ctx, query, o.ID, r.ID)
		if err != nil {
			return err
		}
	}
	if o.R == nil {
		o.R = &TagRels{}
	}
	o.R.Posts = append(o.R.Posts, related...)
	return nil
}

// RemovePosts removes from the Posts relationship by deleting join table rows.
func (o *Tag) RemovePosts(ctx context.Context, exec sqlgen.Executor, related ...*Post) error {
	toRemove := make(map[string]bool)
	for _, r := range related {
		query := "DELETE FROM " + dialect.QuoteIdent("post_tags") +
			" WHERE " + dialect.QuoteIdent("tag_id") + " = " + dialect.Placeholder(1) +
			" AND " + dialect.QuoteIdent("post_id") + " = " + dialect.Placeholder(2)
		_, err := exec.ExecContext(ctx, query, o.ID, r.ID)
		if err != nil {
			return err
		}
		toRemove[fmt.Sprint(r.ID)] = true
	}
	if o.R != nil {
		filtered := make([]*Post, 0, len(o.R.Posts))
		for _, r := range o.R.Posts {
			if !toRemove[fmt.Sprint(r.ID)] {
				filtered = append(filtered, r)
			}
		}
		o.R.Posts = filtered
	}
	return nil
}

// SetPosts replaces the Posts relationship entirely.
// Deletes all existing join rows, then inserts new ones.
func (o *Tag) SetPosts(ctx context.Context, exec sqlgen.Executor, related ...*Post) error {
	// Delete all existing associations.
	query := "DELETE FROM " + dialect.QuoteIdent("post_tags") +
		" WHERE " + dialect.QuoteIdent("tag_id") + " = " + dialect.Placeholder(1)
	_, err := exec.ExecContext(ctx, query, o.ID)
	if err != nil {
		return err
	}
	if o.R == nil {
		o.R = &TagRels{}
	}
	o.R.Posts = nil

	if len(related) == 0 {
		return nil
	}

	// Insert new associations.
	return o.AddPosts(ctx, exec, related...)
}
