// Code generated by sqlgen. DO NOT EDIT.

package models

import (
	"encoding/json"
	"time"

	"github.com/davidbyttow/sqlgen"
)

// profileUserPreload holds nullable scan targets for LEFT JOINed User columns.
type profileUserPreload struct {
	id        sqlgen.Null[string]
	email     sqlgen.Null[string]
	name      sqlgen.Null[string]
	bio       sqlgen.Null[string]
	age       sqlgen.Null[int32]
	score     sqlgen.Null[string]
	isAdmin   sqlgen.Null[bool]
	metadata  sqlgen.Null[json.RawMessage]
	createdAt sqlgen.Null[time.Time]
}

func (p *profileUserPreload) scanDests() []any {
	return []any{
		&p.id,
		&p.email,
		&p.name,
		&p.bio,
		&p.age,
		&p.score,
		&p.isAdmin,
		&p.metadata,
		&p.createdAt,
	}
}

func (p *profileUserPreload) assign(o *Profile) {
	if !p.id.Valid {
		return
	}
	if o.R == nil {
		o.R = &ProfileRels{}
	}
	o.R.User = &User{
		ID:        p.id.Val,
		Email:     p.email.Val,
		Name:      p.name.Val,
		Bio:       p.bio,
		Age:       p.age,
		Score:     p.score,
		IsAdmin:   p.isAdmin.Val,
		Metadata:  p.metadata,
		CreatedAt: p.createdAt.Val,
	}
}

// ProfilePreloadUser is the PreloadDef for the User relationship.
var ProfilePreloadUser = sqlgen.PreloadDef{
	Name:     "User",
	Table:    UserTableName,
	JoinCond: "\"users\".\"id\" = \"profiles\".\"user_id\"",
	Columns: []string{
		"\"users\".\"id\"",
		"\"users\".\"email\"",
		"\"users\".\"name\"",
		"\"users\".\"bio\"",
		"\"users\".\"age\"",
		"\"users\".\"score\"",
		"\"users\".\"is_admin\"",
		"\"users\".\"metadata\"",
		"\"users\".\"created_at\"",
	},
}

// profilePreloadState is the interface for preload scan states.
type profilePreloadState interface {
	scanDests() []any
	assign(o *Profile)
}

// newProfilePreloadState returns a preload state for the named relationship.
func newProfilePreloadState(name string) profilePreloadState {
	switch name {
	case "User":
		return &profileUserPreload{}
	}
	return nil
}
