// Code generated by sqlgen. DO NOT EDIT.

package models

import (
	"github.com/davidbyttow/sqlgen"
)

// ProfileTableName is the database table name.
const ProfileTableName = "profiles"

// ProfileColumns contains all column names for the profiles table.
var ProfileColumns = struct {
	ID        string
	UserID    string
	AvatarURL string
	Website   string
}{
	ID:        "id",
	UserID:    "user_id",
	AvatarURL: "avatar_url",
	Website:   "website",
}

// Profile represents a row from the 'profiles' table.
type Profile struct {
	ID        string              `db:"id" json:"id"`
	UserID    string              `db:"user_id" json:"user_id"`
	AvatarURL sqlgen.Null[string] `db:"avatar_url" json:"avatar_url"`
	Website   sqlgen.Null[string] `db:"website" json:"website"`

	R *ProfileRels `db:"-" json:"-"`
}

// ProfileRels holds eagerly loaded relationships.
type ProfileRels struct {
	User *User
}

// ProfileSlice is a slice of Profile pointers.
type ProfileSlice []*Profile

// ScanRow scans a database row into a Profile.
func (o *Profile) ScanRow(rows interface{ Scan(...any) error }) error {
	return rows.Scan(
		&o.ID,
		&o.UserID,
		&o.AvatarURL,
		&o.Website,
	)
}

// scanDests returns scan destinations for all columns (used by preload-aware queries).
func (o *Profile) scanDests() []any {
	return []any{
		&o.ID,
		&o.UserID,
		&o.AvatarURL,
		&o.Website,
	}
}
