// Code generated by sqlgen. DO NOT EDIT.

package models

import (
	"encoding/json"
	"time"

	"github.com/davidbyttow/sqlgen"
)

// commentUserPreload holds nullable scan targets for LEFT JOINed User columns.
type commentUserPreload struct {
	id        sqlgen.Null[string]
	email     sqlgen.Null[string]
	name      sqlgen.Null[string]
	bio       sqlgen.Null[string]
	age       sqlgen.Null[int32]
	score     sqlgen.Null[string]
	isAdmin   sqlgen.Null[bool]
	metadata  sqlgen.Null[json.RawMessage]
	createdAt sqlgen.Null[time.Time]
}

func (p *commentUserPreload) scanDests() []any {
	return []any{
		&p.id,
		&p.email,
		&p.name,
		&p.bio,
		&p.age,
		&p.score,
		&p.isAdmin,
		&p.metadata,
		&p.createdAt,
	}
}

func (p *commentUserPreload) assign(o *Comment) {
	if !p.id.Valid {
		return
	}
	if o.R == nil {
		o.R = &CommentRels{}
	}
	o.R.User = &User{
		ID:        p.id.Val,
		Email:     p.email.Val,
		Name:      p.name.Val,
		Bio:       p.bio,
		Age:       p.age,
		Score:     p.score,
		IsAdmin:   p.isAdmin.Val,
		Metadata:  p.metadata,
		CreatedAt: p.createdAt.Val,
	}
}

// CommentPreloadUser is the PreloadDef for the User relationship.
var CommentPreloadUser = sqlgen.PreloadDef{
	Name:     "User",
	Table:    UserTableName,
	JoinCond: "\"users\".\"id\" = \"comments\".\"author_id\"",
	Columns: []string{
		"\"users\".\"id\"",
		"\"users\".\"email\"",
		"\"users\".\"name\"",
		"\"users\".\"bio\"",
		"\"users\".\"age\"",
		"\"users\".\"score\"",
		"\"users\".\"is_admin\"",
		"\"users\".\"metadata\"",
		"\"users\".\"created_at\"",
	},
}

// commentPreloadState is the interface for preload scan states.
type commentPreloadState interface {
	scanDests() []any
	assign(o *Comment)
}

// newCommentPreloadState returns a preload state for the named relationship.
func newCommentPreloadState(name string) commentPreloadState {
	switch name {
	case "User":
		return &commentUserPreload{}
	}
	return nil
}
