// Code generated by sqlgen. DO NOT EDIT.

package models

// PostTagTableName is the database table name.
const PostTagTableName = "post_tags"

// PostTagColumns contains all column names for the post_tags table.
var PostTagColumns = struct {
	PostID string
	TagID  string
}{
	PostID: "post_id",
	TagID:  "tag_id",
}

// PostTag represents a row from the 'post_tags' table.
type PostTag struct {
	PostID string `db:"post_id" json:"post_id"`
	TagID  int32  `db:"tag_id" json:"tag_id"`

	R *PostTagRels `db:"-" json:"-"`
}

// PostTagRels holds eagerly loaded relationships.
type PostTagRels struct {
}

// PostTagSlice is a slice of PostTag pointers.
type PostTagSlice []*PostTag

// ScanRow scans a database row into a PostTag.
func (o *PostTag) ScanRow(rows interface{ Scan(...any) error }) error {
	return rows.Scan(
		&o.PostID,
		&o.TagID,
	)
}

// scanDests returns scan destinations for all columns (used by preload-aware queries).
func (o *PostTag) scanDests() []any {
	return []any{
		&o.PostID,
		&o.TagID,
	}
}
