// Code generated by sqlgen. DO NOT EDIT.

package models

import (
	"context"

	"github.com/davidbyttow/sqlgen"
	"github.com/davidbyttow/sqlgen/fake"
)

// ProfileMod is a function that customizes a Profile before use.
type ProfileMod func(*Profile)

// NewProfile creates a Profile with random values for all non-auto-increment fields.
// Pass modifier functions to override specific fields.
func NewProfile(mods ...ProfileMod) *Profile {
	o := &Profile{
		ID:        fake.UUID(),
		UserID:    fake.UUID(),
		AvatarURL: sqlgen.NewNull(fake.String("profiles_avatar_url")),
		Website:   sqlgen.NewNull(fake.String("profiles_website")),
	}
	for _, mod := range mods {
		mod(o)
	}
	return o
}

// InsertProfile creates a Profile with random values, applies mods, and inserts it.
func InsertProfile(ctx context.Context, exec sqlgen.Executor, mods ...ProfileMod) (*Profile, error) {
	o := NewProfile(mods...)
	if err := o.Insert(ctx, exec); err != nil {
		return nil, err
	}
	return o, nil
}
