// Code generated by sqlgen. DO NOT EDIT.

package models

import (
	"context"

	"github.com/davidbyttow/sqlgen"
	"github.com/davidbyttow/sqlgen/fake"
)

// CategoryMod is a function that customizes a Category before use.
type CategoryMod func(*Category)

// NewCategory creates a Category with random values for all non-auto-increment fields.
// Pass modifier functions to override specific fields.
func NewCategory(mods ...CategoryMod) *Category {
	o := &Category{
		Name:     fake.String("categories_name"),
		ParentID: sqlgen.NewNull(fake.Int32()),
	}
	for _, mod := range mods {
		mod(o)
	}
	return o
}

// InsertCategory creates a Category with random values, applies mods, and inserts it.
func InsertCategory(ctx context.Context, exec sqlgen.Executor, mods ...CategoryMod) (*Category, error) {
	o := NewCategory(mods...)
	if err := o.Insert(ctx, exec); err != nil {
		return nil, err
	}
	return o, nil
}
