// Code generated by sqlgen. DO NOT EDIT.

package models

import (
	"database/sql/driver"
	"testing"
)

func TestCommentKindValues(t *testing.T) {
	vals := AllCommentKindValues()
	if len(vals) != 3 {
		t.Errorf("AllCommentKindValues() returned %d values, want %d", len(vals), 3)
	}

	// Each value should be valid.
	for _, v := range vals {
		if !v.IsValid() {
			t.Errorf("value %q should be valid", v)
		}
	}
}

func TestCommentKindIsValid(t *testing.T) {
	// Valid values.
	if !CommentKindReview.IsValid() {
		t.Errorf("%q should be valid", CommentKindReview)
	}
	if !CommentKindReply.IsValid() {
		t.Errorf("%q should be valid", CommentKindReply)
	}
	if !CommentKindNote.IsValid() {
		t.Errorf("%q should be valid", CommentKindNote)
	}

	// Invalid value.
	if CommentKind("bogus_value_xyz").IsValid() {
		t.Error("bogus value should not be valid")
	}
}

func TestCommentKindScanValue(t *testing.T) {
	{
		var e CommentKind
		if err := e.Scan("review"); err != nil {
			t.Errorf("Scan(%q): %v", "review", err)
		}
		if e != CommentKindReview {
			t.Errorf("after Scan(%q), got %q", "review", e)
		}
		v, err := e.Value()
		if err != nil {
			t.Errorf("Value() for %q: %v", "review", err)
		}
		if v != driver.Value("review") {
			t.Errorf("Value() = %v, want %q", v, "review")
		}
	}
	{
		var e CommentKind
		if err := e.Scan("reply"); err != nil {
			t.Errorf("Scan(%q): %v", "reply", err)
		}
		if e != CommentKindReply {
			t.Errorf("after Scan(%q), got %q", "reply", e)
		}
		v, err := e.Value()
		if err != nil {
			t.Errorf("Value() for %q: %v", "reply", err)
		}
		if v != driver.Value("reply") {
			t.Errorf("Value() = %v, want %q", v, "reply")
		}
	}
	{
		var e CommentKind
		if err := e.Scan("note"); err != nil {
			t.Errorf("Scan(%q): %v", "note", err)
		}
		if e != CommentKindNote {
			t.Errorf("after Scan(%q), got %q", "note", e)
		}
		v, err := e.Value()
		if err != nil {
			t.Errorf("Value() for %q: %v", "note", err)
		}
		if v != driver.Value("note") {
			t.Errorf("Value() = %v, want %q", v, "note")
		}
	}
}

func TestCommentKindScanBytes(t *testing.T) {
	var e CommentKind
	if err := e.Scan([]byte("review")); err != nil {
		t.Errorf("Scan([]byte): %v", err)
	}
	if e != CommentKindReview {
		t.Errorf("after Scan([]byte), got %q", e)
	}
}

func TestCommentKindScanInvalid(t *testing.T) {
	var e CommentKind
	if err := e.Scan("not_a_real_value_xyz"); err == nil {
		t.Error("expected error scanning invalid value")
	}
	if err := e.Scan(nil); err == nil {
		t.Error("expected error scanning nil")
	}
	if err := e.Scan(123); err == nil {
		t.Error("expected error scanning int")
	}
}

func TestCommentKindString(t *testing.T) {
	if CommentKindReview.String() != "review" {
		t.Errorf("String() = %q, want %q", CommentKindReview.String(), "review")
	}
	if CommentKindReply.String() != "reply" {
		t.Errorf("String() = %q, want %q", CommentKindReply.String(), "reply")
	}
	if CommentKindNote.String() != "note" {
		t.Errorf("String() = %q, want %q", CommentKindNote.String(), "note")
	}
}
