// Code generated by sqlgen. DO NOT EDIT.

package models

import (
	"context"

	"github.com/davidbyttow/sqlgen"
)

// categoryHooks stores the hooks for Category.
var categoryHooks = sqlgen.NewHooks()

// CategoryHook is a typed hook function for Category lifecycle events.
type CategoryHook func(ctx context.Context, exec sqlgen.Executor, model *Category) (context.Context, error)

// AddCategoryHook registers a typed hook for the given hook point.
// The hook receives the model pointer and can inspect or modify it.
func AddCategoryHook(point sqlgen.HookPoint, fn CategoryHook) {
	categoryHooks.Add(point, func(ctx context.Context, exec sqlgen.Executor, model any) (context.Context, error) {
		return fn(ctx, exec, model.(*Category))
	})
}
