// Code generated by sqlgen. DO NOT EDIT.

package models

import (
	"context"

	"github.com/davidbyttow/sqlgen"
)

// Profiles returns a query builder for the profiles table.
func Profiles(mods ...sqlgen.QueryMod) *sqlgen.Query {
	return sqlgen.NewQuery(dialect, ProfileTableName, mods...)
}

// FindProfileByPK finds a Profile by primary key.
func FindProfileByPK(ctx context.Context, exec sqlgen.Executor, id string) (*Profile, error) {
	q := sqlgen.NewQuery(dialect, ProfileTableName,
		sqlgen.Where("\"id\" = ?", id),
		sqlgen.Limit(1),
	)

	query, args := q.BuildSelect()
	row := exec.QueryRowContext(ctx, query, args...)

	o := &Profile{}
	if err := o.ScanRow(row); err != nil {
		return nil, err
	}
	return o, nil
}

// AllProfiles retrieves all rows from the profiles table with the given query mods.
// Supports Preload() for LEFT JOIN eager loading of to-one relationships.
func AllProfiles(ctx context.Context, exec sqlgen.Executor, mods ...sqlgen.QueryMod) (ProfileSlice, error) {
	q := sqlgen.NewQuery(dialect, ProfileTableName, mods...)
	query, args := q.BuildSelect()
	rows, err := exec.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	preloads := q.Preloads()

	var result ProfileSlice
	for rows.Next() {
		o := &Profile{}
		if len(preloads) == 0 {
			if err := o.ScanRow(rows); err != nil {
				return nil, err
			}
		} else {
			dests := o.scanDests()
			var states []profilePreloadState
			for _, p := range preloads {
				ps := newProfilePreloadState(p.Name)
				if ps != nil {
					dests = append(dests, ps.scanDests()...)
					states = append(states, ps)
				}
			}
			if err := rows.Scan(dests...); err != nil {
				return nil, err
			}
			for _, ps := range states {
				ps.assign(o)
			}
		}
		result = append(result, o)
	}
	return result, rows.Err()
}

// Insert inserts the Profile into the database.
// Optional Columns parameter controls which columns are included (Whitelist/Blacklist).
func (o *Profile) Insert(ctx context.Context, exec sqlgen.Executor, cols ...sqlgen.Columns) error {
	ctx, err := profileHooks.RunIfEnabled(ctx, exec, sqlgen.BeforeInsert, o)
	if err != nil {
		return err
	}
	allCols := []string{"user_id", "avatar_url", "website"}
	allVals := []any{o.UserID, o.AvatarURL, o.Website}
	allCols, allVals = sqlgen.FilterColumns(allCols, allVals, cols...)

	returning := []string{"id", "user_id", "avatar_url", "website"}

	query, args := sqlgen.BuildInsert(dialect, ProfileTableName, allCols, allVals, returning)
	err = exec.QueryRowContext(ctx, query, args...).Scan(
		&o.ID,
		&o.UserID,
		&o.AvatarURL,
		&o.Website,
	)
	if err != nil {
		return err
	}
	_, err = profileHooks.RunIfEnabled(ctx, exec, sqlgen.AfterInsert, o)
	return err
}

// Update updates the Profile in the database. Only non-PK columns are updated.
// Optional Columns parameter controls which columns are included (Whitelist/Blacklist).
func (o *Profile) Update(ctx context.Context, exec sqlgen.Executor, cols ...sqlgen.Columns) error {
	ctx, err := profileHooks.RunIfEnabled(ctx, exec, sqlgen.BeforeUpdate, o)
	if err != nil {
		return err
	}
	setCols := []string{"user_id", "avatar_url", "website"}
	setVals := []any{o.UserID, o.AvatarURL, o.Website}
	setCols, setVals = sqlgen.FilterColumns(setCols, setVals, cols...)

	whereClauses := []string{"\"id\" = ?"}
	whereArgs := []any{o.ID}

	query, args := sqlgen.BuildUpdate(dialect, ProfileTableName, setCols, setVals, whereClauses, whereArgs)
	_, err = exec.ExecContext(ctx, query, args...)
	if err != nil {
		return err
	}
	_, err = profileHooks.RunIfEnabled(ctx, exec, sqlgen.AfterUpdate, o)
	return err
}

// Delete deletes the Profile from the database.
func (o *Profile) Delete(ctx context.Context, exec sqlgen.Executor) error {
	ctx, err := profileHooks.RunIfEnabled(ctx, exec, sqlgen.BeforeDelete, o)
	if err != nil {
		return err
	}

	whereClauses := []string{"\"id\" = ?"}
	whereArgs := []any{o.ID}

	query, args := sqlgen.BuildDelete(dialect, ProfileTableName, whereClauses, whereArgs)
	_, err = exec.ExecContext(ctx, query, args...)
	if err != nil {
		return err
	}
	_, err = profileHooks.RunIfEnabled(ctx, exec, sqlgen.AfterDelete, o)
	return err
}

// Upsert inserts or updates the Profile based on the primary key.
// Optional Columns parameter controls which non-PK columns are included (Whitelist/Blacklist).
func (o *Profile) Upsert(ctx context.Context, exec sqlgen.Executor, cols ...sqlgen.Columns) error {
	ctx, err := profileHooks.RunIfEnabled(ctx, exec, sqlgen.BeforeUpsert, o)
	if err != nil {
		return err
	}
	allCols := []string{"id", "user_id", "avatar_url", "website"}
	allVals := []any{o.ID, o.UserID, o.AvatarURL, o.Website}
	allCols, allVals = sqlgen.FilterColumns(allCols, allVals, cols...)
	conflictCols := []string{"id"}
	updateCols := []string{"user_id", "avatar_url", "website"}
	updateCols, _ = sqlgen.FilterColumns(updateCols, make([]any, len(updateCols)), cols...)
	returning := []string{"id", "user_id", "avatar_url", "website"}

	query, args := sqlgen.BuildUpsert(dialect, ProfileTableName, allCols, allVals, conflictCols, updateCols, returning)
	err = exec.QueryRowContext(ctx, query, args...).Scan(
		&o.ID,
		&o.UserID,
		&o.AvatarURL,
		&o.Website,
	)
	if err != nil {
		return err
	}
	_, err = profileHooks.RunIfEnabled(ctx, exec, sqlgen.AfterUpsert, o)
	return err
}

// Exists checks if a row with the given primary key exists.
func ProfileExists(ctx context.Context, exec sqlgen.Executor, id string) (bool, error) {
	return sqlgen.Exists(ctx, exec, dialect, ProfileTableName,
		sqlgen.Where("\"id\" = ?", id),
	)
}

// CountProfiles returns the count of rows matching the query mods.
func CountProfiles(ctx context.Context, exec sqlgen.Executor, mods ...sqlgen.QueryMod) (int64, error) {
	return sqlgen.Count(ctx, exec, dialect, ProfileTableName, mods...)
}

// UpdateAllProfiles updates all rows matching the given mods.
// set is a map of column name -> new value.
func UpdateAllProfiles(ctx context.Context, exec sqlgen.Executor, set map[string]any, mods ...sqlgen.QueryMod) (int64, error) {
	q := sqlgen.NewQuery(dialect, ProfileTableName, mods...)
	query, args := q.BuildUpdateAll(set)
	result, err := exec.ExecContext(ctx, query, args...)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

// DeleteAllProfiles deletes all rows matching the given mods.
func DeleteAllProfiles(ctx context.Context, exec sqlgen.Executor, mods ...sqlgen.QueryMod) (int64, error) {
	q := sqlgen.NewQuery(dialect, ProfileTableName, mods...)
	query, args := q.BuildDeleteAll()
	result, err := exec.ExecContext(ctx, query, args...)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

// EachProfile executes a query and calls fn for each row. Iteration stops
// early if fn returns an error. Rows are not accumulated in memory.
func EachProfile(ctx context.Context, exec sqlgen.Executor, fn func(*Profile) error, mods ...sqlgen.QueryMod) error {
	return sqlgen.Each(ctx, exec, sqlgen.NewQuery(dialect, ProfileTableName, mods...), func() *Profile { return &Profile{} }, fn)
}

// ProfileCursor returns a cursor for iterating over profiles rows one at a time.
func ProfileCursor(ctx context.Context, exec sqlgen.Executor, mods ...sqlgen.QueryMod) (*sqlgen.Cursor[*Profile], error) {
	return sqlgen.NewCursor(ctx, exec, sqlgen.NewQuery(dialect, ProfileTableName, mods...), func() *Profile { return &Profile{} })
}

// Reload refreshes the Profile from the database using its primary key.
func (o *Profile) Reload(ctx context.Context, exec sqlgen.Executor) error {
	q := sqlgen.NewQuery(dialect, ProfileTableName,
		sqlgen.Where("\"id\" = ?", o.ID),
		sqlgen.Limit(1),
	)
	query, args := q.BuildSelect()
	return o.ScanRow(exec.QueryRowContext(ctx, query, args...))
}

// UpdateAll updates all models in the slice with the given column values.
func (s ProfileSlice) UpdateAll(ctx context.Context, exec sqlgen.Executor, set map[string]any) (int64, error) {
	if len(s) == 0 {
		return 0, nil
	}
	ids := make([]any, len(s))
	for i, o := range s {
		ids[i] = o.ID
	}
	return UpdateAllProfiles(ctx, exec, set, sqlgen.WhereIn("\"id\"", ids...))
}

// DeleteAll deletes all models in the slice.
func (s ProfileSlice) DeleteAll(ctx context.Context, exec sqlgen.Executor) (int64, error) {
	if len(s) == 0 {
		return 0, nil
	}
	ids := make([]any, len(s))
	for i, o := range s {
		ids[i] = o.ID
	}
	return DeleteAllProfiles(ctx, exec, sqlgen.WhereIn("\"id\"", ids...))
}

// InsertAll batch-inserts all models in the slice. Each model's columns are
// scanned back via RETURNING, picking up defaults and generated values.
// Hooks are not fired (consistent with UpdateAll/DeleteAll).
func (s ProfileSlice) InsertAll(ctx context.Context, exec sqlgen.Executor) error {
	if len(s) == 0 {
		return nil
	}
	cols := []string{"user_id", "avatar_url", "website"}
	returning := []string{"id", "user_id", "avatar_url", "website"}

	rows := make([][]any, len(s))
	for i, o := range s {
		rows[i] = []any{o.UserID, o.AvatarURL, o.Website}
	}

	query, args := sqlgen.BuildBatchInsert(dialect, ProfileTableName, cols, rows, returning)
	result, err := exec.QueryContext(ctx, query, args...)
	if err != nil {
		return err
	}
	defer result.Close()

	idx := 0
	for result.Next() {
		if err := s[idx].ScanRow(result); err != nil {
			return err
		}
		idx++
	}
	return result.Err()
}
