// Code generated by sqlgen. DO NOT EDIT.

package models

import (
	"context"

	"github.com/davidbyttow/sqlgen"
	"github.com/davidbyttow/sqlgen/fake"
)

// CommentMod is a function that customizes a Comment before use.
type CommentMod func(*Comment)

// NewComment creates a Comment with random values for all non-auto-increment fields.
// Pass modifier functions to override specific fields.
func NewComment(mods ...CommentMod) *Comment {
	o := &Comment{
		ID:              fake.UUID(),
		AuthorID:        fake.UUID(),
		CommentableType: fake.String("comments_commentable_type"),
		CommentableID:   fake.UUID(),
		Kind:            CommentKind("review"),
		Body:            fake.String("comments_body"),
		CreatedAt:       fake.Time(),
	}
	for _, mod := range mods {
		mod(o)
	}
	return o
}

// InsertComment creates a Comment with random values, applies mods, and inserts it.
func InsertComment(ctx context.Context, exec sqlgen.Executor, mods ...CommentMod) (*Comment, error) {
	o := NewComment(mods...)
	if err := o.Insert(ctx, exec); err != nil {
		return nil, err
	}
	return o, nil
}
