// Code generated by sqlgen. DO NOT EDIT.

package models

import (
	"testing"

	"github.com/davidbyttow/sqlgen"
)

func TestPostTagTableName(t *testing.T) {
	if PostTagTableName != "post_tags" {
		t.Errorf("PostTagTableName = %q, want %q", PostTagTableName, "post_tags")
	}
}

func TestPostTagColumns(t *testing.T) {
	// Verify column constants match expected names.
	cols := map[string]string{
		"PostID": "post_id",
		"TagID":  "tag_id",
	}
	vals := map[string]string{
		"PostID": PostTagColumns.PostID,
		"TagID":  PostTagColumns.TagID,
	}
	for name, want := range cols {
		got := vals[name]
		if got != want {
			t.Errorf("column %s = %q, want %q", name, got, want)
		}
	}
}

func TestPostTagFieldCount(t *testing.T) {
	o := &PostTag{}
	_ = o
}

func TestPostTagQueryBuilder(t *testing.T) {
	q := PostTags()
	sql, args := q.BuildSelect()
	if sql == "" {
		t.Error("BuildSelect returned empty SQL")
	}
	if len(args) != 0 {
		t.Errorf("expected 0 args for unfiltered query, got %d", len(args))
	}

	// With a where clause and limit.
	q = PostTags(
		sqlgen.Where("1 = ?", 1),
		sqlgen.Limit(10),
	)
	sql, args = q.BuildSelect()
	if sql == "" {
		t.Error("BuildSelect with where returned empty SQL")
	}
	if len(args) == 0 {
		t.Error("expected args for filtered query, got 0")
	}
}

func TestPostTagWherePostID(t *testing.T) {
	// EQ
	mod := PostTagWhere.PostID.EQ("")
	q := PostTags(mod)
	sql, args := q.BuildSelect()
	if sql == "" {
		t.Error("EQ query is empty")
	}
	if len(args) != 1 {
		t.Errorf("EQ expected 1 arg, got %d", len(args))
	}

	// IN
	mod = PostTagWhere.PostID.IN("", "")
	q = PostTags(mod)
	sql, args = q.BuildSelect()
	if sql == "" {
		t.Error("IN query is empty")
	}
	if len(args) != 2 {
		t.Errorf("IN expected 2 args, got %d", len(args))
	}
}

func TestPostTagWhereTagID(t *testing.T) {
	// EQ
	mod := PostTagWhere.TagID.EQ(0)
	q := PostTags(mod)
	sql, args := q.BuildSelect()
	if sql == "" {
		t.Error("EQ query is empty")
	}
	if len(args) != 1 {
		t.Errorf("EQ expected 1 arg, got %d", len(args))
	}

	// IN
	mod = PostTagWhere.TagID.IN(0, 0)
	q = PostTags(mod)
	sql, args = q.BuildSelect()
	if sql == "" {
		t.Error("IN query is empty")
	}
	if len(args) != 2 {
		t.Errorf("IN expected 2 args, got %d", len(args))
	}
}

func TestPostTagBuildUpdateAll(t *testing.T) {
	q := PostTags(
		sqlgen.Where("1 = ?", 1),
	)
	sql, args := q.BuildUpdateAll(map[string]any{"post_id": nil})
	if sql == "" {
		t.Error("BuildUpdateAll returned empty SQL")
	}
	if len(args) < 2 {
		t.Errorf("expected at least 2 args (set + where), got %d", len(args))
	}
}

func TestPostTagBuildDeleteAll(t *testing.T) {
	q := PostTags(
		sqlgen.Where("1 = ?", 1),
	)
	sql, args := q.BuildDeleteAll()
	if sql == "" {
		t.Error("BuildDeleteAll returned empty SQL")
	}
	if len(args) != 1 {
		t.Errorf("expected 1 arg, got %d", len(args))
	}
}
