// Code generated by sqlgen. DO NOT EDIT.

package models

import (
	"encoding/json"
	"testing"
	"time"

	"github.com/davidbyttow/sqlgen"
)

func TestUserTableName(t *testing.T) {
	if UserTableName != "users" {
		t.Errorf("UserTableName = %q, want %q", UserTableName, "users")
	}
}

func TestUserColumns(t *testing.T) {
	// Verify column constants match expected names.
	cols := map[string]string{
		"ID":        "id",
		"Email":     "email",
		"Name":      "name",
		"Bio":       "bio",
		"Age":       "age",
		"Score":     "score",
		"IsAdmin":   "is_admin",
		"Metadata":  "metadata",
		"CreatedAt": "created_at",
	}
	vals := map[string]string{
		"ID":        UserColumns.ID,
		"Email":     UserColumns.Email,
		"Name":      UserColumns.Name,
		"Bio":       UserColumns.Bio,
		"Age":       UserColumns.Age,
		"Score":     UserColumns.Score,
		"IsAdmin":   UserColumns.IsAdmin,
		"Metadata":  UserColumns.Metadata,
		"CreatedAt": UserColumns.CreatedAt,
	}
	for name, want := range cols {
		got := vals[name]
		if got != want {
			t.Errorf("column %s = %q, want %q", name, got, want)
		}
	}
}

func TestUserFieldCount(t *testing.T) {
	o := &User{}
	_ = o
}

func TestUserQueryBuilder(t *testing.T) {
	q := Users()
	sql, args := q.BuildSelect()
	if sql == "" {
		t.Error("BuildSelect returned empty SQL")
	}
	if len(args) != 0 {
		t.Errorf("expected 0 args for unfiltered query, got %d", len(args))
	}

	// With a where clause and limit.
	q = Users(
		sqlgen.Where("1 = ?", 1),
		sqlgen.Limit(10),
	)
	sql, args = q.BuildSelect()
	if sql == "" {
		t.Error("BuildSelect with where returned empty SQL")
	}
	if len(args) == 0 {
		t.Error("expected args for filtered query, got 0")
	}
}

func TestUserWhereID(t *testing.T) {
	// EQ
	mod := UserWhere.ID.EQ("")
	q := Users(mod)
	sql, args := q.BuildSelect()
	if sql == "" {
		t.Error("EQ query is empty")
	}
	if len(args) != 1 {
		t.Errorf("EQ expected 1 arg, got %d", len(args))
	}

	// IN
	mod = UserWhere.ID.IN("", "")
	q = Users(mod)
	sql, args = q.BuildSelect()
	if sql == "" {
		t.Error("IN query is empty")
	}
	if len(args) != 2 {
		t.Errorf("IN expected 2 args, got %d", len(args))
	}
}

func TestUserWhereEmail(t *testing.T) {
	// EQ
	mod := UserWhere.Email.EQ("")
	q := Users(mod)
	sql, args := q.BuildSelect()
	if sql == "" {
		t.Error("EQ query is empty")
	}
	if len(args) != 1 {
		t.Errorf("EQ expected 1 arg, got %d", len(args))
	}

	// IN
	mod = UserWhere.Email.IN("", "")
	q = Users(mod)
	sql, args = q.BuildSelect()
	if sql == "" {
		t.Error("IN query is empty")
	}
	if len(args) != 2 {
		t.Errorf("IN expected 2 args, got %d", len(args))
	}
}

func TestUserWhereName(t *testing.T) {
	// EQ
	mod := UserWhere.Name.EQ("")
	q := Users(mod)
	sql, args := q.BuildSelect()
	if sql == "" {
		t.Error("EQ query is empty")
	}
	if len(args) != 1 {
		t.Errorf("EQ expected 1 arg, got %d", len(args))
	}

	// IN
	mod = UserWhere.Name.IN("", "")
	q = Users(mod)
	sql, args = q.BuildSelect()
	if sql == "" {
		t.Error("IN query is empty")
	}
	if len(args) != 2 {
		t.Errorf("IN expected 2 args, got %d", len(args))
	}
}

func TestUserWhereBio(t *testing.T) {
	// EQ
	mod := UserWhere.Bio.EQ(sqlgen.Null[string]{})
	q := Users(mod)
	sql, args := q.BuildSelect()
	if sql == "" {
		t.Error("EQ query is empty")
	}
	if len(args) != 1 {
		t.Errorf("EQ expected 1 arg, got %d", len(args))
	}

	// IN
	mod = UserWhere.Bio.IN(sqlgen.Null[string]{}, sqlgen.Null[string]{})
	q = Users(mod)
	sql, args = q.BuildSelect()
	if sql == "" {
		t.Error("IN query is empty")
	}
	if len(args) != 2 {
		t.Errorf("IN expected 2 args, got %d", len(args))
	}

	// IsNull / IsNotNull
	q = Users(UserWhere.Bio.IsNull())
	sql, _ = q.BuildSelect()
	if sql == "" {
		t.Error("IsNull query is empty")
	}
	q = Users(UserWhere.Bio.IsNotNull())
	sql, _ = q.BuildSelect()
	if sql == "" {
		t.Error("IsNotNull query is empty")
	}
}

func TestUserWhereAge(t *testing.T) {
	// EQ
	mod := UserWhere.Age.EQ(sqlgen.Null[int32]{})
	q := Users(mod)
	sql, args := q.BuildSelect()
	if sql == "" {
		t.Error("EQ query is empty")
	}
	if len(args) != 1 {
		t.Errorf("EQ expected 1 arg, got %d", len(args))
	}

	// IN
	mod = UserWhere.Age.IN(sqlgen.Null[int32]{}, sqlgen.Null[int32]{})
	q = Users(mod)
	sql, args = q.BuildSelect()
	if sql == "" {
		t.Error("IN query is empty")
	}
	if len(args) != 2 {
		t.Errorf("IN expected 2 args, got %d", len(args))
	}

	// IsNull / IsNotNull
	q = Users(UserWhere.Age.IsNull())
	sql, _ = q.BuildSelect()
	if sql == "" {
		t.Error("IsNull query is empty")
	}
	q = Users(UserWhere.Age.IsNotNull())
	sql, _ = q.BuildSelect()
	if sql == "" {
		t.Error("IsNotNull query is empty")
	}
}

func TestUserWhereScore(t *testing.T) {
	// EQ
	mod := UserWhere.Score.EQ(sqlgen.Null[string]{})
	q := Users(mod)
	sql, args := q.BuildSelect()
	if sql == "" {
		t.Error("EQ query is empty")
	}
	if len(args) != 1 {
		t.Errorf("EQ expected 1 arg, got %d", len(args))
	}

	// IN
	mod = UserWhere.Score.IN(sqlgen.Null[string]{}, sqlgen.Null[string]{})
	q = Users(mod)
	sql, args = q.BuildSelect()
	if sql == "" {
		t.Error("IN query is empty")
	}
	if len(args) != 2 {
		t.Errorf("IN expected 2 args, got %d", len(args))
	}

	// IsNull / IsNotNull
	q = Users(UserWhere.Score.IsNull())
	sql, _ = q.BuildSelect()
	if sql == "" {
		t.Error("IsNull query is empty")
	}
	q = Users(UserWhere.Score.IsNotNull())
	sql, _ = q.BuildSelect()
	if sql == "" {
		t.Error("IsNotNull query is empty")
	}
}

func TestUserWhereIsAdmin(t *testing.T) {
	// EQ
	mod := UserWhere.IsAdmin.EQ(false)
	q := Users(mod)
	sql, args := q.BuildSelect()
	if sql == "" {
		t.Error("EQ query is empty")
	}
	if len(args) != 1 {
		t.Errorf("EQ expected 1 arg, got %d", len(args))
	}

	// IN
	mod = UserWhere.IsAdmin.IN(false, false)
	q = Users(mod)
	sql, args = q.BuildSelect()
	if sql == "" {
		t.Error("IN query is empty")
	}
	if len(args) != 2 {
		t.Errorf("IN expected 2 args, got %d", len(args))
	}
}

func TestUserWhereMetadata(t *testing.T) {
	// EQ
	mod := UserWhere.Metadata.EQ(sqlgen.Null[json.RawMessage]{})
	q := Users(mod)
	sql, args := q.BuildSelect()
	if sql == "" {
		t.Error("EQ query is empty")
	}
	if len(args) != 1 {
		t.Errorf("EQ expected 1 arg, got %d", len(args))
	}

	// IN
	mod = UserWhere.Metadata.IN(sqlgen.Null[json.RawMessage]{}, sqlgen.Null[json.RawMessage]{})
	q = Users(mod)
	sql, args = q.BuildSelect()
	if sql == "" {
		t.Error("IN query is empty")
	}
	if len(args) != 2 {
		t.Errorf("IN expected 2 args, got %d", len(args))
	}

	// IsNull / IsNotNull
	q = Users(UserWhere.Metadata.IsNull())
	sql, _ = q.BuildSelect()
	if sql == "" {
		t.Error("IsNull query is empty")
	}
	q = Users(UserWhere.Metadata.IsNotNull())
	sql, _ = q.BuildSelect()
	if sql == "" {
		t.Error("IsNotNull query is empty")
	}
}

func TestUserWhereCreatedAt(t *testing.T) {
	// EQ
	mod := UserWhere.CreatedAt.EQ(time.Time{})
	q := Users(mod)
	sql, args := q.BuildSelect()
	if sql == "" {
		t.Error("EQ query is empty")
	}
	if len(args) != 1 {
		t.Errorf("EQ expected 1 arg, got %d", len(args))
	}

	// IN
	mod = UserWhere.CreatedAt.IN(time.Time{}, time.Time{})
	q = Users(mod)
	sql, args = q.BuildSelect()
	if sql == "" {
		t.Error("IN query is empty")
	}
	if len(args) != 2 {
		t.Errorf("IN expected 2 args, got %d", len(args))
	}
}

func TestUserBuildUpdateAll(t *testing.T) {
	q := Users(
		sqlgen.Where("1 = ?", 1),
	)
	sql, args := q.BuildUpdateAll(map[string]any{"id": nil})
	if sql == "" {
		t.Error("BuildUpdateAll returned empty SQL")
	}
	if len(args) < 2 {
		t.Errorf("expected at least 2 args (set + where), got %d", len(args))
	}
}

func TestUserBuildDeleteAll(t *testing.T) {
	q := Users(
		sqlgen.Where("1 = ?", 1),
	)
	sql, args := q.BuildDeleteAll()
	if sql == "" {
		t.Error("BuildDeleteAll returned empty SQL")
	}
	if len(args) != 1 {
		t.Errorf("expected 1 arg, got %d", len(args))
	}
}
