// Code generated by sqlgen. DO NOT EDIT.

package models

import (
	"testing"

	"github.com/davidbyttow/sqlgen"
)

func TestProfileTableName(t *testing.T) {
	if ProfileTableName != "profiles" {
		t.Errorf("ProfileTableName = %q, want %q", ProfileTableName, "profiles")
	}
}

func TestProfileColumns(t *testing.T) {
	// Verify column constants match expected names.
	cols := map[string]string{
		"ID":        "id",
		"UserID":    "user_id",
		"AvatarURL": "avatar_url",
		"Website":   "website",
	}
	vals := map[string]string{
		"ID":        ProfileColumns.ID,
		"UserID":    ProfileColumns.UserID,
		"AvatarURL": ProfileColumns.AvatarURL,
		"Website":   ProfileColumns.Website,
	}
	for name, want := range cols {
		got := vals[name]
		if got != want {
			t.Errorf("column %s = %q, want %q", name, got, want)
		}
	}
}

func TestProfileFieldCount(t *testing.T) {
	o := &Profile{}
	_ = o
}

func TestProfileQueryBuilder(t *testing.T) {
	q := Profiles()
	sql, args := q.BuildSelect()
	if sql == "" {
		t.Error("BuildSelect returned empty SQL")
	}
	if len(args) != 0 {
		t.Errorf("expected 0 args for unfiltered query, got %d", len(args))
	}

	// With a where clause and limit.
	q = Profiles(
		sqlgen.Where("1 = ?", 1),
		sqlgen.Limit(10),
	)
	sql, args = q.BuildSelect()
	if sql == "" {
		t.Error("BuildSelect with where returned empty SQL")
	}
	if len(args) == 0 {
		t.Error("expected args for filtered query, got 0")
	}
}

func TestProfileWhereID(t *testing.T) {
	// EQ
	mod := ProfileWhere.ID.EQ("")
	q := Profiles(mod)
	sql, args := q.BuildSelect()
	if sql == "" {
		t.Error("EQ query is empty")
	}
	if len(args) != 1 {
		t.Errorf("EQ expected 1 arg, got %d", len(args))
	}

	// IN
	mod = ProfileWhere.ID.IN("", "")
	q = Profiles(mod)
	sql, args = q.BuildSelect()
	if sql == "" {
		t.Error("IN query is empty")
	}
	if len(args) != 2 {
		t.Errorf("IN expected 2 args, got %d", len(args))
	}
}

func TestProfileWhereUserID(t *testing.T) {
	// EQ
	mod := ProfileWhere.UserID.EQ("")
	q := Profiles(mod)
	sql, args := q.BuildSelect()
	if sql == "" {
		t.Error("EQ query is empty")
	}
	if len(args) != 1 {
		t.Errorf("EQ expected 1 arg, got %d", len(args))
	}

	// IN
	mod = ProfileWhere.UserID.IN("", "")
	q = Profiles(mod)
	sql, args = q.BuildSelect()
	if sql == "" {
		t.Error("IN query is empty")
	}
	if len(args) != 2 {
		t.Errorf("IN expected 2 args, got %d", len(args))
	}
}

func TestProfileWhereAvatarURL(t *testing.T) {
	// EQ
	mod := ProfileWhere.AvatarURL.EQ(sqlgen.Null[string]{})
	q := Profiles(mod)
	sql, args := q.BuildSelect()
	if sql == "" {
		t.Error("EQ query is empty")
	}
	if len(args) != 1 {
		t.Errorf("EQ expected 1 arg, got %d", len(args))
	}

	// IN
	mod = ProfileWhere.AvatarURL.IN(sqlgen.Null[string]{}, sqlgen.Null[string]{})
	q = Profiles(mod)
	sql, args = q.BuildSelect()
	if sql == "" {
		t.Error("IN query is empty")
	}
	if len(args) != 2 {
		t.Errorf("IN expected 2 args, got %d", len(args))
	}

	// IsNull / IsNotNull
	q = Profiles(ProfileWhere.AvatarURL.IsNull())
	sql, _ = q.BuildSelect()
	if sql == "" {
		t.Error("IsNull query is empty")
	}
	q = Profiles(ProfileWhere.AvatarURL.IsNotNull())
	sql, _ = q.BuildSelect()
	if sql == "" {
		t.Error("IsNotNull query is empty")
	}
}

func TestProfileWhereWebsite(t *testing.T) {
	// EQ
	mod := ProfileWhere.Website.EQ(sqlgen.Null[string]{})
	q := Profiles(mod)
	sql, args := q.BuildSelect()
	if sql == "" {
		t.Error("EQ query is empty")
	}
	if len(args) != 1 {
		t.Errorf("EQ expected 1 arg, got %d", len(args))
	}

	// IN
	mod = ProfileWhere.Website.IN(sqlgen.Null[string]{}, sqlgen.Null[string]{})
	q = Profiles(mod)
	sql, args = q.BuildSelect()
	if sql == "" {
		t.Error("IN query is empty")
	}
	if len(args) != 2 {
		t.Errorf("IN expected 2 args, got %d", len(args))
	}

	// IsNull / IsNotNull
	q = Profiles(ProfileWhere.Website.IsNull())
	sql, _ = q.BuildSelect()
	if sql == "" {
		t.Error("IsNull query is empty")
	}
	q = Profiles(ProfileWhere.Website.IsNotNull())
	sql, _ = q.BuildSelect()
	if sql == "" {
		t.Error("IsNotNull query is empty")
	}
}

func TestProfileBuildUpdateAll(t *testing.T) {
	q := Profiles(
		sqlgen.Where("1 = ?", 1),
	)
	sql, args := q.BuildUpdateAll(map[string]any{"id": nil})
	if sql == "" {
		t.Error("BuildUpdateAll returned empty SQL")
	}
	if len(args) < 2 {
		t.Errorf("expected at least 2 args (set + where), got %d", len(args))
	}
}

func TestProfileBuildDeleteAll(t *testing.T) {
	q := Profiles(
		sqlgen.Where("1 = ?", 1),
	)
	sql, args := q.BuildDeleteAll()
	if sql == "" {
		t.Error("BuildDeleteAll returned empty SQL")
	}
	if len(args) != 1 {
		t.Errorf("expected 1 arg, got %d", len(args))
	}
}
