// Code generated by sqlgen. DO NOT EDIT.

package models

import (
	"context"

	"github.com/davidbyttow/sqlgen"
	"github.com/davidbyttow/sqlgen/fake"
)

// PostMod is a function that customizes a Post before use.
type PostMod func(*Post)

// NewPost creates a Post with random values for all non-auto-increment fields.
// Pass modifier functions to override specific fields.
func NewPost(mods ...PostMod) *Post {
	o := &Post{
		ID:          fake.UUID(),
		AuthorID:    fake.UUID(),
		CategoryID:  sqlgen.NewNull(fake.Int32()),
		Title:       fake.String("posts_title"),
		Body:        fake.String("posts_body"),
		Status:      PostStatus("draft"),
		CreatedAt:   fake.Time(),
		PublishedAt: sqlgen.NewNull(fake.Time()),
	}
	for _, mod := range mods {
		mod(o)
	}
	return o
}

// InsertPost creates a Post with random values, applies mods, and inserts it.
func InsertPost(ctx context.Context, exec sqlgen.Executor, mods ...PostMod) (*Post, error) {
	o := NewPost(mods...)
	if err := o.Insert(ctx, exec); err != nil {
		return nil, err
	}
	return o, nil
}
