// Code generated by sqlgen. DO NOT EDIT.

package models

import (
	"github.com/davidbyttow/sqlgen"
)

// userProfilePreload holds nullable scan targets for LEFT JOINed Profile columns.
type userProfilePreload struct {
	id        sqlgen.Null[string]
	userID    sqlgen.Null[string]
	avatarURL sqlgen.Null[string]
	website   sqlgen.Null[string]
}

func (p *userProfilePreload) scanDests() []any {
	return []any{
		&p.id,
		&p.userID,
		&p.avatarURL,
		&p.website,
	}
}

func (p *userProfilePreload) assign(o *User) {
	if !p.id.Valid {
		return
	}
	if o.R == nil {
		o.R = &UserRels{}
	}
	o.R.Profile = &Profile{
		ID:        p.id.Val,
		UserID:    p.userID.Val,
		AvatarURL: p.avatarURL,
		Website:   p.website,
	}
}

// UserPreloadProfile is the PreloadDef for the Profile relationship.
var UserPreloadProfile = sqlgen.PreloadDef{
	Name:     "Profile",
	Table:    ProfileTableName,
	JoinCond: "\"profiles\".\"user_id\" = \"users\".\"id\"",
	Columns: []string{
		"\"profiles\".\"id\"",
		"\"profiles\".\"user_id\"",
		"\"profiles\".\"avatar_url\"",
		"\"profiles\".\"website\"",
	},
}

// userPreloadState is the interface for preload scan states.
type userPreloadState interface {
	scanDests() []any
	assign(o *User)
}

// newUserPreloadState returns a preload state for the named relationship.
func newUserPreloadState(name string) userPreloadState {
	switch name {
	case "Profile":
		return &userProfilePreload{}
	}
	return nil
}
