// Code generated by sqlgen. DO NOT EDIT.

package models

import (
	"context"

	"github.com/davidbyttow/sqlgen"
)

// postHooks stores the hooks for Post.
var postHooks = sqlgen.NewHooks()

// PostHook is a typed hook function for Post lifecycle events.
type PostHook func(ctx context.Context, exec sqlgen.Executor, model *Post) (context.Context, error)

// AddPostHook registers a typed hook for the given hook point.
// The hook receives the model pointer and can inspect or modify it.
func AddPostHook(point sqlgen.HookPoint, fn PostHook) {
	postHooks.Add(point, func(ctx context.Context, exec sqlgen.Executor, model any) (context.Context, error) {
		return fn(ctx, exec, model.(*Post))
	})
}
