// Code generated by sqlgen. DO NOT EDIT.

package models

import (
	"testing"
	"time"

	"github.com/davidbyttow/sqlgen"
)

func TestPostTableName(t *testing.T) {
	if PostTableName != "posts" {
		t.Errorf("PostTableName = %q, want %q", PostTableName, "posts")
	}
}

func TestPostColumns(t *testing.T) {
	// Verify column constants match expected names.
	cols := map[string]string{
		"ID":          "id",
		"AuthorID":    "author_id",
		"CategoryID":  "category_id",
		"Title":       "title",
		"Body":        "body",
		"Status":      "status",
		"CreatedAt":   "created_at",
		"PublishedAt": "published_at",
	}
	vals := map[string]string{
		"ID":          PostColumns.ID,
		"AuthorID":    PostColumns.AuthorID,
		"CategoryID":  PostColumns.CategoryID,
		"Title":       PostColumns.Title,
		"Body":        PostColumns.Body,
		"Status":      PostColumns.Status,
		"CreatedAt":   PostColumns.CreatedAt,
		"PublishedAt": PostColumns.PublishedAt,
	}
	for name, want := range cols {
		got := vals[name]
		if got != want {
			t.Errorf("column %s = %q, want %q", name, got, want)
		}
	}
}

func TestPostFieldCount(t *testing.T) {
	o := &Post{}
	_ = o
}

func TestPostQueryBuilder(t *testing.T) {
	q := Posts()
	sql, args := q.BuildSelect()
	if sql == "" {
		t.Error("BuildSelect returned empty SQL")
	}
	if len(args) != 0 {
		t.Errorf("expected 0 args for unfiltered query, got %d", len(args))
	}

	// With a where clause and limit.
	q = Posts(
		sqlgen.Where("1 = ?", 1),
		sqlgen.Limit(10),
	)
	sql, args = q.BuildSelect()
	if sql == "" {
		t.Error("BuildSelect with where returned empty SQL")
	}
	if len(args) == 0 {
		t.Error("expected args for filtered query, got 0")
	}
}

func TestPostWhereID(t *testing.T) {
	// EQ
	mod := PostWhere.ID.EQ("")
	q := Posts(mod)
	sql, args := q.BuildSelect()
	if sql == "" {
		t.Error("EQ query is empty")
	}
	if len(args) != 1 {
		t.Errorf("EQ expected 1 arg, got %d", len(args))
	}

	// IN
	mod = PostWhere.ID.IN("", "")
	q = Posts(mod)
	sql, args = q.BuildSelect()
	if sql == "" {
		t.Error("IN query is empty")
	}
	if len(args) != 2 {
		t.Errorf("IN expected 2 args, got %d", len(args))
	}
}

func TestPostWhereAuthorID(t *testing.T) {
	// EQ
	mod := PostWhere.AuthorID.EQ("")
	q := Posts(mod)
	sql, args := q.BuildSelect()
	if sql == "" {
		t.Error("EQ query is empty")
	}
	if len(args) != 1 {
		t.Errorf("EQ expected 1 arg, got %d", len(args))
	}

	// IN
	mod = PostWhere.AuthorID.IN("", "")
	q = Posts(mod)
	sql, args = q.BuildSelect()
	if sql == "" {
		t.Error("IN query is empty")
	}
	if len(args) != 2 {
		t.Errorf("IN expected 2 args, got %d", len(args))
	}
}

func TestPostWhereCategoryID(t *testing.T) {
	// EQ
	mod := PostWhere.CategoryID.EQ(sqlgen.Null[int32]{})
	q := Posts(mod)
	sql, args := q.BuildSelect()
	if sql == "" {
		t.Error("EQ query is empty")
	}
	if len(args) != 1 {
		t.Errorf("EQ expected 1 arg, got %d", len(args))
	}

	// IN
	mod = PostWhere.CategoryID.IN(sqlgen.Null[int32]{}, sqlgen.Null[int32]{})
	q = Posts(mod)
	sql, args = q.BuildSelect()
	if sql == "" {
		t.Error("IN query is empty")
	}
	if len(args) != 2 {
		t.Errorf("IN expected 2 args, got %d", len(args))
	}

	// IsNull / IsNotNull
	q = Posts(PostWhere.CategoryID.IsNull())
	sql, _ = q.BuildSelect()
	if sql == "" {
		t.Error("IsNull query is empty")
	}
	q = Posts(PostWhere.CategoryID.IsNotNull())
	sql, _ = q.BuildSelect()
	if sql == "" {
		t.Error("IsNotNull query is empty")
	}
}

func TestPostWhereTitle(t *testing.T) {
	// EQ
	mod := PostWhere.Title.EQ("")
	q := Posts(mod)
	sql, args := q.BuildSelect()
	if sql == "" {
		t.Error("EQ query is empty")
	}
	if len(args) != 1 {
		t.Errorf("EQ expected 1 arg, got %d", len(args))
	}

	// IN
	mod = PostWhere.Title.IN("", "")
	q = Posts(mod)
	sql, args = q.BuildSelect()
	if sql == "" {
		t.Error("IN query is empty")
	}
	if len(args) != 2 {
		t.Errorf("IN expected 2 args, got %d", len(args))
	}
}

func TestPostWhereBody(t *testing.T) {
	// EQ
	mod := PostWhere.Body.EQ("")
	q := Posts(mod)
	sql, args := q.BuildSelect()
	if sql == "" {
		t.Error("EQ query is empty")
	}
	if len(args) != 1 {
		t.Errorf("EQ expected 1 arg, got %d", len(args))
	}

	// IN
	mod = PostWhere.Body.IN("", "")
	q = Posts(mod)
	sql, args = q.BuildSelect()
	if sql == "" {
		t.Error("IN query is empty")
	}
	if len(args) != 2 {
		t.Errorf("IN expected 2 args, got %d", len(args))
	}
}

func TestPostWhereStatus(t *testing.T) {
	// EQ
	mod := PostWhere.Status.EQ(PostStatus(""))
	q := Posts(mod)
	sql, args := q.BuildSelect()
	if sql == "" {
		t.Error("EQ query is empty")
	}
	if len(args) != 1 {
		t.Errorf("EQ expected 1 arg, got %d", len(args))
	}

	// IN
	mod = PostWhere.Status.IN(PostStatus(""), PostStatus(""))
	q = Posts(mod)
	sql, args = q.BuildSelect()
	if sql == "" {
		t.Error("IN query is empty")
	}
	if len(args) != 2 {
		t.Errorf("IN expected 2 args, got %d", len(args))
	}
}

func TestPostWhereCreatedAt(t *testing.T) {
	// EQ
	mod := PostWhere.CreatedAt.EQ(time.Time{})
	q := Posts(mod)
	sql, args := q.BuildSelect()
	if sql == "" {
		t.Error("EQ query is empty")
	}
	if len(args) != 1 {
		t.Errorf("EQ expected 1 arg, got %d", len(args))
	}

	// IN
	mod = PostWhere.CreatedAt.IN(time.Time{}, time.Time{})
	q = Posts(mod)
	sql, args = q.BuildSelect()
	if sql == "" {
		t.Error("IN query is empty")
	}
	if len(args) != 2 {
		t.Errorf("IN expected 2 args, got %d", len(args))
	}
}

func TestPostWherePublishedAt(t *testing.T) {
	// EQ
	mod := PostWhere.PublishedAt.EQ(sqlgen.Null[time.Time]{})
	q := Posts(mod)
	sql, args := q.BuildSelect()
	if sql == "" {
		t.Error("EQ query is empty")
	}
	if len(args) != 1 {
		t.Errorf("EQ expected 1 arg, got %d", len(args))
	}

	// IN
	mod = PostWhere.PublishedAt.IN(sqlgen.Null[time.Time]{}, sqlgen.Null[time.Time]{})
	q = Posts(mod)
	sql, args = q.BuildSelect()
	if sql == "" {
		t.Error("IN query is empty")
	}
	if len(args) != 2 {
		t.Errorf("IN expected 2 args, got %d", len(args))
	}

	// IsNull / IsNotNull
	q = Posts(PostWhere.PublishedAt.IsNull())
	sql, _ = q.BuildSelect()
	if sql == "" {
		t.Error("IsNull query is empty")
	}
	q = Posts(PostWhere.PublishedAt.IsNotNull())
	sql, _ = q.BuildSelect()
	if sql == "" {
		t.Error("IsNotNull query is empty")
	}
}

func TestPostBuildUpdateAll(t *testing.T) {
	q := Posts(
		sqlgen.Where("1 = ?", 1),
	)
	sql, args := q.BuildUpdateAll(map[string]any{"id": nil})
	if sql == "" {
		t.Error("BuildUpdateAll returned empty SQL")
	}
	if len(args) < 2 {
		t.Errorf("expected at least 2 args (set + where), got %d", len(args))
	}
}

func TestPostBuildDeleteAll(t *testing.T) {
	q := Posts(
		sqlgen.Where("1 = ?", 1),
	)
	sql, args := q.BuildDeleteAll()
	if sql == "" {
		t.Error("BuildDeleteAll returned empty SQL")
	}
	if len(args) != 1 {
		t.Errorf("expected 1 arg, got %d", len(args))
	}
}
