// Code generated by sqlgen. DO NOT EDIT.

package models

import (
	"time"
)

// CommentTableName is the database table name.
const CommentTableName = "comments"

// CommentColumns contains all column names for the comments table.
var CommentColumns = struct {
	ID              string
	AuthorID        string
	CommentableType string
	CommentableID   string
	Kind            string
	Body            string
	CreatedAt       string
}{
	ID:              "id",
	AuthorID:        "author_id",
	CommentableType: "commentable_type",
	CommentableID:   "commentable_id",
	Kind:            "kind",
	Body:            "body",
	CreatedAt:       "created_at",
}

// Comment represents a row from the 'comments' table.
type Comment struct {
	ID              string      `db:"id" json:"id"`
	AuthorID        string      `db:"author_id" json:"author_id"`
	CommentableType string      `db:"commentable_type" json:"commentable_type"`
	CommentableID   string      `db:"commentable_id" json:"commentable_id"`
	Kind            CommentKind `db:"kind" json:"kind"`
	Body            string      `db:"body" json:"body"`
	CreatedAt       time.Time   `db:"created_at" json:"created_at"`

	R *CommentRels `db:"-" json:"-"`
}

// CommentRels holds eagerly loaded relationships.
type CommentRels struct {
	User *User
	Post *Post
}

// CommentSlice is a slice of Comment pointers.
type CommentSlice []*Comment

// ScanRow scans a database row into a Comment.
func (o *Comment) ScanRow(rows interface{ Scan(...any) error }) error {
	return rows.Scan(
		&o.ID,
		&o.AuthorID,
		&o.CommentableType,
		&o.CommentableID,
		&o.Kind,
		&o.Body,
		&o.CreatedAt,
	)
}

// scanDests returns scan destinations for all columns (used by preload-aware queries).
func (o *Comment) scanDests() []any {
	return []any{
		&o.ID,
		&o.AuthorID,
		&o.CommentableType,
		&o.CommentableID,
		&o.Kind,
		&o.Body,
		&o.CreatedAt,
	}
}
