// Code generated by sqlgen. DO NOT EDIT.

package models

import (
	"context"

	"github.com/davidbyttow/sqlgen"
)

// Comments returns a query builder for the comments table.
func Comments(mods ...sqlgen.QueryMod) *sqlgen.Query {
	return sqlgen.NewQuery(dialect, CommentTableName, mods...)
}

// FindCommentByPK finds a Comment by primary key.
func FindCommentByPK(ctx context.Context, exec sqlgen.Executor, id string) (*Comment, error) {
	q := sqlgen.NewQuery(dialect, CommentTableName,
		sqlgen.Where("\"id\" = ?", id),
		sqlgen.Limit(1),
	)

	query, args := q.BuildSelect()
	row := exec.QueryRowContext(ctx, query, args...)

	o := &Comment{}
	if err := o.ScanRow(row); err != nil {
		return nil, err
	}
	return o, nil
}

// AllComments retrieves all rows from the comments table with the given query mods.
// Supports Preload() for LEFT JOIN eager loading of to-one relationships.
func AllComments(ctx context.Context, exec sqlgen.Executor, mods ...sqlgen.QueryMod) (CommentSlice, error) {
	q := sqlgen.NewQuery(dialect, CommentTableName, mods...)
	query, args := q.BuildSelect()
	rows, err := exec.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	preloads := q.Preloads()

	var result CommentSlice
	for rows.Next() {
		o := &Comment{}
		if len(preloads) == 0 {
			if err := o.ScanRow(rows); err != nil {
				return nil, err
			}
		} else {
			dests := o.scanDests()
			var states []commentPreloadState
			for _, p := range preloads {
				ps := newCommentPreloadState(p.Name)
				if ps != nil {
					dests = append(dests, ps.scanDests()...)
					states = append(states, ps)
				}
			}
			if err := rows.Scan(dests...); err != nil {
				return nil, err
			}
			for _, ps := range states {
				ps.assign(o)
			}
		}
		result = append(result, o)
	}
	return result, rows.Err()
}

// Insert inserts the Comment into the database.
// Optional Columns parameter controls which columns are included (Whitelist/Blacklist).
func (o *Comment) Insert(ctx context.Context, exec sqlgen.Executor, cols ...sqlgen.Columns) error {
	ctx, err := commentHooks.RunIfEnabled(ctx, exec, sqlgen.BeforeInsert, o)
	if err != nil {
		return err
	}
	allCols := []string{"author_id", "commentable_type", "commentable_id", "kind", "body", "created_at"}
	allVals := []any{o.AuthorID, o.CommentableType, o.CommentableID, o.Kind, o.Body, o.CreatedAt}
	allCols, allVals = sqlgen.FilterColumns(allCols, allVals, cols...)

	returning := []string{"id", "author_id", "commentable_type", "commentable_id", "kind", "body", "created_at"}

	query, args := sqlgen.BuildInsert(dialect, CommentTableName, allCols, allVals, returning)
	err = exec.QueryRowContext(ctx, query, args...).Scan(
		&o.ID,
		&o.AuthorID,
		&o.CommentableType,
		&o.CommentableID,
		&o.Kind,
		&o.Body,
		&o.CreatedAt,
	)
	if err != nil {
		return err
	}
	_, err = commentHooks.RunIfEnabled(ctx, exec, sqlgen.AfterInsert, o)
	return err
}

// Update updates the Comment in the database. Only non-PK columns are updated.
// Optional Columns parameter controls which columns are included (Whitelist/Blacklist).
func (o *Comment) Update(ctx context.Context, exec sqlgen.Executor, cols ...sqlgen.Columns) error {
	ctx, err := commentHooks.RunIfEnabled(ctx, exec, sqlgen.BeforeUpdate, o)
	if err != nil {
		return err
	}
	setCols := []string{"author_id", "commentable_type", "commentable_id", "kind", "body", "created_at"}
	setVals := []any{o.AuthorID, o.CommentableType, o.CommentableID, o.Kind, o.Body, o.CreatedAt}
	setCols, setVals = sqlgen.FilterColumns(setCols, setVals, cols...)

	whereClauses := []string{"\"id\" = ?"}
	whereArgs := []any{o.ID}

	query, args := sqlgen.BuildUpdate(dialect, CommentTableName, setCols, setVals, whereClauses, whereArgs)
	_, err = exec.ExecContext(ctx, query, args...)
	if err != nil {
		return err
	}
	_, err = commentHooks.RunIfEnabled(ctx, exec, sqlgen.AfterUpdate, o)
	return err
}

// Delete deletes the Comment from the database.
func (o *Comment) Delete(ctx context.Context, exec sqlgen.Executor) error {
	ctx, err := commentHooks.RunIfEnabled(ctx, exec, sqlgen.BeforeDelete, o)
	if err != nil {
		return err
	}

	whereClauses := []string{"\"id\" = ?"}
	whereArgs := []any{o.ID}

	query, args := sqlgen.BuildDelete(dialect, CommentTableName, whereClauses, whereArgs)
	_, err = exec.ExecContext(ctx, query, args...)
	if err != nil {
		return err
	}
	_, err = commentHooks.RunIfEnabled(ctx, exec, sqlgen.AfterDelete, o)
	return err
}

// Upsert inserts or updates the Comment based on the primary key.
// Optional Columns parameter controls which non-PK columns are included (Whitelist/Blacklist).
func (o *Comment) Upsert(ctx context.Context, exec sqlgen.Executor, cols ...sqlgen.Columns) error {
	ctx, err := commentHooks.RunIfEnabled(ctx, exec, sqlgen.BeforeUpsert, o)
	if err != nil {
		return err
	}
	allCols := []string{"id", "author_id", "commentable_type", "commentable_id", "kind", "body", "created_at"}
	allVals := []any{o.ID, o.AuthorID, o.CommentableType, o.CommentableID, o.Kind, o.Body, o.CreatedAt}
	allCols, allVals = sqlgen.FilterColumns(allCols, allVals, cols...)
	conflictCols := []string{"id"}
	updateCols := []string{"author_id", "commentable_type", "commentable_id", "kind", "body", "created_at"}
	updateCols, _ = sqlgen.FilterColumns(updateCols, make([]any, len(updateCols)), cols...)
	returning := []string{"id", "author_id", "commentable_type", "commentable_id", "kind", "body", "created_at"}

	query, args := sqlgen.BuildUpsert(dialect, CommentTableName, allCols, allVals, conflictCols, updateCols, returning)
	err = exec.QueryRowContext(ctx, query, args...).Scan(
		&o.ID,
		&o.AuthorID,
		&o.CommentableType,
		&o.CommentableID,
		&o.Kind,
		&o.Body,
		&o.CreatedAt,
	)
	if err != nil {
		return err
	}
	_, err = commentHooks.RunIfEnabled(ctx, exec, sqlgen.AfterUpsert, o)
	return err
}

// Exists checks if a row with the given primary key exists.
func CommentExists(ctx context.Context, exec sqlgen.Executor, id string) (bool, error) {
	return sqlgen.Exists(ctx, exec, dialect, CommentTableName,
		sqlgen.Where("\"id\" = ?", id),
	)
}

// CountComments returns the count of rows matching the query mods.
func CountComments(ctx context.Context, exec sqlgen.Executor, mods ...sqlgen.QueryMod) (int64, error) {
	return sqlgen.Count(ctx, exec, dialect, CommentTableName, mods...)
}

// UpdateAllComments updates all rows matching the given mods.
// set is a map of column name -> new value.
func UpdateAllComments(ctx context.Context, exec sqlgen.Executor, set map[string]any, mods ...sqlgen.QueryMod) (int64, error) {
	q := sqlgen.NewQuery(dialect, CommentTableName, mods...)
	query, args := q.BuildUpdateAll(set)
	result, err := exec.ExecContext(ctx, query, args...)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

// DeleteAllComments deletes all rows matching the given mods.
func DeleteAllComments(ctx context.Context, exec sqlgen.Executor, mods ...sqlgen.QueryMod) (int64, error) {
	q := sqlgen.NewQuery(dialect, CommentTableName, mods...)
	query, args := q.BuildDeleteAll()
	result, err := exec.ExecContext(ctx, query, args...)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

// EachComment executes a query and calls fn for each row. Iteration stops
// early if fn returns an error. Rows are not accumulated in memory.
func EachComment(ctx context.Context, exec sqlgen.Executor, fn func(*Comment) error, mods ...sqlgen.QueryMod) error {
	return sqlgen.Each(ctx, exec, sqlgen.NewQuery(dialect, CommentTableName, mods...), func() *Comment { return &Comment{} }, fn)
}

// CommentCursor returns a cursor for iterating over comments rows one at a time.
func CommentCursor(ctx context.Context, exec sqlgen.Executor, mods ...sqlgen.QueryMod) (*sqlgen.Cursor[*Comment], error) {
	return sqlgen.NewCursor(ctx, exec, sqlgen.NewQuery(dialect, CommentTableName, mods...), func() *Comment { return &Comment{} })
}

// Reload refreshes the Comment from the database using its primary key.
func (o *Comment) Reload(ctx context.Context, exec sqlgen.Executor) error {
	q := sqlgen.NewQuery(dialect, CommentTableName,
		sqlgen.Where("\"id\" = ?", o.ID),
		sqlgen.Limit(1),
	)
	query, args := q.BuildSelect()
	return o.ScanRow(exec.QueryRowContext(ctx, query, args...))
}

// UpdateAll updates all models in the slice with the given column values.
func (s CommentSlice) UpdateAll(ctx context.Context, exec sqlgen.Executor, set map[string]any) (int64, error) {
	if len(s) == 0 {
		return 0, nil
	}
	ids := make([]any, len(s))
	for i, o := range s {
		ids[i] = o.ID
	}
	return UpdateAllComments(ctx, exec, set, sqlgen.WhereIn("\"id\"", ids...))
}

// DeleteAll deletes all models in the slice.
func (s CommentSlice) DeleteAll(ctx context.Context, exec sqlgen.Executor) (int64, error) {
	if len(s) == 0 {
		return 0, nil
	}
	ids := make([]any, len(s))
	for i, o := range s {
		ids[i] = o.ID
	}
	return DeleteAllComments(ctx, exec, sqlgen.WhereIn("\"id\"", ids...))
}

// InsertAll batch-inserts all models in the slice. Each model's columns are
// scanned back via RETURNING, picking up defaults and generated values.
// Hooks are not fired (consistent with UpdateAll/DeleteAll).
func (s CommentSlice) InsertAll(ctx context.Context, exec sqlgen.Executor) error {
	if len(s) == 0 {
		return nil
	}
	cols := []string{"author_id", "commentable_type", "commentable_id", "kind", "body", "created_at"}
	returning := []string{"id", "author_id", "commentable_type", "commentable_id", "kind", "body", "created_at"}

	rows := make([][]any, len(s))
	for i, o := range s {
		rows[i] = []any{o.AuthorID, o.CommentableType, o.CommentableID, o.Kind, o.Body, o.CreatedAt}
	}

	query, args := sqlgen.BuildBatchInsert(dialect, CommentTableName, cols, rows, returning)
	result, err := exec.QueryContext(ctx, query, args...)
	if err != nil {
		return err
	}
	defer result.Close()

	idx := 0
	for result.Next() {
		if err := s[idx].ScanRow(result); err != nil {
			return err
		}
		idx++
	}
	return result.Err()
}
