// Code generated by sqlgen. DO NOT EDIT.

package models

import (
	"testing"
	"time"

	"github.com/davidbyttow/sqlgen"
)

func TestCommentTableName(t *testing.T) {
	if CommentTableName != "comments" {
		t.Errorf("CommentTableName = %q, want %q", CommentTableName, "comments")
	}
}

func TestCommentColumns(t *testing.T) {
	// Verify column constants match expected names.
	cols := map[string]string{
		"ID":              "id",
		"AuthorID":        "author_id",
		"CommentableType": "commentable_type",
		"CommentableID":   "commentable_id",
		"Kind":            "kind",
		"Body":            "body",
		"CreatedAt":       "created_at",
	}
	vals := map[string]string{
		"ID":              CommentColumns.ID,
		"AuthorID":        CommentColumns.AuthorID,
		"CommentableType": CommentColumns.CommentableType,
		"CommentableID":   CommentColumns.CommentableID,
		"Kind":            CommentColumns.Kind,
		"Body":            CommentColumns.Body,
		"CreatedAt":       CommentColumns.CreatedAt,
	}
	for name, want := range cols {
		got := vals[name]
		if got != want {
			t.Errorf("column %s = %q, want %q", name, got, want)
		}
	}
}

func TestCommentFieldCount(t *testing.T) {
	o := &Comment{}
	_ = o
}

func TestCommentQueryBuilder(t *testing.T) {
	q := Comments()
	sql, args := q.BuildSelect()
	if sql == "" {
		t.Error("BuildSelect returned empty SQL")
	}
	if len(args) != 0 {
		t.Errorf("expected 0 args for unfiltered query, got %d", len(args))
	}

	// With a where clause and limit.
	q = Comments(
		sqlgen.Where("1 = ?", 1),
		sqlgen.Limit(10),
	)
	sql, args = q.BuildSelect()
	if sql == "" {
		t.Error("BuildSelect with where returned empty SQL")
	}
	if len(args) == 0 {
		t.Error("expected args for filtered query, got 0")
	}
}

func TestCommentWhereID(t *testing.T) {
	// EQ
	mod := CommentWhere.ID.EQ("")
	q := Comments(mod)
	sql, args := q.BuildSelect()
	if sql == "" {
		t.Error("EQ query is empty")
	}
	if len(args) != 1 {
		t.Errorf("EQ expected 1 arg, got %d", len(args))
	}

	// IN
	mod = CommentWhere.ID.IN("", "")
	q = Comments(mod)
	sql, args = q.BuildSelect()
	if sql == "" {
		t.Error("IN query is empty")
	}
	if len(args) != 2 {
		t.Errorf("IN expected 2 args, got %d", len(args))
	}
}

func TestCommentWhereAuthorID(t *testing.T) {
	// EQ
	mod := CommentWhere.AuthorID.EQ("")
	q := Comments(mod)
	sql, args := q.BuildSelect()
	if sql == "" {
		t.Error("EQ query is empty")
	}
	if len(args) != 1 {
		t.Errorf("EQ expected 1 arg, got %d", len(args))
	}

	// IN
	mod = CommentWhere.AuthorID.IN("", "")
	q = Comments(mod)
	sql, args = q.BuildSelect()
	if sql == "" {
		t.Error("IN query is empty")
	}
	if len(args) != 2 {
		t.Errorf("IN expected 2 args, got %d", len(args))
	}
}

func TestCommentWhereCommentableType(t *testing.T) {
	// EQ
	mod := CommentWhere.CommentableType.EQ("")
	q := Comments(mod)
	sql, args := q.BuildSelect()
	if sql == "" {
		t.Error("EQ query is empty")
	}
	if len(args) != 1 {
		t.Errorf("EQ expected 1 arg, got %d", len(args))
	}

	// IN
	mod = CommentWhere.CommentableType.IN("", "")
	q = Comments(mod)
	sql, args = q.BuildSelect()
	if sql == "" {
		t.Error("IN query is empty")
	}
	if len(args) != 2 {
		t.Errorf("IN expected 2 args, got %d", len(args))
	}
}

func TestCommentWhereCommentableID(t *testing.T) {
	// EQ
	mod := CommentWhere.CommentableID.EQ("")
	q := Comments(mod)
	sql, args := q.BuildSelect()
	if sql == "" {
		t.Error("EQ query is empty")
	}
	if len(args) != 1 {
		t.Errorf("EQ expected 1 arg, got %d", len(args))
	}

	// IN
	mod = CommentWhere.CommentableID.IN("", "")
	q = Comments(mod)
	sql, args = q.BuildSelect()
	if sql == "" {
		t.Error("IN query is empty")
	}
	if len(args) != 2 {
		t.Errorf("IN expected 2 args, got %d", len(args))
	}
}

func TestCommentWhereKind(t *testing.T) {
	// EQ
	mod := CommentWhere.Kind.EQ(CommentKind(""))
	q := Comments(mod)
	sql, args := q.BuildSelect()
	if sql == "" {
		t.Error("EQ query is empty")
	}
	if len(args) != 1 {
		t.Errorf("EQ expected 1 arg, got %d", len(args))
	}

	// IN
	mod = CommentWhere.Kind.IN(CommentKind(""), CommentKind(""))
	q = Comments(mod)
	sql, args = q.BuildSelect()
	if sql == "" {
		t.Error("IN query is empty")
	}
	if len(args) != 2 {
		t.Errorf("IN expected 2 args, got %d", len(args))
	}
}

func TestCommentWhereBody(t *testing.T) {
	// EQ
	mod := CommentWhere.Body.EQ("")
	q := Comments(mod)
	sql, args := q.BuildSelect()
	if sql == "" {
		t.Error("EQ query is empty")
	}
	if len(args) != 1 {
		t.Errorf("EQ expected 1 arg, got %d", len(args))
	}

	// IN
	mod = CommentWhere.Body.IN("", "")
	q = Comments(mod)
	sql, args = q.BuildSelect()
	if sql == "" {
		t.Error("IN query is empty")
	}
	if len(args) != 2 {
		t.Errorf("IN expected 2 args, got %d", len(args))
	}
}

func TestCommentWhereCreatedAt(t *testing.T) {
	// EQ
	mod := CommentWhere.CreatedAt.EQ(time.Time{})
	q := Comments(mod)
	sql, args := q.BuildSelect()
	if sql == "" {
		t.Error("EQ query is empty")
	}
	if len(args) != 1 {
		t.Errorf("EQ expected 1 arg, got %d", len(args))
	}

	// IN
	mod = CommentWhere.CreatedAt.IN(time.Time{}, time.Time{})
	q = Comments(mod)
	sql, args = q.BuildSelect()
	if sql == "" {
		t.Error("IN query is empty")
	}
	if len(args) != 2 {
		t.Errorf("IN expected 2 args, got %d", len(args))
	}
}

func TestCommentBuildUpdateAll(t *testing.T) {
	q := Comments(
		sqlgen.Where("1 = ?", 1),
	)
	sql, args := q.BuildUpdateAll(map[string]any{"id": nil})
	if sql == "" {
		t.Error("BuildUpdateAll returned empty SQL")
	}
	if len(args) < 2 {
		t.Errorf("expected at least 2 args (set + where), got %d", len(args))
	}
}

func TestCommentBuildDeleteAll(t *testing.T) {
	q := Comments(
		sqlgen.Where("1 = ?", 1),
	)
	sql, args := q.BuildDeleteAll()
	if sql == "" {
		t.Error("BuildDeleteAll returned empty SQL")
	}
	if len(args) != 1 {
		t.Errorf("expected 1 arg, got %d", len(args))
	}
}
