// Code generated by sqlgen. DO NOT EDIT.

package models

import (
	"context"

	"github.com/davidbyttow/sqlgen"
	"github.com/davidbyttow/sqlgen/fake"
)

// UserMod is a function that customizes a User before use.
type UserMod func(*User)

// NewUser creates a User with random values for all non-auto-increment fields.
// Pass modifier functions to override specific fields.
func NewUser(mods ...UserMod) *User {
	o := &User{
		ID:        fake.UUID(),
		Email:     fake.String("users_email"),
		Name:      fake.String("users_name"),
		Bio:       sqlgen.NewNull(fake.String("users_bio")),
		Age:       sqlgen.NewNull(fake.Int32()),
		Score:     sqlgen.NewNull(fake.Numeric()),
		IsAdmin:   fake.Bool(),
		Metadata:  sqlgen.NewNull(fake.JSON()),
		CreatedAt: fake.Time(),
	}
	for _, mod := range mods {
		mod(o)
	}
	return o
}

// InsertUser creates a User with random values, applies mods, and inserts it.
func InsertUser(ctx context.Context, exec sqlgen.Executor, mods ...UserMod) (*User, error) {
	o := NewUser(mods...)
	if err := o.Insert(ctx, exec); err != nil {
		return nil, err
	}
	return o, nil
}
