// Code generated by sqlgen. DO NOT EDIT.

package models

import (
	"context"

	"github.com/davidbyttow/sqlgen"
	"github.com/davidbyttow/sqlgen/fake"
)

// PostTagMod is a function that customizes a PostTag before use.
type PostTagMod func(*PostTag)

// NewPostTag creates a PostTag with random values for all non-auto-increment fields.
// Pass modifier functions to override specific fields.
func NewPostTag(mods ...PostTagMod) *PostTag {
	o := &PostTag{
		PostID: fake.UUID(),
		TagID:  fake.Int32(),
	}
	for _, mod := range mods {
		mod(o)
	}
	return o
}

// InsertPostTag creates a PostTag with random values, applies mods, and inserts it.
func InsertPostTag(ctx context.Context, exec sqlgen.Executor, mods ...PostTagMod) (*PostTag, error) {
	o := NewPostTag(mods...)
	if err := o.Insert(ctx, exec); err != nil {
		return nil, err
	}
	return o, nil
}
