// Code generated by sqlgen. DO NOT EDIT.

package models

import (
	"encoding/json"
	"time"

	"github.com/davidbyttow/sqlgen"
)

// UserWhere provides type-safe where clause builders for each column.
var UserWhere = struct {
	ID        UserIDFilter
	Email     UserEmailFilter
	Name      UserNameFilter
	Bio       UserBioFilter
	Age       UserAgeFilter
	Score     UserScoreFilter
	IsAdmin   UserIsAdminFilter
	Metadata  UserMetadataFilter
	CreatedAt UserCreatedAtFilter
}{
	ID:        UserIDFilter{col: "id"},
	Email:     UserEmailFilter{col: "email"},
	Name:      UserNameFilter{col: "name"},
	Bio:       UserBioFilter{col: "bio"},
	Age:       UserAgeFilter{col: "age"},
	Score:     UserScoreFilter{col: "score"},
	IsAdmin:   UserIsAdminFilter{col: "is_admin"},
	Metadata:  UserMetadataFilter{col: "metadata"},
	CreatedAt: UserCreatedAtFilter{col: "created_at"},
}

// UserIDFilter provides where clauses for the id column.
type UserIDFilter struct {
	col string
}

func (f UserIDFilter) EQ(val string) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" = ?", val)
}

func (f UserIDFilter) NEQ(val string) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" != ?", val)
}

func (f UserIDFilter) LT(val string) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" < ?", val)
}

func (f UserIDFilter) LTE(val string) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" <= ?", val)
}

func (f UserIDFilter) GT(val string) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" > ?", val)
}

func (f UserIDFilter) GTE(val string) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" >= ?", val)
}

func (f UserIDFilter) IN(vals ...string) sqlgen.QueryMod {
	args := make([]any, len(vals))
	for i, v := range vals {
		args[i] = v
	}
	placeholders := make([]byte, 0, len(vals)*2)
	for i := range vals {
		if i > 0 {
			placeholders = append(placeholders, ',', ' ')
		}
		placeholders = append(placeholders, '?')
	}
	return sqlgen.Where("\""+f.col+"\" IN ("+string(placeholders)+")", args...)
}

// UserEmailFilter provides where clauses for the email column.
type UserEmailFilter struct {
	col string
}

func (f UserEmailFilter) EQ(val string) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" = ?", val)
}

func (f UserEmailFilter) NEQ(val string) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" != ?", val)
}

func (f UserEmailFilter) LT(val string) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" < ?", val)
}

func (f UserEmailFilter) LTE(val string) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" <= ?", val)
}

func (f UserEmailFilter) GT(val string) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" > ?", val)
}

func (f UserEmailFilter) GTE(val string) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" >= ?", val)
}

func (f UserEmailFilter) IN(vals ...string) sqlgen.QueryMod {
	args := make([]any, len(vals))
	for i, v := range vals {
		args[i] = v
	}
	placeholders := make([]byte, 0, len(vals)*2)
	for i := range vals {
		if i > 0 {
			placeholders = append(placeholders, ',', ' ')
		}
		placeholders = append(placeholders, '?')
	}
	return sqlgen.Where("\""+f.col+"\" IN ("+string(placeholders)+")", args...)
}

// UserNameFilter provides where clauses for the name column.
type UserNameFilter struct {
	col string
}

func (f UserNameFilter) EQ(val string) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" = ?", val)
}

func (f UserNameFilter) NEQ(val string) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" != ?", val)
}

func (f UserNameFilter) LT(val string) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" < ?", val)
}

func (f UserNameFilter) LTE(val string) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" <= ?", val)
}

func (f UserNameFilter) GT(val string) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" > ?", val)
}

func (f UserNameFilter) GTE(val string) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" >= ?", val)
}

func (f UserNameFilter) IN(vals ...string) sqlgen.QueryMod {
	args := make([]any, len(vals))
	for i, v := range vals {
		args[i] = v
	}
	placeholders := make([]byte, 0, len(vals)*2)
	for i := range vals {
		if i > 0 {
			placeholders = append(placeholders, ',', ' ')
		}
		placeholders = append(placeholders, '?')
	}
	return sqlgen.Where("\""+f.col+"\" IN ("+string(placeholders)+")", args...)
}

// UserBioFilter provides where clauses for the bio column.
type UserBioFilter struct {
	col string
}

func (f UserBioFilter) EQ(val sqlgen.Null[string]) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" = ?", val)
}

func (f UserBioFilter) NEQ(val sqlgen.Null[string]) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" != ?", val)
}

func (f UserBioFilter) LT(val sqlgen.Null[string]) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" < ?", val)
}

func (f UserBioFilter) LTE(val sqlgen.Null[string]) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" <= ?", val)
}

func (f UserBioFilter) GT(val sqlgen.Null[string]) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" > ?", val)
}

func (f UserBioFilter) GTE(val sqlgen.Null[string]) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" >= ?", val)
}

func (f UserBioFilter) IN(vals ...sqlgen.Null[string]) sqlgen.QueryMod {
	args := make([]any, len(vals))
	for i, v := range vals {
		args[i] = v
	}
	placeholders := make([]byte, 0, len(vals)*2)
	for i := range vals {
		if i > 0 {
			placeholders = append(placeholders, ',', ' ')
		}
		placeholders = append(placeholders, '?')
	}
	return sqlgen.Where("\""+f.col+"\" IN ("+string(placeholders)+")", args...)
}

func (f UserBioFilter) IsNull() sqlgen.QueryMod {
	return sqlgen.Where("\"" + f.col + "\" IS NULL")
}

func (f UserBioFilter) IsNotNull() sqlgen.QueryMod {
	return sqlgen.Where("\"" + f.col + "\" IS NOT NULL")
}

// UserAgeFilter provides where clauses for the age column.
type UserAgeFilter struct {
	col string
}

func (f UserAgeFilter) EQ(val sqlgen.Null[int32]) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" = ?", val)
}

func (f UserAgeFilter) NEQ(val sqlgen.Null[int32]) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" != ?", val)
}

func (f UserAgeFilter) LT(val sqlgen.Null[int32]) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" < ?", val)
}

func (f UserAgeFilter) LTE(val sqlgen.Null[int32]) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" <= ?", val)
}

func (f UserAgeFilter) GT(val sqlgen.Null[int32]) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" > ?", val)
}

func (f UserAgeFilter) GTE(val sqlgen.Null[int32]) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" >= ?", val)
}

func (f UserAgeFilter) IN(vals ...sqlgen.Null[int32]) sqlgen.QueryMod {
	args := make([]any, len(vals))
	for i, v := range vals {
		args[i] = v
	}
	placeholders := make([]byte, 0, len(vals)*2)
	for i := range vals {
		if i > 0 {
			placeholders = append(placeholders, ',', ' ')
		}
		placeholders = append(placeholders, '?')
	}
	return sqlgen.Where("\""+f.col+"\" IN ("+string(placeholders)+")", args...)
}

func (f UserAgeFilter) IsNull() sqlgen.QueryMod {
	return sqlgen.Where("\"" + f.col + "\" IS NULL")
}

func (f UserAgeFilter) IsNotNull() sqlgen.QueryMod {
	return sqlgen.Where("\"" + f.col + "\" IS NOT NULL")
}

// UserScoreFilter provides where clauses for the score column.
type UserScoreFilter struct {
	col string
}

func (f UserScoreFilter) EQ(val sqlgen.Null[string]) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" = ?", val)
}

func (f UserScoreFilter) NEQ(val sqlgen.Null[string]) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" != ?", val)
}

func (f UserScoreFilter) LT(val sqlgen.Null[string]) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" < ?", val)
}

func (f UserScoreFilter) LTE(val sqlgen.Null[string]) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" <= ?", val)
}

func (f UserScoreFilter) GT(val sqlgen.Null[string]) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" > ?", val)
}

func (f UserScoreFilter) GTE(val sqlgen.Null[string]) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" >= ?", val)
}

func (f UserScoreFilter) IN(vals ...sqlgen.Null[string]) sqlgen.QueryMod {
	args := make([]any, len(vals))
	for i, v := range vals {
		args[i] = v
	}
	placeholders := make([]byte, 0, len(vals)*2)
	for i := range vals {
		if i > 0 {
			placeholders = append(placeholders, ',', ' ')
		}
		placeholders = append(placeholders, '?')
	}
	return sqlgen.Where("\""+f.col+"\" IN ("+string(placeholders)+")", args...)
}

func (f UserScoreFilter) IsNull() sqlgen.QueryMod {
	return sqlgen.Where("\"" + f.col + "\" IS NULL")
}

func (f UserScoreFilter) IsNotNull() sqlgen.QueryMod {
	return sqlgen.Where("\"" + f.col + "\" IS NOT NULL")
}

// UserIsAdminFilter provides where clauses for the is_admin column.
type UserIsAdminFilter struct {
	col string
}

func (f UserIsAdminFilter) EQ(val bool) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" = ?", val)
}

func (f UserIsAdminFilter) NEQ(val bool) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" != ?", val)
}

func (f UserIsAdminFilter) LT(val bool) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" < ?", val)
}

func (f UserIsAdminFilter) LTE(val bool) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" <= ?", val)
}

func (f UserIsAdminFilter) GT(val bool) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" > ?", val)
}

func (f UserIsAdminFilter) GTE(val bool) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" >= ?", val)
}

func (f UserIsAdminFilter) IN(vals ...bool) sqlgen.QueryMod {
	args := make([]any, len(vals))
	for i, v := range vals {
		args[i] = v
	}
	placeholders := make([]byte, 0, len(vals)*2)
	for i := range vals {
		if i > 0 {
			placeholders = append(placeholders, ',', ' ')
		}
		placeholders = append(placeholders, '?')
	}
	return sqlgen.Where("\""+f.col+"\" IN ("+string(placeholders)+")", args...)
}

// UserMetadataFilter provides where clauses for the metadata column.
type UserMetadataFilter struct {
	col string
}

func (f UserMetadataFilter) EQ(val sqlgen.Null[json.RawMessage]) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" = ?", val)
}

func (f UserMetadataFilter) NEQ(val sqlgen.Null[json.RawMessage]) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" != ?", val)
}

func (f UserMetadataFilter) LT(val sqlgen.Null[json.RawMessage]) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" < ?", val)
}

func (f UserMetadataFilter) LTE(val sqlgen.Null[json.RawMessage]) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" <= ?", val)
}

func (f UserMetadataFilter) GT(val sqlgen.Null[json.RawMessage]) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" > ?", val)
}

func (f UserMetadataFilter) GTE(val sqlgen.Null[json.RawMessage]) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" >= ?", val)
}

func (f UserMetadataFilter) IN(vals ...sqlgen.Null[json.RawMessage]) sqlgen.QueryMod {
	args := make([]any, len(vals))
	for i, v := range vals {
		args[i] = v
	}
	placeholders := make([]byte, 0, len(vals)*2)
	for i := range vals {
		if i > 0 {
			placeholders = append(placeholders, ',', ' ')
		}
		placeholders = append(placeholders, '?')
	}
	return sqlgen.Where("\""+f.col+"\" IN ("+string(placeholders)+")", args...)
}

func (f UserMetadataFilter) IsNull() sqlgen.QueryMod {
	return sqlgen.Where("\"" + f.col + "\" IS NULL")
}

func (f UserMetadataFilter) IsNotNull() sqlgen.QueryMod {
	return sqlgen.Where("\"" + f.col + "\" IS NOT NULL")
}

// UserCreatedAtFilter provides where clauses for the created_at column.
type UserCreatedAtFilter struct {
	col string
}

func (f UserCreatedAtFilter) EQ(val time.Time) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" = ?", val)
}

func (f UserCreatedAtFilter) NEQ(val time.Time) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" != ?", val)
}

func (f UserCreatedAtFilter) LT(val time.Time) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" < ?", val)
}

func (f UserCreatedAtFilter) LTE(val time.Time) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" <= ?", val)
}

func (f UserCreatedAtFilter) GT(val time.Time) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" > ?", val)
}

func (f UserCreatedAtFilter) GTE(val time.Time) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" >= ?", val)
}

func (f UserCreatedAtFilter) IN(vals ...time.Time) sqlgen.QueryMod {
	args := make([]any, len(vals))
	for i, v := range vals {
		args[i] = v
	}
	placeholders := make([]byte, 0, len(vals)*2)
	for i := range vals {
		if i > 0 {
			placeholders = append(placeholders, ',', ' ')
		}
		placeholders = append(placeholders, '?')
	}
	return sqlgen.Where("\""+f.col+"\" IN ("+string(placeholders)+")", args...)
}
