// Code generated by sqlgen. DO NOT EDIT.

package models

import (
	"context"

	"github.com/davidbyttow/sqlgen"
	"github.com/davidbyttow/sqlgen/fake"
)

// TagMod is a function that customizes a Tag before use.
type TagMod func(*Tag)

// NewTag creates a Tag with random values for all non-auto-increment fields.
// Pass modifier functions to override specific fields.
func NewTag(mods ...TagMod) *Tag {
	o := &Tag{
		Name: fake.String("tags_name"),
	}
	for _, mod := range mods {
		mod(o)
	}
	return o
}

// InsertTag creates a Tag with random values, applies mods, and inserts it.
func InsertTag(ctx context.Context, exec sqlgen.Executor, mods ...TagMod) (*Tag, error) {
	o := NewTag(mods...)
	if err := o.Insert(ctx, exec); err != nil {
		return nil, err
	}
	return o, nil
}
