// Code generated by sqlgen. DO NOT EDIT.

package models

import (
	"database/sql/driver"
	"testing"
)

func TestPostStatusValues(t *testing.T) {
	vals := AllPostStatusValues()
	if len(vals) != 3 {
		t.Errorf("AllPostStatusValues() returned %d values, want %d", len(vals), 3)
	}

	// Each value should be valid.
	for _, v := range vals {
		if !v.IsValid() {
			t.Errorf("value %q should be valid", v)
		}
	}
}

func TestPostStatusIsValid(t *testing.T) {
	// Valid values.
	if !PostStatusDraft.IsValid() {
		t.Errorf("%q should be valid", PostStatusDraft)
	}
	if !PostStatusPublished.IsValid() {
		t.Errorf("%q should be valid", PostStatusPublished)
	}
	if !PostStatusArchived.IsValid() {
		t.Errorf("%q should be valid", PostStatusArchived)
	}

	// Invalid value.
	if PostStatus("bogus_value_xyz").IsValid() {
		t.Error("bogus value should not be valid")
	}
}

func TestPostStatusScanValue(t *testing.T) {
	{
		var e PostStatus
		if err := e.Scan("draft"); err != nil {
			t.Errorf("Scan(%q): %v", "draft", err)
		}
		if e != PostStatusDraft {
			t.Errorf("after Scan(%q), got %q", "draft", e)
		}
		v, err := e.Value()
		if err != nil {
			t.Errorf("Value() for %q: %v", "draft", err)
		}
		if v != driver.Value("draft") {
			t.Errorf("Value() = %v, want %q", v, "draft")
		}
	}
	{
		var e PostStatus
		if err := e.Scan("published"); err != nil {
			t.Errorf("Scan(%q): %v", "published", err)
		}
		if e != PostStatusPublished {
			t.Errorf("after Scan(%q), got %q", "published", e)
		}
		v, err := e.Value()
		if err != nil {
			t.Errorf("Value() for %q: %v", "published", err)
		}
		if v != driver.Value("published") {
			t.Errorf("Value() = %v, want %q", v, "published")
		}
	}
	{
		var e PostStatus
		if err := e.Scan("archived"); err != nil {
			t.Errorf("Scan(%q): %v", "archived", err)
		}
		if e != PostStatusArchived {
			t.Errorf("after Scan(%q), got %q", "archived", e)
		}
		v, err := e.Value()
		if err != nil {
			t.Errorf("Value() for %q: %v", "archived", err)
		}
		if v != driver.Value("archived") {
			t.Errorf("Value() = %v, want %q", v, "archived")
		}
	}
}

func TestPostStatusScanBytes(t *testing.T) {
	var e PostStatus
	if err := e.Scan([]byte("draft")); err != nil {
		t.Errorf("Scan([]byte): %v", err)
	}
	if e != PostStatusDraft {
		t.Errorf("after Scan([]byte), got %q", e)
	}
}

func TestPostStatusScanInvalid(t *testing.T) {
	var e PostStatus
	if err := e.Scan("not_a_real_value_xyz"); err == nil {
		t.Error("expected error scanning invalid value")
	}
	if err := e.Scan(nil); err == nil {
		t.Error("expected error scanning nil")
	}
	if err := e.Scan(123); err == nil {
		t.Error("expected error scanning int")
	}
}

func TestPostStatusString(t *testing.T) {
	if PostStatusDraft.String() != "draft" {
		t.Errorf("String() = %q, want %q", PostStatusDraft.String(), "draft")
	}
	if PostStatusPublished.String() != "published" {
		t.Errorf("String() = %q, want %q", PostStatusPublished.String(), "published")
	}
	if PostStatusArchived.String() != "archived" {
		t.Errorf("String() = %q, want %q", PostStatusArchived.String(), "archived")
	}
}
