// Code generated by sqlgen. DO NOT EDIT.

package models

import (
	"testing"

	"github.com/davidbyttow/sqlgen"
)

func TestCategoryTableName(t *testing.T) {
	if CategoryTableName != "categories" {
		t.Errorf("CategoryTableName = %q, want %q", CategoryTableName, "categories")
	}
}

func TestCategoryColumns(t *testing.T) {
	// Verify column constants match expected names.
	cols := map[string]string{
		"ID":       "id",
		"Name":     "name",
		"ParentID": "parent_id",
	}
	vals := map[string]string{
		"ID":       CategoryColumns.ID,
		"Name":     CategoryColumns.Name,
		"ParentID": CategoryColumns.ParentID,
	}
	for name, want := range cols {
		got := vals[name]
		if got != want {
			t.Errorf("column %s = %q, want %q", name, got, want)
		}
	}
}

func TestCategoryFieldCount(t *testing.T) {
	o := &Category{}
	_ = o
}

func TestCategoryQueryBuilder(t *testing.T) {
	q := Categories()
	sql, args := q.BuildSelect()
	if sql == "" {
		t.Error("BuildSelect returned empty SQL")
	}
	if len(args) != 0 {
		t.Errorf("expected 0 args for unfiltered query, got %d", len(args))
	}

	// With a where clause and limit.
	q = Categories(
		sqlgen.Where("1 = ?", 1),
		sqlgen.Limit(10),
	)
	sql, args = q.BuildSelect()
	if sql == "" {
		t.Error("BuildSelect with where returned empty SQL")
	}
	if len(args) == 0 {
		t.Error("expected args for filtered query, got 0")
	}
}

func TestCategoryWhereID(t *testing.T) {
	// EQ
	mod := CategoryWhere.ID.EQ(0)
	q := Categories(mod)
	sql, args := q.BuildSelect()
	if sql == "" {
		t.Error("EQ query is empty")
	}
	if len(args) != 1 {
		t.Errorf("EQ expected 1 arg, got %d", len(args))
	}

	// IN
	mod = CategoryWhere.ID.IN(0, 0)
	q = Categories(mod)
	sql, args = q.BuildSelect()
	if sql == "" {
		t.Error("IN query is empty")
	}
	if len(args) != 2 {
		t.Errorf("IN expected 2 args, got %d", len(args))
	}
}

func TestCategoryWhereName(t *testing.T) {
	// EQ
	mod := CategoryWhere.Name.EQ("")
	q := Categories(mod)
	sql, args := q.BuildSelect()
	if sql == "" {
		t.Error("EQ query is empty")
	}
	if len(args) != 1 {
		t.Errorf("EQ expected 1 arg, got %d", len(args))
	}

	// IN
	mod = CategoryWhere.Name.IN("", "")
	q = Categories(mod)
	sql, args = q.BuildSelect()
	if sql == "" {
		t.Error("IN query is empty")
	}
	if len(args) != 2 {
		t.Errorf("IN expected 2 args, got %d", len(args))
	}
}

func TestCategoryWhereParentID(t *testing.T) {
	// EQ
	mod := CategoryWhere.ParentID.EQ(sqlgen.Null[int32]{})
	q := Categories(mod)
	sql, args := q.BuildSelect()
	if sql == "" {
		t.Error("EQ query is empty")
	}
	if len(args) != 1 {
		t.Errorf("EQ expected 1 arg, got %d", len(args))
	}

	// IN
	mod = CategoryWhere.ParentID.IN(sqlgen.Null[int32]{}, sqlgen.Null[int32]{})
	q = Categories(mod)
	sql, args = q.BuildSelect()
	if sql == "" {
		t.Error("IN query is empty")
	}
	if len(args) != 2 {
		t.Errorf("IN expected 2 args, got %d", len(args))
	}

	// IsNull / IsNotNull
	q = Categories(CategoryWhere.ParentID.IsNull())
	sql, _ = q.BuildSelect()
	if sql == "" {
		t.Error("IsNull query is empty")
	}
	q = Categories(CategoryWhere.ParentID.IsNotNull())
	sql, _ = q.BuildSelect()
	if sql == "" {
		t.Error("IsNotNull query is empty")
	}
}

func TestCategoryBuildUpdateAll(t *testing.T) {
	q := Categories(
		sqlgen.Where("1 = ?", 1),
	)
	sql, args := q.BuildUpdateAll(map[string]any{"id": nil})
	if sql == "" {
		t.Error("BuildUpdateAll returned empty SQL")
	}
	if len(args) < 2 {
		t.Errorf("expected at least 2 args (set + where), got %d", len(args))
	}
}

func TestCategoryBuildDeleteAll(t *testing.T) {
	q := Categories(
		sqlgen.Where("1 = ?", 1),
	)
	sql, args := q.BuildDeleteAll()
	if sql == "" {
		t.Error("BuildDeleteAll returned empty SQL")
	}
	if len(args) != 1 {
		t.Errorf("expected 1 arg, got %d", len(args))
	}
}
