// Code generated by sqlgen. DO NOT EDIT.

package models

import "github.com/davidbyttow/sqlgen"

// ProfileWhere provides type-safe where clause builders for each column.
var ProfileWhere = struct {
	ID        ProfileIDFilter
	UserID    ProfileUserIDFilter
	AvatarURL ProfileAvatarURLFilter
	Website   ProfileWebsiteFilter
}{
	ID:        ProfileIDFilter{col: "id"},
	UserID:    ProfileUserIDFilter{col: "user_id"},
	AvatarURL: ProfileAvatarURLFilter{col: "avatar_url"},
	Website:   ProfileWebsiteFilter{col: "website"},
}

// ProfileIDFilter provides where clauses for the id column.
type ProfileIDFilter struct {
	col string
}

func (f ProfileIDFilter) EQ(val string) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" = ?", val)
}

func (f ProfileIDFilter) NEQ(val string) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" != ?", val)
}

func (f ProfileIDFilter) LT(val string) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" < ?", val)
}

func (f ProfileIDFilter) LTE(val string) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" <= ?", val)
}

func (f ProfileIDFilter) GT(val string) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" > ?", val)
}

func (f ProfileIDFilter) GTE(val string) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" >= ?", val)
}

func (f ProfileIDFilter) IN(vals ...string) sqlgen.QueryMod {
	args := make([]any, len(vals))
	for i, v := range vals {
		args[i] = v
	}
	placeholders := make([]byte, 0, len(vals)*2)
	for i := range vals {
		if i > 0 {
			placeholders = append(placeholders, ',', ' ')
		}
		placeholders = append(placeholders, '?')
	}
	return sqlgen.Where("\""+f.col+"\" IN ("+string(placeholders)+")", args...)
}

// ProfileUserIDFilter provides where clauses for the user_id column.
type ProfileUserIDFilter struct {
	col string
}

func (f ProfileUserIDFilter) EQ(val string) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" = ?", val)
}

func (f ProfileUserIDFilter) NEQ(val string) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" != ?", val)
}

func (f ProfileUserIDFilter) LT(val string) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" < ?", val)
}

func (f ProfileUserIDFilter) LTE(val string) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" <= ?", val)
}

func (f ProfileUserIDFilter) GT(val string) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" > ?", val)
}

func (f ProfileUserIDFilter) GTE(val string) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" >= ?", val)
}

func (f ProfileUserIDFilter) IN(vals ...string) sqlgen.QueryMod {
	args := make([]any, len(vals))
	for i, v := range vals {
		args[i] = v
	}
	placeholders := make([]byte, 0, len(vals)*2)
	for i := range vals {
		if i > 0 {
			placeholders = append(placeholders, ',', ' ')
		}
		placeholders = append(placeholders, '?')
	}
	return sqlgen.Where("\""+f.col+"\" IN ("+string(placeholders)+")", args...)
}

// ProfileAvatarURLFilter provides where clauses for the avatar_url column.
type ProfileAvatarURLFilter struct {
	col string
}

func (f ProfileAvatarURLFilter) EQ(val sqlgen.Null[string]) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" = ?", val)
}

func (f ProfileAvatarURLFilter) NEQ(val sqlgen.Null[string]) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" != ?", val)
}

func (f ProfileAvatarURLFilter) LT(val sqlgen.Null[string]) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" < ?", val)
}

func (f ProfileAvatarURLFilter) LTE(val sqlgen.Null[string]) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" <= ?", val)
}

func (f ProfileAvatarURLFilter) GT(val sqlgen.Null[string]) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" > ?", val)
}

func (f ProfileAvatarURLFilter) GTE(val sqlgen.Null[string]) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" >= ?", val)
}

func (f ProfileAvatarURLFilter) IN(vals ...sqlgen.Null[string]) sqlgen.QueryMod {
	args := make([]any, len(vals))
	for i, v := range vals {
		args[i] = v
	}
	placeholders := make([]byte, 0, len(vals)*2)
	for i := range vals {
		if i > 0 {
			placeholders = append(placeholders, ',', ' ')
		}
		placeholders = append(placeholders, '?')
	}
	return sqlgen.Where("\""+f.col+"\" IN ("+string(placeholders)+")", args...)
}

func (f ProfileAvatarURLFilter) IsNull() sqlgen.QueryMod {
	return sqlgen.Where("\"" + f.col + "\" IS NULL")
}

func (f ProfileAvatarURLFilter) IsNotNull() sqlgen.QueryMod {
	return sqlgen.Where("\"" + f.col + "\" IS NOT NULL")
}

// ProfileWebsiteFilter provides where clauses for the website column.
type ProfileWebsiteFilter struct {
	col string
}

func (f ProfileWebsiteFilter) EQ(val sqlgen.Null[string]) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" = ?", val)
}

func (f ProfileWebsiteFilter) NEQ(val sqlgen.Null[string]) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" != ?", val)
}

func (f ProfileWebsiteFilter) LT(val sqlgen.Null[string]) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" < ?", val)
}

func (f ProfileWebsiteFilter) LTE(val sqlgen.Null[string]) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" <= ?", val)
}

func (f ProfileWebsiteFilter) GT(val sqlgen.Null[string]) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" > ?", val)
}

func (f ProfileWebsiteFilter) GTE(val sqlgen.Null[string]) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" >= ?", val)
}

func (f ProfileWebsiteFilter) IN(vals ...sqlgen.Null[string]) sqlgen.QueryMod {
	args := make([]any, len(vals))
	for i, v := range vals {
		args[i] = v
	}
	placeholders := make([]byte, 0, len(vals)*2)
	for i := range vals {
		if i > 0 {
			placeholders = append(placeholders, ',', ' ')
		}
		placeholders = append(placeholders, '?')
	}
	return sqlgen.Where("\""+f.col+"\" IN ("+string(placeholders)+")", args...)
}

func (f ProfileWebsiteFilter) IsNull() sqlgen.QueryMod {
	return sqlgen.Where("\"" + f.col + "\" IS NULL")
}

func (f ProfileWebsiteFilter) IsNotNull() sqlgen.QueryMod {
	return sqlgen.Where("\"" + f.col + "\" IS NOT NULL")
}
