// Code generated by sqlgen. DO NOT EDIT.

package models

import (
	"context"

	"github.com/davidbyttow/sqlgen"
)

// SetUser sets the User relationship by updating the FK column.
func (o *Profile) SetUser(ctx context.Context, exec sqlgen.Executor, related *User) error {
	o.UserID = related.ID
	query := "UPDATE " + dialect.QuoteIdent(ProfileTableName) +
		" SET " + dialect.QuoteIdent("user_id") + " = " + dialect.Placeholder(1) +
		" WHERE " + dialect.QuoteIdent("id") + " = " + dialect.Placeholder(2)
	_, err := exec.ExecContext(ctx, query, o.UserID, o.ID)
	if err != nil {
		return err
	}
	if o.R == nil {
		o.R = &ProfileRels{}
	}
	o.R.User = related
	return nil
}
