// Code generated by sqlgen. DO NOT EDIT.

package models

import (
	"context"
	"fmt"

	"github.com/davidbyttow/sqlgen"
)

// profileLoaders maps relationship names to their loader functions.
var profileLoaders = map[string]sqlgen.LoadFunc{}

func init() {
	profileLoaders["User"] = loadProfileUser
}

// LoadRelations eagerly loads the specified relationships for a slice of Profile.
func (s ProfileSlice) LoadRelations(ctx context.Context, exec sqlgen.Executor, loads ...*sqlgen.EagerLoadRequest) error {
	for _, load := range loads {
		fn, ok := profileLoaders[load.Name]
		if !ok {
			return fmt.Errorf("unknown relationship %q on Profile", load.Name)
		}
		if err := fn(ctx, exec, dialect, s, loads); err != nil {
			return fmt.Errorf("loading %s: %w", load.Name, err)
		}
	}
	return nil
}

// profileLoadMods extracts query mods for the named relationship from the load requests.
func profileLoadMods(loads []*sqlgen.EagerLoadRequest, name string) []sqlgen.QueryMod {
	for _, l := range loads {
		if l.Name == name {
			return l.Mods
		}
	}
	return nil
}

func loadProfileUser(ctx context.Context, exec sqlgen.Executor, d sqlgen.Dialect, parentModels any, loads []*sqlgen.EagerLoadRequest) error {
	models := parentModels.(ProfileSlice)
	if len(models) == 0 {
		return nil
	}

	// Collect unique FK values.
	seen := make(map[string]bool)
	var ids []any
	for _, m := range models {
		key := fmt.Sprint(m.UserID)
		if !seen[key] {
			seen[key] = true
			ids = append(ids, m.UserID)
		}
	}

	mods := profileLoadMods(loads, "User")
	rows, err := sqlgen.LoadMany(ctx, exec, d, UserTableName, "id", ids, mods...)
	if err != nil {
		return err
	}
	if rows == nil {
		return nil
	}
	defer rows.Close()

	resultMap := make(map[string]*User)
	for rows.Next() {
		o := &User{}
		if err := o.ScanRow(rows); err != nil {
			return err
		}
		resultMap[fmt.Sprint(o.ID)] = o
	}
	if err := rows.Err(); err != nil {
		return err
	}

	for _, m := range models {
		o := resultMap[fmt.Sprint(m.UserID)]
		if o != nil {
			if m.R == nil {
				m.R = &ProfileRels{}
			}
			m.R.User = o
		}
	}
	return nil
}
