// Code generated by sqlgen. DO NOT EDIT.

package models

import (
	"testing"

	"github.com/davidbyttow/sqlgen"
)

func TestTagTableName(t *testing.T) {
	if TagTableName != "tags" {
		t.Errorf("TagTableName = %q, want %q", TagTableName, "tags")
	}
}

func TestTagColumns(t *testing.T) {
	// Verify column constants match expected names.
	cols := map[string]string{
		"ID":   "id",
		"Name": "name",
	}
	vals := map[string]string{
		"ID":   TagColumns.ID,
		"Name": TagColumns.Name,
	}
	for name, want := range cols {
		got := vals[name]
		if got != want {
			t.Errorf("column %s = %q, want %q", name, got, want)
		}
	}
}

func TestTagFieldCount(t *testing.T) {
	o := &Tag{}
	_ = o
}

func TestTagQueryBuilder(t *testing.T) {
	q := Tags()
	sql, args := q.BuildSelect()
	if sql == "" {
		t.Error("BuildSelect returned empty SQL")
	}
	if len(args) != 0 {
		t.Errorf("expected 0 args for unfiltered query, got %d", len(args))
	}

	// With a where clause and limit.
	q = Tags(
		sqlgen.Where("1 = ?", 1),
		sqlgen.Limit(10),
	)
	sql, args = q.BuildSelect()
	if sql == "" {
		t.Error("BuildSelect with where returned empty SQL")
	}
	if len(args) == 0 {
		t.Error("expected args for filtered query, got 0")
	}
}

func TestTagWhereID(t *testing.T) {
	// EQ
	mod := TagWhere.ID.EQ(0)
	q := Tags(mod)
	sql, args := q.BuildSelect()
	if sql == "" {
		t.Error("EQ query is empty")
	}
	if len(args) != 1 {
		t.Errorf("EQ expected 1 arg, got %d", len(args))
	}

	// IN
	mod = TagWhere.ID.IN(0, 0)
	q = Tags(mod)
	sql, args = q.BuildSelect()
	if sql == "" {
		t.Error("IN query is empty")
	}
	if len(args) != 2 {
		t.Errorf("IN expected 2 args, got %d", len(args))
	}
}

func TestTagWhereName(t *testing.T) {
	// EQ
	mod := TagWhere.Name.EQ("")
	q := Tags(mod)
	sql, args := q.BuildSelect()
	if sql == "" {
		t.Error("EQ query is empty")
	}
	if len(args) != 1 {
		t.Errorf("EQ expected 1 arg, got %d", len(args))
	}

	// IN
	mod = TagWhere.Name.IN("", "")
	q = Tags(mod)
	sql, args = q.BuildSelect()
	if sql == "" {
		t.Error("IN query is empty")
	}
	if len(args) != 2 {
		t.Errorf("IN expected 2 args, got %d", len(args))
	}
}

func TestTagBuildUpdateAll(t *testing.T) {
	q := Tags(
		sqlgen.Where("1 = ?", 1),
	)
	sql, args := q.BuildUpdateAll(map[string]any{"id": nil})
	if sql == "" {
		t.Error("BuildUpdateAll returned empty SQL")
	}
	if len(args) < 2 {
		t.Errorf("expected at least 2 args (set + where), got %d", len(args))
	}
}

func TestTagBuildDeleteAll(t *testing.T) {
	q := Tags(
		sqlgen.Where("1 = ?", 1),
	)
	sql, args := q.BuildDeleteAll()
	if sql == "" {
		t.Error("BuildDeleteAll returned empty SQL")
	}
	if len(args) != 1 {
		t.Errorf("expected 1 arg, got %d", len(args))
	}
}
