// Code generated by sqlgen. DO NOT EDIT.

package models

import (
	"time"

	"github.com/davidbyttow/sqlgen"
)

// CommentWhere provides type-safe where clause builders for each column.
var CommentWhere = struct {
	ID              CommentIDFilter
	AuthorID        CommentAuthorIDFilter
	CommentableType CommentCommentableTypeFilter
	CommentableID   CommentCommentableIDFilter
	Kind            CommentKindFilter
	Body            CommentBodyFilter
	CreatedAt       CommentCreatedAtFilter
}{
	ID:              CommentIDFilter{col: "id"},
	AuthorID:        CommentAuthorIDFilter{col: "author_id"},
	CommentableType: CommentCommentableTypeFilter{col: "commentable_type"},
	CommentableID:   CommentCommentableIDFilter{col: "commentable_id"},
	Kind:            CommentKindFilter{col: "kind"},
	Body:            CommentBodyFilter{col: "body"},
	CreatedAt:       CommentCreatedAtFilter{col: "created_at"},
}

// CommentIDFilter provides where clauses for the id column.
type CommentIDFilter struct {
	col string
}

func (f CommentIDFilter) EQ(val string) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" = ?", val)
}

func (f CommentIDFilter) NEQ(val string) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" != ?", val)
}

func (f CommentIDFilter) LT(val string) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" < ?", val)
}

func (f CommentIDFilter) LTE(val string) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" <= ?", val)
}

func (f CommentIDFilter) GT(val string) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" > ?", val)
}

func (f CommentIDFilter) GTE(val string) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" >= ?", val)
}

func (f CommentIDFilter) IN(vals ...string) sqlgen.QueryMod {
	args := make([]any, len(vals))
	for i, v := range vals {
		args[i] = v
	}
	placeholders := make([]byte, 0, len(vals)*2)
	for i := range vals {
		if i > 0 {
			placeholders = append(placeholders, ',', ' ')
		}
		placeholders = append(placeholders, '?')
	}
	return sqlgen.Where("\""+f.col+"\" IN ("+string(placeholders)+")", args...)
}

// CommentAuthorIDFilter provides where clauses for the author_id column.
type CommentAuthorIDFilter struct {
	col string
}

func (f CommentAuthorIDFilter) EQ(val string) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" = ?", val)
}

func (f CommentAuthorIDFilter) NEQ(val string) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" != ?", val)
}

func (f CommentAuthorIDFilter) LT(val string) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" < ?", val)
}

func (f CommentAuthorIDFilter) LTE(val string) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" <= ?", val)
}

func (f CommentAuthorIDFilter) GT(val string) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" > ?", val)
}

func (f CommentAuthorIDFilter) GTE(val string) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" >= ?", val)
}

func (f CommentAuthorIDFilter) IN(vals ...string) sqlgen.QueryMod {
	args := make([]any, len(vals))
	for i, v := range vals {
		args[i] = v
	}
	placeholders := make([]byte, 0, len(vals)*2)
	for i := range vals {
		if i > 0 {
			placeholders = append(placeholders, ',', ' ')
		}
		placeholders = append(placeholders, '?')
	}
	return sqlgen.Where("\""+f.col+"\" IN ("+string(placeholders)+")", args...)
}

// CommentCommentableTypeFilter provides where clauses for the commentable_type column.
type CommentCommentableTypeFilter struct {
	col string
}

func (f CommentCommentableTypeFilter) EQ(val string) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" = ?", val)
}

func (f CommentCommentableTypeFilter) NEQ(val string) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" != ?", val)
}

func (f CommentCommentableTypeFilter) LT(val string) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" < ?", val)
}

func (f CommentCommentableTypeFilter) LTE(val string) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" <= ?", val)
}

func (f CommentCommentableTypeFilter) GT(val string) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" > ?", val)
}

func (f CommentCommentableTypeFilter) GTE(val string) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" >= ?", val)
}

func (f CommentCommentableTypeFilter) IN(vals ...string) sqlgen.QueryMod {
	args := make([]any, len(vals))
	for i, v := range vals {
		args[i] = v
	}
	placeholders := make([]byte, 0, len(vals)*2)
	for i := range vals {
		if i > 0 {
			placeholders = append(placeholders, ',', ' ')
		}
		placeholders = append(placeholders, '?')
	}
	return sqlgen.Where("\""+f.col+"\" IN ("+string(placeholders)+")", args...)
}

// CommentCommentableIDFilter provides where clauses for the commentable_id column.
type CommentCommentableIDFilter struct {
	col string
}

func (f CommentCommentableIDFilter) EQ(val string) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" = ?", val)
}

func (f CommentCommentableIDFilter) NEQ(val string) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" != ?", val)
}

func (f CommentCommentableIDFilter) LT(val string) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" < ?", val)
}

func (f CommentCommentableIDFilter) LTE(val string) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" <= ?", val)
}

func (f CommentCommentableIDFilter) GT(val string) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" > ?", val)
}

func (f CommentCommentableIDFilter) GTE(val string) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" >= ?", val)
}

func (f CommentCommentableIDFilter) IN(vals ...string) sqlgen.QueryMod {
	args := make([]any, len(vals))
	for i, v := range vals {
		args[i] = v
	}
	placeholders := make([]byte, 0, len(vals)*2)
	for i := range vals {
		if i > 0 {
			placeholders = append(placeholders, ',', ' ')
		}
		placeholders = append(placeholders, '?')
	}
	return sqlgen.Where("\""+f.col+"\" IN ("+string(placeholders)+")", args...)
}

// CommentKindFilter provides where clauses for the kind column.
type CommentKindFilter struct {
	col string
}

func (f CommentKindFilter) EQ(val CommentKind) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" = ?", val)
}

func (f CommentKindFilter) NEQ(val CommentKind) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" != ?", val)
}

func (f CommentKindFilter) LT(val CommentKind) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" < ?", val)
}

func (f CommentKindFilter) LTE(val CommentKind) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" <= ?", val)
}

func (f CommentKindFilter) GT(val CommentKind) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" > ?", val)
}

func (f CommentKindFilter) GTE(val CommentKind) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" >= ?", val)
}

func (f CommentKindFilter) IN(vals ...CommentKind) sqlgen.QueryMod {
	args := make([]any, len(vals))
	for i, v := range vals {
		args[i] = v
	}
	placeholders := make([]byte, 0, len(vals)*2)
	for i := range vals {
		if i > 0 {
			placeholders = append(placeholders, ',', ' ')
		}
		placeholders = append(placeholders, '?')
	}
	return sqlgen.Where("\""+f.col+"\" IN ("+string(placeholders)+")", args...)
}

// CommentBodyFilter provides where clauses for the body column.
type CommentBodyFilter struct {
	col string
}

func (f CommentBodyFilter) EQ(val string) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" = ?", val)
}

func (f CommentBodyFilter) NEQ(val string) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" != ?", val)
}

func (f CommentBodyFilter) LT(val string) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" < ?", val)
}

func (f CommentBodyFilter) LTE(val string) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" <= ?", val)
}

func (f CommentBodyFilter) GT(val string) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" > ?", val)
}

func (f CommentBodyFilter) GTE(val string) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" >= ?", val)
}

func (f CommentBodyFilter) IN(vals ...string) sqlgen.QueryMod {
	args := make([]any, len(vals))
	for i, v := range vals {
		args[i] = v
	}
	placeholders := make([]byte, 0, len(vals)*2)
	for i := range vals {
		if i > 0 {
			placeholders = append(placeholders, ',', ' ')
		}
		placeholders = append(placeholders, '?')
	}
	return sqlgen.Where("\""+f.col+"\" IN ("+string(placeholders)+")", args...)
}

// CommentCreatedAtFilter provides where clauses for the created_at column.
type CommentCreatedAtFilter struct {
	col string
}

func (f CommentCreatedAtFilter) EQ(val time.Time) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" = ?", val)
}

func (f CommentCreatedAtFilter) NEQ(val time.Time) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" != ?", val)
}

func (f CommentCreatedAtFilter) LT(val time.Time) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" < ?", val)
}

func (f CommentCreatedAtFilter) LTE(val time.Time) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" <= ?", val)
}

func (f CommentCreatedAtFilter) GT(val time.Time) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" > ?", val)
}

func (f CommentCreatedAtFilter) GTE(val time.Time) sqlgen.QueryMod {
	return sqlgen.Where("\""+f.col+"\" >= ?", val)
}

func (f CommentCreatedAtFilter) IN(vals ...time.Time) sqlgen.QueryMod {
	args := make([]any, len(vals))
	for i, v := range vals {
		args[i] = v
	}
	placeholders := make([]byte, 0, len(vals)*2)
	for i := range vals {
		if i > 0 {
			placeholders = append(placeholders, ',', ' ')
		}
		placeholders = append(placeholders, '?')
	}
	return sqlgen.Where("\""+f.col+"\" IN ("+string(placeholders)+")", args...)
}
