// Code generated by sqlgen. DO NOT EDIT.

package models

import (
	"context"
	"fmt"

	"github.com/davidbyttow/sqlgen"
)

// commentLoaders maps relationship names to their loader functions.
var commentLoaders = map[string]sqlgen.LoadFunc{}

func init() {
	commentLoaders["User"] = loadCommentUser
	commentLoaders["Post"] = loadCommentPost
}

// LoadRelations eagerly loads the specified relationships for a slice of Comment.
func (s CommentSlice) LoadRelations(ctx context.Context, exec sqlgen.Executor, loads ...*sqlgen.EagerLoadRequest) error {
	for _, load := range loads {
		fn, ok := commentLoaders[load.Name]
		if !ok {
			return fmt.Errorf("unknown relationship %q on Comment", load.Name)
		}
		if err := fn(ctx, exec, dialect, s, loads); err != nil {
			return fmt.Errorf("loading %s: %w", load.Name, err)
		}
	}
	return nil
}

// commentLoadMods extracts query mods for the named relationship from the load requests.
func commentLoadMods(loads []*sqlgen.EagerLoadRequest, name string) []sqlgen.QueryMod {
	for _, l := range loads {
		if l.Name == name {
			return l.Mods
		}
	}
	return nil
}

func loadCommentUser(ctx context.Context, exec sqlgen.Executor, d sqlgen.Dialect, parentModels any, loads []*sqlgen.EagerLoadRequest) error {
	models := parentModels.(CommentSlice)
	if len(models) == 0 {
		return nil
	}

	// Collect unique FK values.
	seen := make(map[string]bool)
	var ids []any
	for _, m := range models {
		key := fmt.Sprint(m.AuthorID)
		if !seen[key] {
			seen[key] = true
			ids = append(ids, m.AuthorID)
		}
	}

	mods := commentLoadMods(loads, "User")
	rows, err := sqlgen.LoadMany(ctx, exec, d, UserTableName, "id", ids, mods...)
	if err != nil {
		return err
	}
	if rows == nil {
		return nil
	}
	defer rows.Close()

	resultMap := make(map[string]*User)
	for rows.Next() {
		o := &User{}
		if err := o.ScanRow(rows); err != nil {
			return err
		}
		resultMap[fmt.Sprint(o.ID)] = o
	}
	if err := rows.Err(); err != nil {
		return err
	}

	for _, m := range models {
		o := resultMap[fmt.Sprint(m.AuthorID)]
		if o != nil {
			if m.R == nil {
				m.R = &CommentRels{}
			}
			m.R.User = o
		}
	}
	return nil
}

func loadCommentPost(ctx context.Context, exec sqlgen.Executor, d sqlgen.Dialect, parentModels any, loads []*sqlgen.EagerLoadRequest) error {
	models := parentModels.(CommentSlice)
	if len(models) == 0 {
		return nil
	}

	// Only load for models matching this type value.
	seen := make(map[string]bool)
	var ids []any
	for _, m := range models {
		if m.CommentableType != "Post" {
			continue
		}
		key := fmt.Sprint(m.CommentableID)
		if !seen[key] {
			seen[key] = true
			ids = append(ids, m.CommentableID)
		}
	}
	if len(ids) == 0 {
		return nil
	}

	mods := commentLoadMods(loads, "Post")
	rows, err := sqlgen.LoadMany(ctx, exec, d, PostTableName, "id", ids, mods...)
	if err != nil {
		return err
	}
	if rows == nil {
		return nil
	}
	defer rows.Close()

	resultMap := make(map[string]*Post)
	for rows.Next() {
		o := &Post{}
		if err := o.ScanRow(rows); err != nil {
			return err
		}
		resultMap[fmt.Sprint(o.ID)] = o
	}
	if err := rows.Err(); err != nil {
		return err
	}

	for _, m := range models {
		if m.CommentableType != "Post" {
			continue
		}
		o := resultMap[fmt.Sprint(m.CommentableID)]
		if o != nil {
			if m.R == nil {
				m.R = &CommentRels{}
			}
			m.R.Post = o
		}
	}
	return nil
}
