// Code generated by sqlgen. DO NOT EDIT.

package models

import (
	"context"

	"github.com/davidbyttow/sqlgen"
)

// SetProfile sets the Profile relationship by updating the related model's FK.
func (o *User) SetProfile(ctx context.Context, exec sqlgen.Executor, related *Profile) error {
	related.UserID = o.ID
	query := "UPDATE " + dialect.QuoteIdent(ProfileTableName) +
		" SET " + dialect.QuoteIdent("user_id") + " = " + dialect.Placeholder(1) +
		" WHERE " + dialect.QuoteIdent("id") + " = " + dialect.Placeholder(2)
	_, err := exec.ExecContext(ctx, query, related.UserID, related.ID)
	if err != nil {
		return err
	}
	if o.R == nil {
		o.R = &UserRels{}
	}
	o.R.Profile = related
	return nil
}

// AddPosts adds models to the Posts relationship by setting their FK.
func (o *User) AddPosts(ctx context.Context, exec sqlgen.Executor, related ...*Post) error {
	for _, r := range related {
		r.AuthorID = o.ID
		query := "UPDATE " + dialect.QuoteIdent(PostTableName) +
			" SET " + dialect.QuoteIdent("author_id") + " = " + dialect.Placeholder(1) +
			" WHERE " + dialect.QuoteIdent("id") + " = " + dialect.Placeholder(2)
		_, err := exec.ExecContext(ctx, query, r.AuthorID, r.ID)
		if err != nil {
			return err
		}
	}
	if o.R == nil {
		o.R = &UserRels{}
	}
	o.R.Posts = append(o.R.Posts, related...)
	return nil
}

// AddComments adds models to the Comments relationship by setting their FK.
func (o *User) AddComments(ctx context.Context, exec sqlgen.Executor, related ...*Comment) error {
	for _, r := range related {
		r.AuthorID = o.ID
		query := "UPDATE " + dialect.QuoteIdent(CommentTableName) +
			" SET " + dialect.QuoteIdent("author_id") + " = " + dialect.Placeholder(1) +
			" WHERE " + dialect.QuoteIdent("id") + " = " + dialect.Placeholder(2)
		_, err := exec.ExecContext(ctx, query, r.AuthorID, r.ID)
		if err != nil {
			return err
		}
	}
	if o.R == nil {
		o.R = &UserRels{}
	}
	o.R.Comments = append(o.R.Comments, related...)
	return nil
}
