// Code generated by sqlgen. DO NOT EDIT.

package models

import (
	"database/sql/driver"
	"fmt"
)

// CommentKind is the 'comment_kind' enum type.
type CommentKind string

const (
	CommentKindReview CommentKind = "review"
	CommentKindReply  CommentKind = "reply"
	CommentKindNote   CommentKind = "note"
)

// AllCommentKindValues returns all valid values for this enum.
func AllCommentKindValues() []CommentKind {
	return []CommentKind{
		CommentKindReview,
		CommentKindReply,
		CommentKindNote,
	}
}

// IsValid checks if the value is a valid enum value.
func (e CommentKind) IsValid() bool {
	switch e {
	case CommentKindReview:
		return true
	case CommentKindReply:
		return true
	case CommentKindNote:
		return true
	}
	return false
}

// String returns the string representation.
func (e CommentKind) String() string {
	return string(e)
}

// Scan implements sql.Scanner.
func (e *CommentKind) Scan(src any) error {
	if src == nil {
		return fmt.Errorf("sqlgen: cannot scan nil into CommentKind")
	}
	switch v := src.(type) {
	case string:
		*e = CommentKind(v)
	case []byte:
		*e = CommentKind(string(v))
	default:
		return fmt.Errorf("sqlgen: cannot scan %T into CommentKind", src)
	}
	if !e.IsValid() {
		return fmt.Errorf("sqlgen: invalid CommentKind value: %q", *e)
	}
	return nil
}

// Value implements driver.Valuer.
func (e CommentKind) Value() (driver.Value, error) {
	if !e.IsValid() {
		return nil, fmt.Errorf("sqlgen: invalid CommentKind value: %q", e)
	}
	return string(e), nil
}
