// Code generated by sqlgen. DO NOT EDIT.

package models

import (
	"context"

	"github.com/davidbyttow/sqlgen"
)

// profileHooks stores the hooks for Profile.
var profileHooks = sqlgen.NewHooks()

// ProfileHook is a typed hook function for Profile lifecycle events.
type ProfileHook func(ctx context.Context, exec sqlgen.Executor, model *Profile) (context.Context, error)

// AddProfileHook registers a typed hook for the given hook point.
// The hook receives the model pointer and can inspect or modify it.
func AddProfileHook(point sqlgen.HookPoint, fn ProfileHook) {
	profileHooks.Add(point, func(ctx context.Context, exec sqlgen.Executor, model any) (context.Context, error) {
		return fn(ctx, exec, model.(*Profile))
	})
}
