// Code generated by sqlgen. DO NOT EDIT.

package models

import (
	"encoding/json"
	"time"

	"github.com/davidbyttow/sqlgen"
)

// UserTableName is the database table name.
const UserTableName = "users"

// UserColumns contains all column names for the users table.
var UserColumns = struct {
	ID        string
	Email     string
	Name      string
	Bio       string
	Age       string
	Score     string
	IsAdmin   string
	Metadata  string
	CreatedAt string
}{
	ID:        "id",
	Email:     "email",
	Name:      "name",
	Bio:       "bio",
	Age:       "age",
	Score:     "score",
	IsAdmin:   "is_admin",
	Metadata:  "metadata",
	CreatedAt: "created_at",
}

// User represents a row from the 'users' table.
type User struct {
	ID        string                       `db:"id" json:"id"`
	Email     string                       `db:"email" json:"email"`
	Name      string                       `db:"name" json:"name"`
	Bio       sqlgen.Null[string]          `db:"bio" json:"bio"`
	Age       sqlgen.Null[int32]           `db:"age" json:"age"`
	Score     sqlgen.Null[string]          `db:"score" json:"score"`
	IsAdmin   bool                         `db:"is_admin" json:"is_admin"`
	Metadata  sqlgen.Null[json.RawMessage] `db:"metadata" json:"metadata"`
	CreatedAt time.Time                    `db:"created_at" json:"created_at"`

	R *UserRels `db:"-" json:"-"`
}

// UserRels holds eagerly loaded relationships.
type UserRels struct {
	Profile       *Profile
	Posts         []*Post
	PostsCount    *int64
	Comments      []*Comment
	CommentsCount *int64
}

// UserSlice is a slice of User pointers.
type UserSlice []*User

// ScanRow scans a database row into a User.
func (o *User) ScanRow(rows interface{ Scan(...any) error }) error {
	return rows.Scan(
		&o.ID,
		&o.Email,
		&o.Name,
		&o.Bio,
		&o.Age,
		&o.Score,
		&o.IsAdmin,
		&o.Metadata,
		&o.CreatedAt,
	)
}

// scanDests returns scan destinations for all columns (used by preload-aware queries).
func (o *User) scanDests() []any {
	return []any{
		&o.ID,
		&o.Email,
		&o.Name,
		&o.Bio,
		&o.Age,
		&o.Score,
		&o.IsAdmin,
		&o.Metadata,
		&o.CreatedAt,
	}
}
