// Code generated by sqlgen. DO NOT EDIT.

package models

import (
	"encoding/json"
	"time"

	"github.com/davidbyttow/sqlgen"
)

// postUserPreload holds nullable scan targets for LEFT JOINed User columns.
type postUserPreload struct {
	id        sqlgen.Null[string]
	email     sqlgen.Null[string]
	name      sqlgen.Null[string]
	bio       sqlgen.Null[string]
	age       sqlgen.Null[int32]
	score     sqlgen.Null[string]
	isAdmin   sqlgen.Null[bool]
	metadata  sqlgen.Null[json.RawMessage]
	createdAt sqlgen.Null[time.Time]
}

func (p *postUserPreload) scanDests() []any {
	return []any{
		&p.id,
		&p.email,
		&p.name,
		&p.bio,
		&p.age,
		&p.score,
		&p.isAdmin,
		&p.metadata,
		&p.createdAt,
	}
}

func (p *postUserPreload) assign(o *Post) {
	if !p.id.Valid {
		return
	}
	if o.R == nil {
		o.R = &PostRels{}
	}
	o.R.User = &User{
		ID:        p.id.Val,
		Email:     p.email.Val,
		Name:      p.name.Val,
		Bio:       p.bio,
		Age:       p.age,
		Score:     p.score,
		IsAdmin:   p.isAdmin.Val,
		Metadata:  p.metadata,
		CreatedAt: p.createdAt.Val,
	}
}

// PostPreloadUser is the PreloadDef for the User relationship.
var PostPreloadUser = sqlgen.PreloadDef{
	Name:     "User",
	Table:    UserTableName,
	JoinCond: "\"users\".\"id\" = \"posts\".\"author_id\"",
	Columns: []string{
		"\"users\".\"id\"",
		"\"users\".\"email\"",
		"\"users\".\"name\"",
		"\"users\".\"bio\"",
		"\"users\".\"age\"",
		"\"users\".\"score\"",
		"\"users\".\"is_admin\"",
		"\"users\".\"metadata\"",
		"\"users\".\"created_at\"",
	},
}

// postCategoryPreload holds nullable scan targets for LEFT JOINed Category columns.
type postCategoryPreload struct {
	id       sqlgen.Null[int32]
	name     sqlgen.Null[string]
	parentID sqlgen.Null[int32]
}

func (p *postCategoryPreload) scanDests() []any {
	return []any{
		&p.id,
		&p.name,
		&p.parentID,
	}
}

func (p *postCategoryPreload) assign(o *Post) {
	if !p.id.Valid {
		return
	}
	if o.R == nil {
		o.R = &PostRels{}
	}
	o.R.Category = &Category{
		ID:       p.id.Val,
		Name:     p.name.Val,
		ParentID: p.parentID,
	}
}

// PostPreloadCategory is the PreloadDef for the Category relationship.
var PostPreloadCategory = sqlgen.PreloadDef{
	Name:     "Category",
	Table:    CategoryTableName,
	JoinCond: "\"categories\".\"id\" = \"posts\".\"category_id\"",
	Columns: []string{
		"\"categories\".\"id\"",
		"\"categories\".\"name\"",
		"\"categories\".\"parent_id\"",
	},
}

// postPreloadState is the interface for preload scan states.
type postPreloadState interface {
	scanDests() []any
	assign(o *Post)
}

// newPostPreloadState returns a preload state for the named relationship.
func newPostPreloadState(name string) postPreloadState {
	switch name {
	case "User":
		return &postUserPreload{}
	case "Category":
		return &postCategoryPreload{}
	}
	return nil
}
