// Code generated by sqlgen. DO NOT EDIT.

package models

import (
	"database/sql/driver"
	"fmt"
)

// PostStatus is the 'post_status' enum type.
type PostStatus string

const (
	PostStatusDraft     PostStatus = "draft"
	PostStatusPublished PostStatus = "published"
	PostStatusArchived  PostStatus = "archived"
)

// AllPostStatusValues returns all valid values for this enum.
func AllPostStatusValues() []PostStatus {
	return []PostStatus{
		PostStatusDraft,
		PostStatusPublished,
		PostStatusArchived,
	}
}

// IsValid checks if the value is a valid enum value.
func (e PostStatus) IsValid() bool {
	switch e {
	case PostStatusDraft:
		return true
	case PostStatusPublished:
		return true
	case PostStatusArchived:
		return true
	}
	return false
}

// String returns the string representation.
func (e PostStatus) String() string {
	return string(e)
}

// Scan implements sql.Scanner.
func (e *PostStatus) Scan(src any) error {
	if src == nil {
		return fmt.Errorf("sqlgen: cannot scan nil into PostStatus")
	}
	switch v := src.(type) {
	case string:
		*e = PostStatus(v)
	case []byte:
		*e = PostStatus(string(v))
	default:
		return fmt.Errorf("sqlgen: cannot scan %T into PostStatus", src)
	}
	if !e.IsValid() {
		return fmt.Errorf("sqlgen: invalid PostStatus value: %q", *e)
	}
	return nil
}

// Value implements driver.Valuer.
func (e PostStatus) Value() (driver.Value, error) {
	if !e.IsValid() {
		return nil, fmt.Errorf("sqlgen: invalid PostStatus value: %q", e)
	}
	return string(e), nil
}
